unpackaged/main/default/objects/AuditLogEntry__c/AuditLogEntry__c.object-meta.xml
<CustomObject>
    <description>An audit log of key events that occur in the org.</description>
    <label>Audit Log Entry</label>
    <nameField>
        <displayFormat>ALE-{0}</displayFormat>
        <label>Audit Log Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Log Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AuditLogEntry__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>The ID of the record this audit log relates to.</description>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AuditLogEntry__c/fields/RecordObject__c.field-meta.xml
<CustomField>
    <fullName>RecordObject__c</fullName>
    <description>The name to which this audit log entry relates.</description>
    <label>Record Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuditLogEntry__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>The ID of the user who triggered the event.</description>
    <label>User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuditLogEntryTest.cls
@isTest
public with sharing class AuditLogEntryTest {

    // Create an account whose access will be audited
    @testSetup static void setup() {
        TestDataFactory.createHousehold(1, 0, 'AUDIT_LOG_TEST');
    }

    // Run test with expectation of creating audit log
    @istest
    static void testCreateAudit() {
        List<Account> accs = [SELECT Id FROM Account WHERE AccountNumber = 'AUDIT_LOG_TEST'];
        AuditLogEntry.createAuditLogEntry(accs[0].Id, 'Account', false);
        List<AuditLogEntry__c> ales = [SELECT Id, RecordId__c, RecordObject__c, UserId__c FROM AuditLogEntry__c WHERE RecordId__c = :accs[0].Id];
        System.assertEquals(ales.size(), 1);
        System.assertEquals(ales[0].RecordObject__c, 'Account');
        System.assertEquals(ales[0].UserId__c, UserInfo.getUserId());
    }

    // Run test with expectation of skipping audit log creation
    @istest
    static void testSkipAudit() {
        List<Account> accs = [SELECT Id FROM Account WHERE AccountNumber = 'AUDIT_LOG_TEST'];
        AuditLogEntry.createAuditLogEntry(accs[0].Id, 'Account', true);
        List<AuditLogEntry__c> ales = [SELECT Id, RecordId__c, RecordObject__c, UserId__c FROM AuditLogEntry__c WHERE RecordId__c = :accs[0].Id];
        System.assertEquals(ales.size(), 0);
    }

    // Run test with expectation of failure due to no record ID or object name
    @istest
    static void testAuditError() {
        List<Account> accs = [SELECT Id FROM Account WHERE AccountNumber = 'AUDIT_LOG_TEST'];
        AuditLogEntry.createAuditLogEntry('', '', false);
        List<AuditLogEntry__c> ales = [SELECT Id, RecordId__c, RecordObject__c, UserId__c FROM AuditLogEntry__c WHERE RecordId__c = :accs[0].Id];
        System.assertEquals(ales.size(), 0);
    }
}