unpackaged/main/default/objects/AuditLogEntry__c/AuditLogEntry__c.object-meta.xml
<CustomObject>
    <description>An audit log of key events that occur in the org.</description>
    <label>Audit Log Entry</label>
    <nameField>
        <displayFormat>ALE-{0}</displayFormat>
        <label>Audit Log Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Log Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AuditLogEntry__c/fields/EventDate__c.field-meta.xml
<CustomField>
    <fullName>EventDate__c</fullName>
    <description>The date and time of the event.</description>
    <label>Event Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AuditLogEntry__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <description>The type of event being audited.</description>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Page view</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AuditLogEntry__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>The ID of the record this audit log relates to.</description>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AuditLogEntry__c/fields/RecordName__c.field-meta.xml
<CustomField>
    <fullName>RecordName__c</fullName>
    <label>Record Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AuditLogEntry__c/fields/RecordObject__c.field-meta.xml
<CustomField>
    <fullName>RecordObject__c</fullName>
    <description>The name to which this audit log entry relates.</description>
    <label>Record Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuditLogEntry__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>The ID of the user who triggered the event.</description>
    <label>User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AuditLogEntry__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <label>User Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuditLogEntry.cls
/**
    * @description This class controls the capturing of audit log entries. 
*/
public without sharing class AuditLogEntry {

    /**
    * @description Takes a record ID and object API name and captures audits who has viewed that record
        * @param recordId - the ID of the record being viewed
        * @param objectApiName - the object being viewed
        * @param audited - if the view has already been audited or not
        * @return audited - whether an audit record has been captured or not
    */
    @AuraEnabled
    public static Boolean createAuditLogEntry(String recordId, String objectApiName, Boolean audited){
        if(audited == false){
            if(!String.isEmpty(recordId) && !String.isEmpty(objectApiName)){
                String eventType = 'Page view';
                Id defaultOwnerId = '0054J000005ZwOKQA0';
                String recordName;
                List<sObject> records = Database.query('SELECT Id, Name FROM ' + objectApiName + ' WHERE Id = :recordId');
                if(records.size() == 1){
                    recordName = (String) records[0].get('Name');
                } else if(records.size() == 0){
                    recordName = 'Err: no record';
                } else {
                    recordName = 'Err: multiple records';
                }
                AuditLogEntry__c log = new AuditLogEntry__c(
                    RecordId__c = recordId, 
                    EventDate__c = DateTime.now(),
                    EventType__c = eventType,
                    UserId__c = UserInfo.getUserId(),
                    UserName__c = UserInfo.getName(),
                    OwnerId = defaultOwnerId,
                    RecordName__c = recordName,
                    RecordObject__c = objectApiName
                );
                try {
                    insert log;
                    audited = true;
                } catch(DmlException e) {
                    audited = false;
                    System.debug('Audit failed with exception: ' + e.getMessage());
                }
            } else {
                audited = false;
            }
            
        }
        return audited;
    }
}