force-app/main/default/objects/OW_task_information__c/OW_task_information__c.object-meta.xml
<CustomObject>
    <description>This object stores reference data related to tasks carried out by people across Octopus Wealth. In addition to a description of how to perform the task, there is useful information stored like which team performs it, whether the task is active, and which part of the process it falls under.</description>
    <label>Task Information</label>
    <nameField>
        <label>Task Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_description_google_doc_link__c.field-meta.xml
<CustomField>
    <fullName>OW_task_description_google_doc_link__c</fullName>
    <description>Stores the link to the Google Doc where the task description is mastered.</description>
    <label>Task description Google Doc link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_type__c.field-meta.xml
<CustomField>
    <fullName>OW_task_type__c</fullName>
    <description>A code that will identify the type of task this task information record represents.</description>
    <label>Task type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LwcHelperTaskOrchestrator.cls
public with sharing class LwcHelperTaskOrchestrator {
    @AuraEnabled(cacheable=true)
    public static OW_task_information__c getTaskInfoByTaskName(String taskTypeName) {
        List<OW_task_information__c> info = [
            SELECT Id, OW_task_type__c, OW_task_description_google_doc_link__c
            FROM OW_task_information__c
            WHERE OW_task_type__c = :taskTypeName
            LIMIT 1
        ];

        if(info.size() > 0) {
            return info[0];
        }
        return null;
    }
}