force-app/main/default/objects/OW_task_information__c/OW_task_information__c.object-meta.xml
<CustomObject>
    <description>This object stores reference data related to tasks carried out by people across Octopus Wealth. In addition to a description of how to perform the task, there is useful information stored like which team performs it, whether the task is active, and which part of the process it falls under.</description>
    <label>Task Information</label>
    <nameField>
        <label>Task Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_record_type_developer_name__c.field-meta.xml
<CustomField>
    <fullName>OW_record_type_developer_name__c</fullName>
    <description>This field holds the developer name of the task record type. This is the unique reference used to identify to which task record type this information relates.</description>
    <inlineHelpText>This is a unique reference to the record type. This MUST NOT be changed without understanding the implications or it will stop task information from displaying when viewing tasks.</inlineHelpText>
    <label>Record type developer name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_description__c.field-meta.xml
<CustomField>
    <fullName>OW_task_description__c</fullName>
    <description>This is the description of how to complete this task.</description>
    <label>Task description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_type__c.field-meta.xml
<CustomField>
    <fullName>OW_task_type__c</fullName>
    <description>A code that will identify the type of task this task information record represents.</description>
    <label>Task type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/OW_task_ad_hoc.recordType-meta.xml
<RecordType>
    <fullName>OW_task_ad_hoc</fullName>
    <active>true</active>
    <description>Tasks created manually by users.</description>
    <label>#Client task (ad-hoc)</label>
</RecordType>

unpackaged/main/default/objects/Task/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>false</active>
    <label>zDel Test</label>
</RecordType>

force-app/main/default/classes/TaskInformationControllerTest.cls
@istest
public class TaskInformationControllerTest {
    
    @istest
    private static void testFetchingTaskInformation() {
        
        String task_id = 'random_id'; 
        
        // Create and insert a task information record for the same record type specified in the line below        
        OW_task_information__c ti = new OW_task_information__c(
            OW_record_type_developer_name__c = 'record_type_name',
            OW_task_type__c = task_id,
            Name = 'Test task information ',
            OW_task_description__c = 'Test description'
        );
        insert ti;
        
        // Create and insert a task with the record type specified in the line below
        Task t = new Task(
            OW_task_information_identifier__c = ti.Id,
            Subject = 'Test subject'
        );
        insert t;
        
        // Run the class for the task created
        Test.startTest();
        OW_task_information__c taskInfo = TaskInformationController.getTaskInfo( t.Id );
        Test.stopTest();

        // Assert that the task information record returned by the class matches the one created above
        System.assertEquals(taskInfo.Id, ti.Id);
    }
    
    @istest
    private static void testFetchingTaskInformationLegacy() {
        
        // Create and insert a task with the record type specified in the line below
        String record_type_name = 'OW_task_ad_hoc'; 
        Task t = new Task(
            RecordTypeId = Schema.sObjectType.Task.getRecordTypeInfosByDeveloperName().get(record_type_name).getRecordTypeId(),
            Subject = 'Test subject'
        );
        insert t;
		
        // Create and insert a task information record for the same record type specified in the line below        
        OW_task_information__c ti = new OW_task_information__c(
            OW_record_type_developer_name__c = record_type_name,
            Name = 'Test task information ',
            OW_task_description__c = 'Test description'
        );
        insert ti;
        
        // Run the class for the task created
        Test.startTest();
        OW_task_information__c taskInfo = TaskInformationController.getTaskInfo( t.Id );
        Test.stopTest();

        // Assert that the task information record returned by the class matches the one created above
        System.assertEquals(taskInfo.Id, ti.Id);
    }
}