force-app/main/default/objects/OW_task_information__c/OW_task_information__c.object-meta.xml
<CustomObject>
    <description>This object stores reference data related to tasks carried out by people across Octopus Wealth. In addition to a description of how to perform the task, there is useful information stored like which team performs it, whether the task is active, and which part of the process it falls under.</description>
    <label>Task Information</label>
    <nameField>
        <label>Task Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_record_type_developer_name__c.field-meta.xml
<CustomField>
    <fullName>OW_record_type_developer_name__c</fullName>
    <description>This field holds the developer name of the task record type. This is the unique reference used to identify to which task record type this information relates.</description>
    <inlineHelpText>This is a unique reference to the record type. This MUST NOT be changed without understanding the implications or it will stop task information from displaying when viewing tasks.</inlineHelpText>
    <label>Record type developer name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_description_google_doc_link__c.field-meta.xml
<CustomField>
    <fullName>OW_task_description_google_doc_link__c</fullName>
    <description>Stores the link to the Google Doc where the task description is mastered.</description>
    <label>Task description Google Doc link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_type__c.field-meta.xml
<CustomField>
    <fullName>OW_task_type__c</fullName>
    <description>A code that will identify the type of task this task information record represents.</description>
    <label>Task type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LwcHelperTaskOrchestratorTest.cls
@isTest
public class LwcHelperTaskOrchestratorTest {

    private static final String TASK_TYPE = 'test_type';

    @IsTest
    public static void testGetTaskInfoByTaskName() {
        OW_task_information__c taskInfo = new OW_task_information__c();
        taskInfo.OW_task_type__c = TASK_TYPE;
        taskInfo.OW_record_type_developer_name__c = TASK_TYPE;
        taskInfo.OW_task_description_google_doc_link__c = 'https://google.com';
        insert taskInfo;

        test.startTest();
        OW_task_information__c fetchedTaskInfo = LwcHelperTaskOrchestrator.getTaskInfoByTaskName(TASK_TYPE);
        Assert.areEqual(taskInfo.Id, fetchedTaskInfo.Id);
        test.stopTest();
    }

}