force-app/main/default/objects/OW_task_information__c/OW_task_information__c.object-meta.xml
<CustomObject>
    <description>This object stores reference data related to tasks carried out by people across Octopus Wealth. In addition to a description of how to perform the task, there is useful information stored like which team performs it, whether the task is active, and which part of the process it falls under.</description>
    <label>Task Information</label>
    <nameField>
        <label>Task Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_task_information__c/fields/OW_assigned_to__c.field-meta.xml
<CustomField>
    <fullName>OW_assigned_to__c</fullName>
    <description>The team that this task is normally completed by.</description>
    <label>Assigned To</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Case owner</fullName>
            </value>
            <value>
                <fullName>Chosen user</fullName>
            </value>
            <value>
                <fullName>Dedicated specialist/household team</fullName>
            </value>
            <value>
                <fullName>Household team</fullName>
            </value>
            <value>
                <fullName>Opportunity owner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Specific user</fullName>
            </value>
            <value>
                <fullName>Suitability planner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_due_date__c.field-meta.xml
<CustomField>
    <fullName>OW_due_date__c</fullName>
    <description>A description of when this task is due, in relation to its creation (eg, due immediately, due 7 days later, etc).</description>
    <label>Due date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_process_variant__c.field-meta.xml
<CustomField>
    <fullName>OW_process_variant__c</fullName>
    <description>Describes whether this task is part of an old or new process (eg old factfind or new profile).</description>
    <label>Process Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Legacy Wealth Management</fullName>
            </value>
            <value>
                <fullName>Current Wealth Management Process</fullName>
            </value>
            <value>
                <fullName>New customer</fullName>
            </value>
            <value>
                <fullName>Annual review</fullName>
            </value>
            <value>
                <fullName>Tax year end</fullName>
            </value>
            <value>
                <fullName>Follow on advice</fullName>
            </value>
            <value>
                <fullName>Nurture lead</fullName>
            </value>
            <value>
                <fullName>Manage opportunity</fullName>
            </value>
            <value>
                <fullName>Manage application</fullName>
            </value>
            <value>
                <fullName>Employee onboarding</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder Turning 18</fullName>
            </value>
            <value>
                <fullName>Customer support</fullName>
            </value>
            <value>
                <fullName>Protection advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_record_type_developer_name__c.field-meta.xml
<CustomField>
    <fullName>OW_record_type_developer_name__c</fullName>
    <description>This field holds the developer name of the task record type. This is the unique reference used to identify to which task record type this information relates.</description>
    <inlineHelpText>This is a unique reference to the record type. This MUST NOT be changed without understanding the implications or it will stop task information from displaying when viewing tasks.</inlineHelpText>
    <label>Record type developer name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_requires_4eye__c.field-meta.xml
<CustomField>
    <fullName>OW_requires_4eye__c</fullName>
    <description>Indicates whether this specific task needs a 4eye check before it can be completed.</description>
    <label>Requires 4eye?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Dependent on experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_stage__c.field-meta.xml
<CustomField>
    <fullName>OW_stage__c</fullName>
    <description>The stage of the advice process that this task falls under.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_process_variant__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Nurturing</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Data Gathering</fullName>
            </value>
            <value>
                <fullName>Suitability</fullName>
            </value>
            <value>
                <fullName>Fulfilment</fullName>
            </value>
            <value>
                <fullName>Annual Review</fullName>
            </value>
            <value>
                <fullName>Unactioned</fullName>
            </value>
            <value>
                <fullName>Gather information</fullName>
            </value>
            <value>
                <fullName>Broker mortgage</fullName>
            </value>
            <value>
                <fullName>Await completion</fullName>
            </value>
            <value>
                <fullName>Mortgage complete</fullName>
            </value>
            <value>
                <fullName>Applying for DIP</fullName>
            </value>
            <value>
                <fullName>DIP granted</fullName>
            </value>
            <value>
                <fullName>Agree product</fullName>
            </value>
            <value>
                <fullName>Provide advice</fullName>
            </value>
            <value>
                <fullName>Applying for mortgage</fullName>
            </value>
            <value>
                <fullName>Mortgage offered</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_status__c.field-meta.xml
<CustomField>
    <fullName>OW_status__c</fullName>
    <description>The status of the task description itself.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Out of date</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_description__c.field-meta.xml
<CustomField>
    <fullName>OW_task_description__c</fullName>
    <description>This is the description of how to complete this task.</description>
    <label>Task description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_triggered_by__c.field-meta.xml
<CustomField>
    <fullName>OW_triggered_by__c</fullName>
    <description>The trigger that causes this task to be completed (eg completion of a process street checklist, tickbox being checked)</description>
    <inlineHelpText>A text description of what triggers this task.</inlineHelpText>
    <label>Triggered by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_triggers__c.field-meta.xml
<CustomField>
    <fullName>OW_triggers__c</fullName>
    <description>The event triggered by completion of this task (eg another task, or nothing).</description>
    <label>Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaskInformationController.cls
public class TaskInformationController {
    
    @AuraEnabled
    public static OW_task_information__c getTaskInfo(String taskId){
        
        // Get the record type first for the given task. 
        // No error handling for null return or multiple results as this class will be called by a Lightning component
        // on a task record page so we can trust that the task ID can only and will always return 1 result.
        Task t = [SELECT OW_task_information_identifier__c, RecordType.DeveloperName FROM Task WHERE Id =: taskId LIMIT 1];
        
        // Get the task information for the given task record type.
        // Max 1 result will be returned as the field in the WHERE statement is unique.
        // Error handling for a null result handled here with Aura exception thrown warning no task information record exists. 
        
        List<OW_task_information__c> taskinfos = new List<OW_task_information__c>();
        if( t.OW_task_information_identifier__c != null){
            taskInfos = [SELECT Id, Name, OW_assigned_to__c, OW_due_date__c, LastModifiedBy.Name, LastModifiedDate, OW_process_variant__c, OW_requires_4eye__c, OW_stage__c, OW_status__c, OW_task_description__c, OW_triggered_by__c, OW_triggers__c FROM OW_task_information__c WHERE Id =: t.OW_task_information_identifier__c LIMIT 1];
        } else {
            taskInfos = [SELECT Id, Name, OW_assigned_to__c, OW_due_date__c, LastModifiedBy.Name, LastModifiedDate, OW_process_variant__c, OW_requires_4eye__c, OW_stage__c, OW_status__c, OW_task_description__c, OW_triggered_by__c, OW_triggers__c FROM OW_task_information__c WHERE OW_record_type_developer_name__c =: t.RecordType.DeveloperName LIMIT 1];
        }
        //        if(!taskInfos.isEmpty()){
        return taskInfos[0];
        //      }
        //        else{
        //         throw new AuraHandledException('No task information found. Please set a record up for this record type.');
        //     }
    }
}