force-app/main/default/objects/OW_task_information__c/OW_task_information__c.object-meta.xml
<CustomObject>
    <description>This object stores reference data related to tasks carried out by people across Octopus Wealth. In addition to a description of how to perform the task, there is useful information stored like which team performs it, whether the task is active, and which part of the process it falls under.</description>
    <label>Task Information</label>
    <nameField>
        <label>Task Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_task_information__c/fields/OW_assigned_to__c.field-meta.xml
<CustomField>
    <fullName>OW_assigned_to__c</fullName>
    <description>The team that this task is normally completed by.</description>
    <label>Assigned To</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Case owner</fullName>
            </value>
            <value>
                <fullName>Chosen user</fullName>
            </value>
            <value>
                <fullName>Dedicated specialist/household team</fullName>
            </value>
            <value>
                <fullName>Household team</fullName>
            </value>
            <value>
                <fullName>Opportunity owner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Specific user</fullName>
            </value>
            <value>
                <fullName>Suitability planner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_due_date_offset__c.field-meta.xml
<CustomField>
    <fullName>OW_due_date_offset__c</fullName>
    <description>The number of business days after the task creation date that tasks created from this template will be due.</description>
    <inlineHelpText>How many business days after creation should this task be due? Use 0 for same day, 1 for next day etc.</inlineHelpText>
    <label>Due date offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_priority__c.field-meta.xml
<CustomField>
    <fullName>OW_priority__c</fullName>
    <description>The priority of the task created from this template.</description>
    <inlineHelpText>What priority do you want to be set for any tasks of this type?</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_process_variant__c.field-meta.xml
<CustomField>
    <fullName>OW_process_variant__c</fullName>
    <description>Describes whether this task is part of an old or new process (eg old factfind or new profile).</description>
    <label>Process Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Legacy Wealth Management</fullName>
            </value>
            <value>
                <fullName>Current Wealth Management Process</fullName>
            </value>
            <value>
                <fullName>New customer</fullName>
            </value>
            <value>
                <fullName>Annual review</fullName>
            </value>
            <value>
                <fullName>Tax year end</fullName>
            </value>
            <value>
                <fullName>Follow on advice</fullName>
            </value>
            <value>
                <fullName>Nurture lead</fullName>
            </value>
            <value>
                <fullName>Manage opportunity</fullName>
            </value>
            <value>
                <fullName>Manage application</fullName>
            </value>
            <value>
                <fullName>Employee onboarding</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder Turning 18</fullName>
            </value>
            <value>
                <fullName>Customer support</fullName>
            </value>
            <value>
                <fullName>Protection advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_record_type_developer_name__c.field-meta.xml
<CustomField>
    <fullName>OW_record_type_developer_name__c</fullName>
    <description>This field holds the developer name of the task record type. This is the unique reference used to identify to which task record type this information relates.</description>
    <inlineHelpText>This is a unique reference to the record type. This MUST NOT be changed without understanding the implications or it will stop task information from displaying when viewing tasks.</inlineHelpText>
    <label>Record type developer name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_specific_user__c.field-meta.xml
<CustomField>
    <fullName>OW_specific_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field in which a specific user can be identified for a given task information record.</description>
    <label>Specific user</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>User must be active.</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Task_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_stage__c.field-meta.xml
<CustomField>
    <fullName>OW_stage__c</fullName>
    <description>The stage of the advice process that this task falls under.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_process_variant__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Nurturing</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Data Gathering</fullName>
            </value>
            <value>
                <fullName>Suitability</fullName>
            </value>
            <value>
                <fullName>Fulfilment</fullName>
            </value>
            <value>
                <fullName>Annual Review</fullName>
            </value>
            <value>
                <fullName>Unactioned</fullName>
            </value>
            <value>
                <fullName>Gather information</fullName>
            </value>
            <value>
                <fullName>Broker mortgage</fullName>
            </value>
            <value>
                <fullName>Await completion</fullName>
            </value>
            <value>
                <fullName>Mortgage complete</fullName>
            </value>
            <value>
                <fullName>Applying for DIP</fullName>
            </value>
            <value>
                <fullName>DIP granted</fullName>
            </value>
            <value>
                <fullName>Agree product</fullName>
            </value>
            <value>
                <fullName>Provide advice</fullName>
            </value>
            <value>
                <fullName>Applying for mortgage</fullName>
            </value>
            <value>
                <fullName>Mortgage offered</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_status__c.field-meta.xml
<CustomField>
    <fullName>OW_status__c</fullName>
    <description>The status of the task description itself.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Out of date</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_subject__c.field-meta.xml
<CustomField>
    <fullName>OW_subject__c</fullName>
    <description>The subject of the task created from this template.</description>
    <inlineHelpText>What subject do you want to be set for any tasks of this type?</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_task_credit__c.field-meta.xml
<CustomField>
    <fullName>OW_task_credit__c</fullName>
    <description>Credit depending on how much time and effort the task takes</description>
    <label>Task credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_type__c.field-meta.xml
<CustomField>
    <fullName>OW_task_type__c</fullName>
    <description>A code that will identify the type of task this task information record represents.</description>
    <label>Task type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_team__c.field-meta.xml
<CustomField>
    <fullName>OW_team__c</fullName>
    <description>Used to capture the team that looks after this task.</description>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business operations</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Mortgages</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Planners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_turnaround_time__c.field-meta.xml
<CustomField>
    <fullName>OW_turnaround_time__c</fullName>
    <description>The number of business days prior to the task due date that the target start date will be set for any tasks created using this template.</description>
    <inlineHelpText>How many business days before the task due date should the target start date be set? Use 0 to have the target start date equal the due date, 1 for it to be the business day before etc.</inlineHelpText>
    <label>Turnaround time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OW_task_request__c/OW_task_request__c.object-meta.xml
<CustomObject>
    <description>Used to generate tasks requested by external software</description>
    <label>Task Request</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Task Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_task_request__c/fields/OW_due_date_input__c.field-meta.xml
<CustomField>
    <fullName>OW_due_date_input__c</fullName>
    <label>Due date input</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_household_id__c.field-meta.xml
<CustomField>
    <fullName>OW_household_id__c</fullName>
    <label>Household ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_task_type__c.field-meta.xml
<CustomField>
    <fullName>OW_task_type__c</fullName>
    <label>Task type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_request__c/fields/OW_what_id__c.field-meta.xml
<CustomField>
    <fullName>OW_what_id__c</fullName>
    <label>What ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <description>Record type for all call logging</description>
    <label>Call</label>
</RecordType>

unpackaged/main/default/objects/Task/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>false</active>
    <label>zDel Test</label>
</RecordType>

force-app/main/default/classes/TaskRequestHelperTest.cls
@isTest
private class TaskRequestHelperTest {

    @TestSetup
    static void makeData(){
        OW_task_information__c taskInfo = new OW_Task_Information__c();
        taskInfo.Name = 'Test';
        taskInfo.OW_record_type_developer_name__c = TaskRequestHelper.TASK_REQUEST_DEFAULT_TASK_INFORMATION_DEVELOPER_NAME; 
        taskInfo.OW_task_type__c = TaskRequestHelper.TASK_REQUEST_DEFAULT_TASK_INFORMATION_DEVELOPER_NAME;
        taskInfo.OW_status__c = taskEngine.TASK_TYPE_STATUS_ACTIVE;
        taskInfo.OW_subject__c = 'Test';
        taskInfo.OW_task_credit__c = 1;
        taskInfo.OW_due_date_offset__c = 1;
        taskInfo.OW_turnaround_time__c = 3;
        taskInfo.OW_priority__c = 'Medium';
        taskInfo.OW_process_variant__c = 'Protection advice';
        taskInfo.OW_stage__c = 'N/A';
        taskInfo.OW_team__c = 'Business operations';
        taskInfo.OW_assigned_to__c = TaskEngine.ASSIGNED_TO_SPECIFIC_USER;
        taskInfo.OW_specific_user__c = UserInfo.getUserId();

        insert taskInfo;
    }

    /**
     * @description Tests the successful creation of multiple Task records from a list of requests.
     */
    @isTest
    static void testGenerateRequests_CreatesTasksSuccessfully() {
        // --- Arrange ---
        // Create a related Account and Contact to use for WhatId and WhoId
        List<Account> testHousehold = TestDataFactory.createHousehold(1, 0, 'test');

        
        // Create a list of test records to be processed
        List<OW_task_request__c> testRequests = new List<OW_task_request__c>();
        for(Integer i = 0; i < 3; i++) {
            testRequests.add(new OW_task_request__c(
                OW_due_date_input__c = Date.today().addDays(i),
                OW_what_id__c = testHousehold[0].Id,
                OW_household_id__c = testHousehold[0].Id
            ));
        }


        Test.startTest();
        insert testRequests;
        Test.stopTest();

        List<Task> createdTasks = [SELECT Id, Type, ActivityDate, WhatId, WhoId FROM Task];
        
        // Verify that the correct number of tasks were created
        System.assertEquals(3, createdTasks.size(), 'Should have created 3 Task records.');

        // Verify that the data was mapped correctly onto the new Task
        // We'll check the first task as a representative sample
        System.assertEquals(Date.today(), createdTasks[0].ActivityDate, 'Due Date should be mapped correctly.');
        System.assertEquals(testHousehold[0].Id, createdTasks[0].WhatId, 'WhatId should be mapped to the Account.');
    }

    /**
     * @description Tests that a null task type is replaced with the default developer name.
     */
    @isTest
    static void testGenerateRequests_AppliesDefaultTaskType() {

        // --- Arrange ---
        List<Account> testHousehold = TestDataFactory.createHousehold(1, 0, 'test');
        // Create a request with a null task type
        OW_task_request__c testRequest = new OW_task_request__c(
            OW_due_date_input__c = Date.today().addDays(5),
            OW_what_id__c = testHousehold[0].Id,
            OW_household_id__c = testHousehold[0].Id
        );
        

        // --- Act ---
        Test.startTest();
        insert testRequest;
        Test.stopTest();

        // --- Assert ---
        // Find the created task
        List<Task> createdTasks = [SELECT Id, OW_task_information_name__c FROM Task];
        
        System.assertEquals(1, createdTasks.size(), 'Should have created one Task.');
        
        // Verify that the Task's Type field was set to the default constant
        System.assertEquals(
            TaskRequestHelper.TASK_REQUEST_DEFAULT_TASK_INFORMATION_DEVELOPER_NAME, 
            createdTasks[0].OW_task_information_name__c,
            'Task Type should be set to the default value when the source is null.'
        );
    }

    /**
     * @description Tests that the method handles null or empty lists gracefully without creating tasks.
     */
    @isTest
    static void testGenerateRequests_HandlesEmptyAndNullLists() {
        // --- Arrange ---
        // No data is needed for this test.

        // --- Act ---
        Test.startTest();
        // Call with an empty list
        TaskRequestHelper.generateRequestsFromTaskRequestRecords(new List<OW_task_request__c>());
        // Call with a null list
        TaskRequestHelper.generateRequestsFromTaskRequestRecords(null);
        Test.stopTest();

        // --- Assert ---
        // Verify that no Task records were created
        List<Task> tasks = [SELECT Id FROM Task];
        System.assertEquals(0, tasks.size(), 'TaskEngine should not be called, and no tasks should be created.');
    }
}