force-app/main/default/objects/OW_task_information__c/OW_task_information__c.object-meta.xml
<CustomObject>
    <description>This object stores reference data related to tasks carried out by people across Octopus Wealth. In addition to a description of how to perform the task, there is useful information stored like which team performs it, whether the task is active, and which part of the process it falls under.</description>
    <label>Task Information</label>
    <nameField>
        <label>Task Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_task_information__c/fields/OW_assigned_to__c.field-meta.xml
<CustomField>
    <fullName>OW_assigned_to__c</fullName>
    <description>The team that this task is normally completed by.</description>
    <label>Assigned To</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Case owner</fullName>
            </value>
            <value>
                <fullName>Chosen user</fullName>
            </value>
            <value>
                <fullName>Dedicated specialist/household team</fullName>
            </value>
            <value>
                <fullName>Household team</fullName>
            </value>
            <value>
                <fullName>Opportunity owner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Specific user</fullName>
            </value>
            <value>
                <fullName>Suitability planner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_due_date_offset__c.field-meta.xml
<CustomField>
    <fullName>OW_due_date_offset__c</fullName>
    <description>The number of business days after the task creation date that tasks created from this template will be due.</description>
    <inlineHelpText>How many business days after creation should this task be due? Use 0 for same day, 1 for next day etc.</inlineHelpText>
    <label>Due date offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_priority__c.field-meta.xml
<CustomField>
    <fullName>OW_priority__c</fullName>
    <description>The priority of the task created from this template.</description>
    <inlineHelpText>What priority do you want to be set for any tasks of this type?</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_process_variant__c.field-meta.xml
<CustomField>
    <fullName>OW_process_variant__c</fullName>
    <description>Describes whether this task is part of an old or new process (eg old factfind or new profile).</description>
    <label>Process Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Legacy Wealth Management</fullName>
            </value>
            <value>
                <fullName>Current Wealth Management Process</fullName>
            </value>
            <value>
                <fullName>New customer</fullName>
            </value>
            <value>
                <fullName>Annual review</fullName>
            </value>
            <value>
                <fullName>Tax year end</fullName>
            </value>
            <value>
                <fullName>Follow on advice</fullName>
            </value>
            <value>
                <fullName>Nurture lead</fullName>
            </value>
            <value>
                <fullName>Manage opportunity</fullName>
            </value>
            <value>
                <fullName>Manage application</fullName>
            </value>
            <value>
                <fullName>Employee onboarding</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder Turning 18</fullName>
            </value>
            <value>
                <fullName>Customer support</fullName>
            </value>
            <value>
                <fullName>Protection advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_queue__c.field-meta.xml
<CustomField>
    <fullName>OW_queue__c</fullName>
    <description>The queue to which tasks of this type should be assigned.</description>
    <label>Queue</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>OW_queues</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_record_type_developer_name__c.field-meta.xml
<CustomField>
    <fullName>OW_record_type_developer_name__c</fullName>
    <description>This field holds the developer name of the task record type. This is the unique reference used to identify to which task record type this information relates.</description>
    <inlineHelpText>This is a unique reference to the record type. This MUST NOT be changed without understanding the implications or it will stop task information from displaying when viewing tasks.</inlineHelpText>
    <label>Record type developer name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_stage__c.field-meta.xml
<CustomField>
    <fullName>OW_stage__c</fullName>
    <description>The stage of the advice process that this task falls under.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_process_variant__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Nurturing</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Data Gathering</fullName>
            </value>
            <value>
                <fullName>Suitability</fullName>
            </value>
            <value>
                <fullName>Fulfilment</fullName>
            </value>
            <value>
                <fullName>Annual Review</fullName>
            </value>
            <value>
                <fullName>Unactioned</fullName>
            </value>
            <value>
                <fullName>Gather information</fullName>
            </value>
            <value>
                <fullName>Broker mortgage</fullName>
            </value>
            <value>
                <fullName>Await completion</fullName>
            </value>
            <value>
                <fullName>Mortgage complete</fullName>
            </value>
            <value>
                <fullName>Applying for DIP</fullName>
            </value>
            <value>
                <fullName>DIP granted</fullName>
            </value>
            <value>
                <fullName>Agree product</fullName>
            </value>
            <value>
                <fullName>Provide advice</fullName>
            </value>
            <value>
                <fullName>Applying for mortgage</fullName>
            </value>
            <value>
                <fullName>Mortgage offered</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_status__c.field-meta.xml
<CustomField>
    <fullName>OW_status__c</fullName>
    <description>The status of the task description itself.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Out of date</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_subject__c.field-meta.xml
<CustomField>
    <fullName>OW_subject__c</fullName>
    <description>The subject of the task created from this template.</description>
    <inlineHelpText>What subject do you want to be set for any tasks of this type?</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_description_google_doc_link__c.field-meta.xml
<CustomField>
    <fullName>OW_task_description_google_doc_link__c</fullName>
    <description>Stores the link to the Google Doc where the task description is mastered.</description>
    <label>Task description Google Doc link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_type__c.field-meta.xml
<CustomField>
    <fullName>OW_task_type__c</fullName>
    <description>A code that will identify the type of task this task information record represents.</description>
    <label>Task type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_team__c.field-meta.xml
<CustomField>
    <fullName>OW_team__c</fullName>
    <description>Used to capture the team that looks after this task.</description>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business operations</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Mortgages</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Planners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_turnaround_time__c.field-meta.xml
<CustomField>
    <fullName>OW_turnaround_time__c</fullName>
    <description>The number of business days prior to the task due date that the target start date will be set for any tasks created using this template.</description>
    <inlineHelpText>How many business days before the task due date should the target start date be set? Use 0 to have the target start date equal the due date, 1 for it to be the business day before etc.</inlineHelpText>
    <label>Turnaround time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>false</active>
    <label>zDel Test</label>
</RecordType>

force-app/main/default/classes/DataFactoryTaskInformation.cls
/**
* This class generates task information records to assist in generating realistic but fake data in sandbox seeding and anonymisation.
* It should be used in the data factory and sandbox classes primarily and is not intended for any production use case. 
*/
public class DataFactoryTaskInformation {
    
    public OW_task_information__c generateTaskInformation(String taskType){
        if(String.isBlank(taskType)){
            taskType = 'RANDOM_TASK_TYPE_VALUE';
        }
        OW_task_information__c taskInformation = new OW_task_information__c(
        	OW_task_type__c = taskType,
            OW_record_type_developer_name__c = taskType,
            OW_task_description_google_doc_link__c = 'https://google.com',
            OW_status__c = 'Active',
            OW_team__c = 'Planners',
            OW_assigned_to__c = 'Queue',
            OW_due_date_offset__c = 0,
            OW_turnaround_time__c = 0,
            OW_priority__c = 'High',
            OW_process_variant__c = 'New customer',
            OW_stage__c = 'Discovery',
            OW_queue__c = 'OW_planners',
            OW_subject__c = 'test'
        );
        insert taskInformation;
        return taskInformation;
    }
}