force-app/main/default/objects/FinancialProduct__c/FinancialProduct__c.object-meta.xml
<CustomObject>
    <label>Financial Product</label>
    <nameField>
        <displayFormat>FP-{000000}</displayFormat>
        <label>Financial product name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FinancialProduct__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Record the status of the financial product</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegularTransaction__c/RegularTransaction__c.object-meta.xml
<CustomObject>
    <label>Regular Transaction</label>
    <nameField>
        <displayFormat>RT-{00000}</displayFormat>
        <label>Regular Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regular Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegularTransaction__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TransactionDirection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegularTransaction__c/fields/FinancialProduct__c.field-meta.xml
<CustomField>
    <fullName>FinancialProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Financial Product</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>RegularTransactions</relationshipLabel>
    <relationshipName>RegularTransactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegularTransaction__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegularTransaction__c/fields/NextTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>NextTransactionDate__c</fullName>
    <label>Next Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegularTransaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TransactionDirection.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONTRIBUTION</fullName>
        <label>Contribution</label>
    </customValue>
    <customValue>
        <fullName>WITHDRAWL</fullName>
        <label>Withdrawl</label>
    </customValue>
    <masterLabel>Transaction Direction</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RegularTransactionRequest.cls
public class RegularTransactionRequest {
    
    @AuraEnabled public Id id;
    @AuraEnabled public Id productId;
    @AuraEnabled public Decimal amount;
    @AuraEnabled public String direction;
    @AuraEnabled public String transactionType;
    @AuraEnabled public String frequency;
    @AuraEnabled public Date nextTransactionDate;
    @AuraEnabled public Date startDate;
    @AuraEnabled public Date endDate;
    @AuraEnabled public string status;

    @AuraEnabled public Boolean isError;
    @AuraEnabled public String errorMessage = '';

    @AuraEnabled public RegularTransaction__c regularTransactionRecord;

    public void setError(string errorMessage) {
        this.isError = true;
        this.errorMessage += errorMessage;
    }
    
    public void validate() {
        this.isError = false;
        this.errorMessage = '';

        //todo extend validation

        if(this.productId == null) {
            this.setError('Product not specified. ');
        }

        if(this.amount == null){
            this.setError('Amount not specified. ');
        }

        if(this.direction == null) {
            this.setError('Direction not specified. ');
        } else if(!ExpectationHelper.DIRECTION_VALUES.contains(this.direction)) {
            this.setError('Direction value not valid. ');
        }

        if(this.status == null) {
            this.setError('Status not specified. ');
        }

        /*
        if(this.transactionType == null){
            this.setError('Transaction type not specified. ');
        } else if(!ExpectationHelper.TRANSACTION_TYPE_VALUES.contains(this.transactionType)){
            this.setError('Transaction type value not valid. ');
        }*/
    }

    public void convertToRecord(){

        if(this.regularTransactionRecord == null) {
            this.regularTransactionRecord = new RegularTransaction__c();
        }

        this.regularTransactionRecord.Id = this.id;
        this.regularTransactionRecord.FinancialProduct__c = this.productId;
        this.regularTransactionRecord.Amount__c = this.amount;
        this.regularTransactionRecord.Direction__c = this.direction;
        //this.regularTransactionRecord.Type__c = this.transactionType;
        this.regularTransactionRecord.Frequency__c = this.frequency;
        this.regularTransactionRecord.NextTransactionDate__c = this.nextTransactionDate;
        this.regularTransactionRecord.StartDate__c = this.startDate;
        this.regularTransactionRecord.EndDate__c = this.endDate;
        this.regularTransactionRecord.Status__c = this.status;
    }

    public void convertRecordToRequest(){

        this.id = this.regularTransactionRecord.Id;
        this.productId = this.regularTransactionRecord.FinancialProduct__c;
        this.amount = this.regularTransactionRecord.Amount__c;
        this.direction = this.regularTransactionRecord.Direction__c;
        this.frequency = this.regularTransactionRecord.Frequency__c;
        this.nextTransactionDate = this.regularTransactionRecord.NextTransactionDate__c;
        this.startDate = this.regularTransactionRecord.StartDate__c;
        this.endDate = this.regularTransactionRecord.EndDate__c;
        this.status = this.regularTransactionRecord.Status__c;
    }
}