force-app/main/default/objects/OW_task_request__c/OW_task_request__c.object-meta.xml
<CustomObject>
    <description>Used to generate tasks requested by external software</description>
    <label>Task Request</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Task Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_task_request__c/fields/OW_due_date_input__c.field-meta.xml
<CustomField>
    <fullName>OW_due_date_input__c</fullName>
    <label>Due date input</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_household_id__c.field-meta.xml
<CustomField>
    <fullName>OW_household_id__c</fullName>
    <label>Household ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_related_advice__c.field-meta.xml
<CustomField>
    <fullName>OW_related_advice__c</fullName>
    <description>related advice id</description>
    <label>Related advice</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_request__c/fields/OW_related_aml__c.field-meta.xml
<CustomField>
    <fullName>OW_related_aml__c</fullName>
    <description>related AML &amp; KYC check id</description>
    <label>Related AML</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_request__c/fields/OW_related_annual_review__c.field-meta.xml
<CustomField>
    <fullName>OW_related_annual_review__c</fullName>
    <description>Related annual review ID</description>
    <label>Related annual review</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_related_loa__c.field-meta.xml
<CustomField>
    <fullName>OW_related_loa__c</fullName>
    <description>ID of related LOA record</description>
    <label>Related LOA</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_related_mortgage_application__c.field-meta.xml
<CustomField>
    <fullName>OW_related_mortgage_application__c</fullName>
    <description>ID of related mortgage application.</description>
    <label>Related mortgage application</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_related_opportunity__c.field-meta.xml
<CustomField>
    <fullName>OW_related_opportunity__c</fullName>
    <description>ID of related opportunity</description>
    <label>Related opportunity</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_related_provider__c.field-meta.xml
<CustomField>
    <fullName>OW_related_provider__c</fullName>
    <description>ID of related provider</description>
    <label>Related provider</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_target_start_date__c.field-meta.xml
<CustomField>
    <fullName>OW_target_start_date__c</fullName>
    <label>Target start date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_task_id__c.field-meta.xml
<CustomField>
    <fullName>OW_task_id__c</fullName>
    <label>Task ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_request__c/fields/OW_task_type__c.field-meta.xml
<CustomField>
    <fullName>OW_task_type__c</fullName>
    <label>Task type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_request__c/fields/OW_what_id__c.field-meta.xml
<CustomField>
    <fullName>OW_what_id__c</fullName>
    <label>What ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_request__c/fields/OW_who_id__c.field-meta.xml
<CustomField>
    <fullName>OW_who_id__c</fullName>
    <label>Who ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaskRequestHelper.cls
public class TaskRequestHelper {

    public static final string TASK_REQUEST_DEFAULT_TASK_INFORMATION_DEVELOPER_NAME = 'DEFAULT_TASK_REQUEST';

    public static void generateRequestsFromTaskRequestRecords(List<OW_task_request__c> newRequests) {

        if (newRequests == null || newRequests.isEmpty()) {
            return;
        }

        List<TaskEngineRequest> taskEngineRequests = new List<TaskEngineRequest>();

        for (OW_task_request__c request : newRequests) {
            TaskEngineRequest engineRequest = new TaskEngineRequest();

            engineRequest.dueDateInput              = request.OW_due_date_input__c;
            engineRequest.householdId               = request.OW_household_id__c;
            engineRequest.originalTask              = request.OW_task_id__c;
            engineRequest.relatedAdviceId           = request.OW_related_advice__c;
            engineRequest.relatedAmlKycId           = request.OW_related_aml__c;
            engineRequest.relatedAnnualReview       = request.OW_related_annual_review__c;
            engineRequest.relatedLoa                = request.OW_related_loa__c;
            engineRequest.relatedMortgageApplication= request.OW_related_mortgage_application__c;
            engineRequest.relatedOpportunity        = request.OW_related_opportunity__c;
            engineRequest.relatedProvider           = request.OW_related_provider__c;
            engineRequest.targetStartDateInput      = request.OW_target_start_date__c;
            engineRequest.taskType                  = request.OW_task_type__c;
            engineRequest.whatId                    = request.OW_what_id__c;
            engineRequest.whoId                     = request.OW_who_id__c;

            if (request.OW_task_type__c == null) {
                engineRequest.taskType = TASK_REQUEST_DEFAULT_TASK_INFORMATION_DEVELOPER_NAME;
            }

            // Fields with NO source on OW_task_request__c will be null by default:
            // engineRequest.chosenUser
            // engineRequest.relatedFee
            // engineRequest.relatedFulfilment
            // engineRequest.relatedInformationRequest
            // engineRequest.subject
            // engineRequest.taskId    

            taskEngineRequests.add(engineRequest);
        }

        if (!taskEngineRequests.isEmpty()) {
            try {
                TaskEngine.generateTasks(taskEngineRequests);
                if(TaskEngine.taskErrors.size() > 0) {
                    throw new TaskRequestHelperException(JSON.serialize(TaskEngine.taskErrors));
                }
            } catch (Exception e) {
                System.debug('An error occurred calling TaskEngine.generateTasks: ' + e.getMessage());
                newRequests[0].addError('Failed to generate tasks. Error: ' + e.getMessage());
                //todo - add to nebula logger
            }
        }
    }

    public class TaskRequestHelperException extends Exception {}
}