unpackaged/main/default/objects/Account/fields/OW_admin_notes__c.field-meta.xml
<CustomField>
    <fullName>OW_admin_notes__c</fullName>
    <description>For storage of temporary messages while managing data migration etc to assist with tracking.</description>
    <label>Admin notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Advice_Status__c.field-meta.xml
<CustomField>
    <fullName>Advice_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
                <default>true</default>
                <label>Setup</label>
            </value>
            <value>
                <fullName>Data gathering</fullName>
            </value>
            <value>
                <fullName>Risk Call</fullName>
            </value>
            <value>
                <fullName>Ready for suitability</fullName>
            </value>
            <value>
                <fullName>Suitability in progress</fullName>
            </value>
            <value>
                <fullName>Prepare advice</fullName>
            </value>
            <value>
                <fullName>Present advice</fullName>
            </value>
            <value>
                <fullName>Deck complete</fullName>
            </value>
            <value>
                <fullName>Await decision</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>In fulfilment</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Suitability Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Meeting held</fullName>
                <isActive>false</isActive>
                <label>Meeting held</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Fact_find_requirements__c.field-meta.xml
<CustomField>
    <fullName>Fact_find_requirements__c</fullName>
    <label>Fact find requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update required</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/G_Drive_Advice_Folder__c.field-meta.xml
<CustomField>
    <fullName>G_Drive_Advice_Folder__c</fullName>
    <label>G-Drive Advice Folder</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/New_LOAs_required__c.field-meta.xml
<CustomField>
    <fullName>New_LOAs_required__c</fullName>
    <inlineHelpText>This will start a workflow to create and send out new LOAs</inlineHelpText>
    <label>Additional LOAs required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/New_or_existing_client__c.field-meta.xml
<CustomField>
    <fullName>New_or_existing_client__c</fullName>
    <label>New or Existing client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Update_valuations__c.field-meta.xml
<CustomField>
    <fullName>Update_valuations__c</fullName>
    <inlineHelpText>Yes - will create a task for a specialist to update valuations for related financial products</inlineHelpText>
    <label>Update valuations</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/recordTypes/Advice_RT_General_Advice.recordType-meta.xml
<RecordType>
    <fullName>Advice_RT_General_Advice</fullName>
    <active>true</active>
    <description>RT for general advice, this will be broken into many</description>
    <label>General Advice</label>
</RecordType>

force-app/main/default/objects/EmailConfiguration__c/EmailConfiguration__c.object-meta.xml
<CustomObject>
    <description>Holds the details of emails that is used to drive automation and business validation.</description>
    <label>Email Configuration</label>
    <nameField>
        <label>Email Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EmailConfiguration__c/fields/ClientsAddressed__c.field-meta.xml
<CustomField>
    <fullName>ClientsAddressed__c</fullName>
    <label>Clients Addressed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>One only</fullName>
            </value>
            <value>
                <fullName>User defined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/CustomPermission__c.field-meta.xml
<CustomField>
    <fullName>CustomPermission__c</fullName>
    <description>If this field has a value, a user must have this custom permission order to send an email of this type</description>
    <inlineHelpText>If this field has a value, a user must have this custom permission order to send an email of this type</inlineHelpText>
    <label>Custom permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the email template</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name of the email template this email configuration is associated with.</description>
    <externalId>true</externalId>
    <inlineHelpText>Must match the developer name of the email template.</inlineHelpText>
    <label>Developer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <description>The email address this email message must come from.</description>
    <label>From</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Necessity__c.field-meta.xml
<CustomField>
    <fullName>Necessity__c</fullName>
    <label>Necessity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/PartnerCopied__c.field-meta.xml
<CustomField>
    <fullName>PartnerCopied__c</fullName>
    <description>Indicates if partner should be copied into an email of this type</description>
    <label>Partner copied</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always</fullName>
            </value>
            <value>
                <fullName>Never</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The subject that should be used in this email</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EmailConfiguration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>false</active>
    <label>zDel Test</label>
</RecordType>

unpackaged/main/default/classes/sendTemplatedEmailTest.cls
@isTest
public class sendTemplatedEmailTest {
    
    @testSetup
    static void setup() {

        // set up user and permissions
        User currentUser = [ SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        PermissionSet ps = new PermissionSet(
            Name = 'Test', 
            Label = 'Test'
        );
        System.runAs ( currentUser ) {
            insert ps;
        }
        CustomPermission cp = [SELECT Id, DeveloperName FROM CustomPermission WHERE IsLicensed = false AND IsProtected = false AND NamespacePrefix = null LIMIT 1];
        SetupEntityAccess sea = new SetupEntityAccess(
            ParentId = ps.Id, 
            SetupEntityId = cp.Id
        );
        System.runAs ( currentUser ) {
            insert sea;
        }
        
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = currentUser.Id,
            PermissionSetId = ps.Id
        );
        System.runAs ( currentUser ) {
            insert psa;
        }

        // Create email templates and email configuration records
        OrgWideEmailAddress fromEmail = [SELECT Id, Address FROM OrgWideEmailAddress ORDER BY Address ASC LIMIT 1];
        List<EmailTemplate> testEmailTemplates = new List<EmailTemplate>();
        List<EmailConfiguration__c> emailConfigRecords = new List<EmailConfiguration__c>();
        List<Account> accs = new List<Account>();
        testEmailTemplates.add(new EmailTemplate(
            isActive = true, 
            Name = 'STARTER_EMAIL', 
            DeveloperName = 'STARTER_EMAIL', 
            TemplateType = 'text', 
            FolderId = UserInfo.getUserId() // fix this line, not right
        )); 
        emailConfigRecords.add(new EmailConfiguration__c(
            Name = 'STARTER_EMAIL', 
            DeveloperName__c = 'STARTER_EMAIL',
            ClientsAddressed__c = 'All', 
            CustomPermission__c = cp.DeveloperName,
            Description__c = 'Test',
            From__c = fromEmail.Address,
            PartnerCopied__c = 'Always',
            Type__c = 'Service',
            Necessity__c = 'Required'
        ));
        String identifier = 'EmailMessageHelperTestHousehold';
        DataFactoryAccountHousehold dfah = new DataFactoryAccountHousehold();
        Account household = dfah.createHousehold(identifier, 1, 0, 'Active', 'Full');
        String ADVICE_RECORD_TYPE_DEVELOPER_NAME = 'Advice_RT_General_Advice';
        Advice__c advice = new Advice__c(
            Advice_Household__c = household.Id,
            RecordTypeId = Schema.SObjectType.Advice__c.getRecordTypeInfosByDeveloperName().get(ADVICE_RECORD_TYPE_DEVELOPER_NAME).getRecordTypeId(),
            New_or_existing_client__c = 'Existing',
            Partner__c = currentUser.Id,
            Fact_find_requirements__c = 'Not required',
            G_Drive_Advice_Folder__c = 'google.com',
            Update_valuations__c = 'No',
            New_LOAs_required__c = 'No', 
            Advice_Status__c = 'Data Gathering',
            Subject__c = identifier,
            Name = identifier
        );
            
        System.runAs ( currentUser ) {
			insert advice;
            insert testEmailTemplates;
            insert emailConfigRecords;
        }
    }
    
    @istest
    static void sendEmail_templateMissing_Blocked(){
        Account person = [SELECT Id, PersonEmail, PersonContactId FROM Account WHERE IsPersonAccount = true];
        Account acc = [SELECT Id FROM Account WHERE OW_admin_notes__c = 'EmailMessageHelperTestHousehold'];
        Advice__c adv = [SELECT Id FROM Advice__c WHERE Name = 'EmailMessageHelperTestHousehold'];
        OrgWideEmailAddress fromEmail = [SELECT Id, Address FROM OrgWideEmailAddress ORDER BY Address ASC LIMIT 1];
        List<String> toEmails = new List<String>{person.PersonEmail};
        List<String> ccEmails = new List<String>{UserInfo.getUserEmail()};
                
        Test.startTest();
        sendTemplatedEmail.sendTemplatedEmail(toEmails, ccEmails, 'NOT_REAL_TEMPLATE', person.PersonContactId, adv.Id, fromEmail.Id, true);    
        Integer emailsSent = Limits.getEmailInvocations();
        List<Task> task = [SELECT Id FROM Task WHERE WhatID =: adv.Id AND AccountId =: acc.Id AND WhoId =: person.PersonContactId];
        Test.stopTest();
        
        System.assertEquals(0, emailsSent);
        System.assertEquals(0, task.size());
    }
    
    @istest
    static void sendEmail_direct_allowed(){
        Account person = [SELECT Id, PersonEmail, PersonContactId FROM Account WHERE IsPersonAccount = true];
        Account acc = [SELECT Id FROM Account WHERE OW_admin_notes__c = 'EmailMessageHelperTestHousehold'];
        Advice__c adv = [SELECT Id FROM Advice__c WHERE Name = 'EmailMessageHelperTestHousehold'];
        OrgWideEmailAddress fromEmail = [SELECT Id, Address FROM OrgWideEmailAddress ORDER BY Address ASC LIMIT 1];
        List<String> toEmails = new List<String>{person.PersonEmail};
        List<String> ccEmails = new List<String>{UserInfo.getUserEmail()};
        
        Test.startTest();
        sendTemplatedEmail.sendTemplatedEmail(toEmails, ccEmails, 'STARTER_EMAIL', person.PersonContactId, adv.Id, fromEmail.Id, true);
        Integer emailsSent = Limits.getEmailInvocations();
        List<Task> task = [SELECT Id FROM Task WHERE WhatID =: adv.Id AND AccountId =: acc.Id AND WhoId =: person.PersonContactId];
        Test.stopTest();
        
        System.assertEquals(1, emailsSent, 'Expected 1 email but not true');
        System.assertEquals(1, task.size(), 'Exepcted 1 task but none/more found');
    }
    
    
    
    @isTest
    static void sendEmail_invocable_allowed() {
        Account person = [SELECT Id, PersonEmail, PersonContactId FROM Account WHERE IsPersonAccount = true];
		Account acc = [SELECT Id FROM Account WHERE OW_admin_notes__c = 'EmailMessageHelperTestHousehold'];
        Advice__c adv = [SELECT Id FROM Advice__c WHERE Name = 'EmailMessageHelperTestHousehold'];
        OrgWideEmailAddress fromEmail = [SELECT Id, Address FROM OrgWideEmailAddress ORDER BY Address ASC LIMIT 1];
        List<String> toEmails = new List<String>{person.PersonEmail};
        List<String> ccEmails = new List<String>{UserInfo.getUserEmail()};

        List<sendTemplatedEmail.FlowInputs> FlowInputs = new List<sendTemplatedEmail.FlowInputs>();
        sendTemplatedEmail.FlowInputs FlowInput = new sendTemplatedEmail.FlowInputs();
        FlowInput.toRecipients = toEmails;
        FlowInput.ccRecipients = ccEmails;
        FlowInput.emailTemplateDevName = 'STARTER_EMAIL';
        FlowInput.targetObjId = person.PersonContactId;
        FlowInput.whatId = adv.Id;
        FlowInput.orgWideEmailId = fromEmail.Id;
		FlowInput.saveAsActivity = true;        
        FlowInputs.add(FlowInput);
        
        Test.startTest();
		sendTemplatedEmail.invokeThisMethod(FlowInputs);
        Integer emailsSent = Limits.getEmailInvocations();
        List<Task> task = [SELECT Id FROM Task WHERE WhatId = :adv.Id AND AccountId = :acc.Id AND WhoId = :person.PersonContactId];
        Test.stopTest();
        System.assertEquals(1, emailsSent,  'Expected 1 email but not true');
        System.assertEquals(1, task.size(), 'Exepcted 1 task but none/more found');
    }
}