unpackaged/main/default/objects/Account/fields/OW_admin_notes__c.field-meta.xml
<CustomField>
    <fullName>OW_admin_notes__c</fullName>
    <description>For storage of temporary messages while managing data migration etc to assist with tracking.</description>
    <label>Admin notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/EmailConfiguration__c.object-meta.xml
<CustomObject>
    <description>Holds the details of emails that is used to drive automation and business validation.</description>
    <label>Email Configuration</label>
    <nameField>
        <label>Email Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailConfiguration__c/fields/AwaitReply__c.field-meta.xml
<CustomField>
    <fullName>AwaitReply__c</fullName>
    <description>Determines whether the related email case should be closed after the related email message using this template is sent. If no reply is expected, the email case is auto closed when the template is sent using the Email Message | Outbound flow. Field was re-labeled for business users to view on Manage email templates page.</description>
    <label>Close after sent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Await a reply</fullName>
            </value>
            <value>
                <fullName>No reply expected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/ClientsAddressed__c.field-meta.xml
<CustomField>
    <fullName>ClientsAddressed__c</fullName>
    <description>Indicates if one or both clients should be included in an email</description>
    <label>Clients addressed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>One only</fullName>
            </value>
            <value>
                <fullName>User defined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name of the email template this email configuration is associated with.</description>
    <externalId>true</externalId>
    <inlineHelpText>Must match the developer name of the email template.</inlineHelpText>
    <label>Developer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <description>The email address this email message must come from.</description>
    <label>From</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Necessity__c.field-meta.xml
<CustomField>
    <fullName>Necessity__c</fullName>
    <label>Necessity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/PartnerCopied__c.field-meta.xml
<CustomField>
    <fullName>PartnerCopied__c</fullName>
    <description>Indicates if partner should be copied into an email of this type</description>
    <label>Partner copied</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always</fullName>
            </value>
            <value>
                <fullName>Never</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/SendingProcess__c.field-meta.xml
<CustomField>
    <fullName>SendingProcess__c</fullName>
    <description>Captures whether this is an automatically or manually set email template.</description>
    <label>Sending process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUTOMATIC</fullName>
                <label>Automatic</label>
            </value>
            <value>
                <fullName>MANUAL</fullName>
                <label>Manual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of email being sent</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailSendTest.cls
@IsTest
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
public class EmailSendTest { 
    @testSetup
    static void setup() {
        if( IS_EMAIL_DELIVERABILITY_ENABLED == true ) {
            DataFactory df = new DataFactory();
            Id household = df.createHousehold('EmailSendTestHousehold', 2, 2, 'Active', 'Full');
            Account acc = [SELECT Id FROM Account WHERE Id =: household];
            acc.OW_admin_notes__c = 'EmailSendTestHousehold';
            update acc;
            
            AccountHouseholdMembers.HouseholdMemberRequest request = new AccountHouseholdMembers.HouseholdMemberRequest();
        	request.householdId = household;
        	request.roles = new Set<String>{'Client','Child'};
        	AccountHouseholdMembers.HouseholdMemberResult result = AccountHouseholdMembers.getHouseholdMembers(request);
        	List<Account> clients = result.memberAccountsByRole.get('Client');
        	List<Account> children = result.memberAccountsByRole.get('Child');
            
            AccountContactRelation targetObject = [SELECT ContactId FROM AccountContactRelation WHERE AccountId =: household LIMIT 1][0];
            
            EmailConfiguration__c emailConfig = new EmailConfiguration__c(
                SendingProcess__c='AUTOMATIC', 
                ClientsAddressed__c='One only', 
                DeveloperName__c='NovaWealthFulfilmentUpdateFinal',
                Necessity__c='Required',
                From__c='team@novawm.com',
                AwaitReply__c='No reply expected',
                PartnerCopied__c='Always',
                Type__c='Service'
            );
            insert emailConfig;
        }
    }

    @isTest
    static void sendEmail_single_success() {
        Account acc = [SELECT Id FROM Account WHERE OW_admin_notes__c = 'EmailSendTestHousehold'];
        Id household = acc.Id;
        AccountContactRelation targetObject = [SELECT ContactId FROM AccountContactRelation WHERE AccountId =: household LIMIT 1][0];
            
        List<EmailSend.EmailSendRequestAutomatic> emailRequests = new List<EmailSend.EmailSendRequestAutomatic>();
        EmailSend.EmailSendRequestAutomatic emailRequest = new EmailSend.EmailSendRequestAutomatic();

        emailRequest.householdId = household;
        emailRequest.whatId = household;
        emailRequest.targetObjectId = targetObject.ContactId;
        emailRequest.saveAsActivity = true;
        emailRequest.subject = 'Test Email';
        emailRequest.parameters = new Map<String, String>{};
        emailRequest.emailTemplateDeveloperName = 'NovaWealthFulfilmentUpdateFinal';            
        emailRequests.add(emailRequest);
        
        Test.startTest();
        EmailSend emailSender = new EmailSend();
        emailSender.sendAutomaticTemplatedEmailCustomSubject(emailRequests);

        Integer emailsSent = Limits.getEmailInvocations();
        System.assertEquals(1, emailsSent, 'Expected 1 email but got ' + emailsSent);
        Test.stopTest();
    }
    
    @isTest
    static void sendEmail_multiple_success() {
        Integer n = 2;    
        Account acc = [SELECT Id FROM Account WHERE OW_admin_notes__c = 'EmailSendTestHousehold'];   
        Id household = acc.Id;
        AccountContactRelation targetObject = [SELECT ContactId FROM AccountContactRelation WHERE AccountId =: household LIMIT 1][0];
        List<EmailSend.EmailSendRequestAutomatic> emailRequests = new List<EmailSend.EmailSendRequestAutomatic>();

        for(Integer i = 0; i < n; i++) {
            EmailSend.EmailSendRequestAutomatic emailRequest = new EmailSend.EmailSendRequestAutomatic();

            emailRequest.householdId = household;
            emailRequest.whatId = household;
            emailRequest.targetObjectId = targetObject.ContactId;
            emailRequest.saveAsActivity = true;
            emailRequest.subject = 'Test Email';
            emailRequest.parameters = new Map<String, String>{};
            emailRequest.emailTemplateDeveloperName = 'NovaWealthFulfilmentUpdateFinal';            
            emailRequests.add(emailRequest);
        }

        Test.startTest();
        EmailSend emailSender = new EmailSend();
        emailSender.sendAutomaticTemplatedEmailCustomSubject(emailRequests);

        Integer emailsSent = getSentEmailCount(household);
        System.assertEquals(n, emailsSent, 'Expected ' + n + ' emails but got ' + emailsSent);
        Test.stopTest();
    }

    @isTest
    static void sendEmail_noConfig_blocked(){
        Account acc = [SELECT Id FROM Account WHERE OW_admin_notes__c = 'EmailSendTestHousehold'];
        Id household = acc.Id;
        AccountContactRelation targetObject = [SELECT ContactId FROM AccountContactRelation WHERE AccountId =: household LIMIT 1][0];
        List<EmailSend.EmailSendRequestAutomatic> emailRequests = new List<EmailSend.EmailSendRequestAutomatic>();
        EmailSend.EmailSendRequestAutomatic emailRequest = new EmailSend.EmailSendRequestAutomatic();

        emailRequest.householdId = household;
        emailRequest.whatId = household;
        emailRequest.targetObjectId = targetObject.ContactId;
        emailRequest.saveAsActivity = true;
        emailRequest.subject = 'Test Email';
        emailRequest.emailTemplateDeveloperName = 'DefinitelyNotARealConfigRecord';            
        emailRequest.parameters = new Map<String, String>{};
        emailRequests.add(emailRequest);

        Test.startTest();
        EmailSend emailSender = new EmailSend();
        try{
            emailSender.sendAutomaticTemplatedEmailCustomSubject(emailRequests);
        }  catch (EmailSend.EmailSendException e) {
            System.Assert.isTrue(e.getMessage().contains('No email configurations found'), 'Allowed to send email without a config record');
        }
        Test.stopTest();
    }

    @isTest
    static void sendEmails_wrongConfig_blocked() {
        Integer n = 2;    
        Account acc = [SELECT Id FROM Account WHERE OW_admin_notes__c = 'EmailSendTestHousehold'];   
        Id household = acc.Id;
        AccountContactRelation targetObject = [SELECT ContactId FROM AccountContactRelation WHERE AccountId =: household LIMIT 1][0];
        List<EmailSend.EmailSendRequestAutomatic> emailRequests = new List<EmailSend.EmailSendRequestAutomatic>();
      
        EmailSend.EmailSendRequestAutomatic emailRequest = new EmailSend.EmailSendRequestAutomatic();
        emailRequest.householdId = household;
        emailRequest.whatId = household;
        emailRequest.targetObjectId = targetObject.ContactId;
        emailRequest.saveAsActivity = true;
        emailRequest.subject = 'Test Email';
        emailRequest.parameters = new Map<String, String>{};
        emailRequest.emailTemplateDeveloperName = 'NovaWealthFulfilmentUpdateFinal';            
        emailRequests.add(emailRequest);

        EmailSend.EmailSendRequestAutomatic emailRequest2 = new EmailSend.EmailSendRequestAutomatic();
        emailRequest2.householdId = household;
        emailRequest2.whatId = household;
        emailRequest2.targetObjectId = targetObject.ContactId;
        emailRequest2.saveAsActivity = true;
        emailRequest2.subject = 'Test Email';
        emailRequest2.parameters = new Map<String, String>{};
        emailRequest2.emailTemplateDeveloperName = 'DefinitelyNotARealConfigRecord';            
        emailRequests.add(emailRequest2);

        Test.startTest();
        EmailSend emailSender = new EmailSend();
        try{
            emailSender.sendAutomaticTemplatedEmailCustomSubject(emailRequests);
        }  catch (EmailSend.EmailSendException e) {
            System.Assert.isTrue(e.getMessage().contains('Email configuration records not found for all templates'), 'Allowed to send emails without all config records');
        }
        Test.stopTest();
    }

    @TestVisible
    private static final Boolean IS_EMAIL_DELIVERABILITY_ENABLED {
        get {
            if (IS_EMAIL_DELIVERABILITY_ENABLED == null) {
                try {
                    System.Messaging.reserveSingleEmailCapacity(1);
                    IS_EMAIL_DELIVERABILITY_ENABLED = true;
                } catch (System.NoAccessException e) {
                    IS_EMAIL_DELIVERABILITY_ENABLED = false;
                }
            }
            return IS_EMAIL_DELIVERABILITY_ENABLED;
        }
        set;
    } 
    
    public static Integer getSentEmailCount(Id recordId) {
        List<EmailMessage> sentEmails = [
            SELECT Id
            FROM EmailMessage
            WHERE RelatedToId = :recordId
        ];
        return sentEmails.size();
    }
}