unpackaged/main/default/objects/Account/fields/OW_admin_notes__c.field-meta.xml
<CustomField>
    <fullName>OW_admin_notes__c</fullName>
    <description>For storage of temporary messages while managing data migration etc to assist with tracking.</description>
    <label>Admin notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/OW_queue__c.field-meta.xml
<CustomField>
    <fullName>OW_queue__c</fullName>
    <description>The queue to which this household is assigned.</description>
    <label>Queue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OW_queues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PlatformId__c.field-meta.xml
<CustomField>
    <fullName>PlatformId__c</fullName>
    <description>To store the external ID of the account in finprod</description>
    <externalId>true</externalId>
    <label>Platform ID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Advice__c/fields/Assigned_planner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_planner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suitability planner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_planner</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/PlatformId__c.field-meta.xml
<CustomField>
    <fullName>PlatformId__c</fullName>
    <externalId>true</externalId>
    <label>Platform ID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Advice__c/recordTypes/Protection.recordType-meta.xml
<RecordType>
    <fullName>Protection</fullName>
    <active>true</active>
    <description>For advice that involves protection recommendations only.</description>
    <label>Protection</label>
</RecordType>

force-app/main/default/objects/Case/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Link to advice. Advice must be linked to case to send next steps email.</description>
    <label>Advice</label>
    <referenceTo>Advice__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlatformId__c.field-meta.xml
<CustomField>
    <fullName>PlatformId__c</fullName>
    <description>store the external ID of the account in the nova service</description>
    <externalId>true</externalId>
    <label>Platform ID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OW_task_information__c/OW_task_information__c.object-meta.xml
<CustomObject>
    <description>This object stores reference data related to tasks carried out by people across Octopus Wealth. In addition to a description of how to perform the task, there is useful information stored like which team performs it, whether the task is active, and which part of the process it falls under.</description>
    <label>Task Information</label>
    <nameField>
        <label>Task Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_task_information__c/fields/OW_assigned_to__c.field-meta.xml
<CustomField>
    <fullName>OW_assigned_to__c</fullName>
    <description>The team that this task is normally completed by.</description>
    <label>Assigned To</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Case owner</fullName>
            </value>
            <value>
                <fullName>Chosen user</fullName>
            </value>
            <value>
                <fullName>Dedicated specialist/household team</fullName>
            </value>
            <value>
                <fullName>Household team</fullName>
            </value>
            <value>
                <fullName>Opportunity owner</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Specific user</fullName>
            </value>
            <value>
                <fullName>Suitability planner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_due_date_offset__c.field-meta.xml
<CustomField>
    <fullName>OW_due_date_offset__c</fullName>
    <description>The number of business days after the task creation date that tasks created from this template will be due.</description>
    <inlineHelpText>How many business days after creation should this task be due? Use 0 for same day, 1 for next day etc.</inlineHelpText>
    <label>Due date offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_priority__c.field-meta.xml
<CustomField>
    <fullName>OW_priority__c</fullName>
    <description>The priority of the task created from this template.</description>
    <inlineHelpText>What priority do you want to be set for any tasks of this type?</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_process_variant__c.field-meta.xml
<CustomField>
    <fullName>OW_process_variant__c</fullName>
    <description>Describes whether this task is part of an old or new process (eg old factfind or new profile).</description>
    <label>Process Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Legacy Wealth Management</fullName>
            </value>
            <value>
                <fullName>Current Wealth Management Process</fullName>
            </value>
            <value>
                <fullName>New customer</fullName>
            </value>
            <value>
                <fullName>Annual review</fullName>
            </value>
            <value>
                <fullName>Tax year end</fullName>
            </value>
            <value>
                <fullName>Follow on advice</fullName>
            </value>
            <value>
                <fullName>Nurture lead</fullName>
            </value>
            <value>
                <fullName>Manage opportunity</fullName>
            </value>
            <value>
                <fullName>Manage application</fullName>
            </value>
            <value>
                <fullName>Employee onboarding</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder Turning 18</fullName>
            </value>
            <value>
                <fullName>Customer support</fullName>
            </value>
            <value>
                <fullName>Protection advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_queue__c.field-meta.xml
<CustomField>
    <fullName>OW_queue__c</fullName>
    <description>The queue to which tasks of this type should be assigned.</description>
    <label>Queue</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_team__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>OW_queues</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_record_type_developer_name__c.field-meta.xml
<CustomField>
    <fullName>OW_record_type_developer_name__c</fullName>
    <description>This field holds the developer name of the task record type. This is the unique reference used to identify to which task record type this information relates.</description>
    <inlineHelpText>This is a unique reference to the record type. This MUST NOT be changed without understanding the implications or it will stop task information from displaying when viewing tasks.</inlineHelpText>
    <label>Record type developer name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_specific_user__c.field-meta.xml
<CustomField>
    <fullName>OW_specific_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field in which a specific user can be identified for a given task information record.</description>
    <label>Specific user</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>User must be active.</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Task_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_stage__c.field-meta.xml
<CustomField>
    <fullName>OW_stage__c</fullName>
    <description>The stage of the advice process that this task falls under.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OW_process_variant__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Nurturing</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Data Gathering</fullName>
            </value>
            <value>
                <fullName>Suitability</fullName>
            </value>
            <value>
                <fullName>Fulfilment</fullName>
            </value>
            <value>
                <fullName>Annual Review</fullName>
            </value>
            <value>
                <fullName>Unactioned</fullName>
            </value>
            <value>
                <fullName>Gather information</fullName>
            </value>
            <value>
                <fullName>Broker mortgage</fullName>
            </value>
            <value>
                <fullName>Await completion</fullName>
            </value>
            <value>
                <fullName>Mortgage complete</fullName>
            </value>
            <value>
                <fullName>Applying for DIP</fullName>
            </value>
            <value>
                <fullName>DIP granted</fullName>
            </value>
            <value>
                <fullName>Agree product</fullName>
            </value>
            <value>
                <fullName>Provide advice</fullName>
            </value>
            <value>
                <fullName>Applying for mortgage</fullName>
            </value>
            <value>
                <fullName>Mortgage offered</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_status__c.field-meta.xml
<CustomField>
    <fullName>OW_status__c</fullName>
    <description>The status of the task description itself.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Out of date</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_subject__c.field-meta.xml
<CustomField>
    <fullName>OW_subject__c</fullName>
    <description>The subject of the task created from this template.</description>
    <inlineHelpText>What subject do you want to be set for any tasks of this type?</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_task_information__c/fields/OW_task_credit__c.field-meta.xml
<CustomField>
    <fullName>OW_task_credit__c</fullName>
    <description>Credit depending on how much time and effort the task takes</description>
    <label>Task credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_task_type__c.field-meta.xml
<CustomField>
    <fullName>OW_task_type__c</fullName>
    <description>A code that will identify the type of task this task information record represents.</description>
    <label>Task type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_team__c.field-meta.xml
<CustomField>
    <fullName>OW_team__c</fullName>
    <description>Used to capture the team that looks after this task.</description>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business operations</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Mortgages</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Planners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_task_information__c/fields/OW_turnaround_time__c.field-meta.xml
<CustomField>
    <fullName>OW_turnaround_time__c</fullName>
    <description>The number of business days prior to the task due date that the target start date will be set for any tasks created using this template.</description>
    <inlineHelpText>How many business days before the task due date should the target start date be set? Use 0 to have the target start date equal the due date, 1 for it to be the business day before etc.</inlineHelpText>
    <label>Turnaround time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>false</active>
    <label>zDel Test</label>
</RecordType>

force-app/main/default/classes/TaskEngineTest.cls
@isTest
private class TaskEngineTest {

    static final string HOUSEHOLD_IDENTIFIER = 'testHousehold';
    static final string CASE_IDENTIFIER = 'testCase';
    static final string OPPORTUNITY_IDENTIFIER = 'testOpportuntiy';
    static final string QUEUE_IDENTIFIER = 'OperationsTeamA';
    static final string HOUSEHOLD_QUEUE_IDENTIFIER = 'OperationsTeamB';
    static final string USER_IDENTIFIER = 'testUser@testnova.com';
    static final string PARTNER_IDENTIFIER = 'testPartner@testnova.com';
    static final string CHOSEN_USER_IDENTIFIER = 'testChosenUser@testnova.com';
    static final string CASE_OWNER_IDENTIFIER = 'testCaseUser@testnova.com';
    static final string OPPORTUNITY_OWNER_IDENTIFIER = 'testOpportintyUser@testnova.com';
    static final string SUITIBILITY_PLANNER_IDENTIFIER = 'testSuitabilityUser@testnova.com';

    static final string TEAM_OPERATIONS = 'Operations';
    static final string TEAM_MORTGAGES = 'Mortgages';
    static final string TEAM_BUSINESS_OPERATIONS = 'Business operations';
    static final string TEAM_PARTNERS = 'Partners';

    public static User testUser = new User();
    public static User testPartner = new User();
    public static User testChosenUser = new User();
    public static User testCaseOwner = new User();
    public static User testOpportunityOwner = new User();
    public static User testSuitibilityPlanner = new User();

    public static Group testQueue = new Group();
    public static Group testHouseholdQueue = new Group();

    static List<String> assignmentTypeList = new List<String>{
        taskEngine.ASSIGNED_TO_CASE_OWNER,
        taskEngine.ASSIGNED_TO_CHOSEN_USER,
        taskEngine.ASSIGNED_TO_DEDICATED_TEAM,
        taskEngine.ASSIGNED_TO_HOUSEHOLD_TEAM,
        taskEngine.ASSIGNED_TO_OPPORTUNITY_OWNER,
        taskEngine.ASSIGNED_TO_PARTNER,
        taskEngine.ASSIGNED_TO_QUEUE,
        taskEngine.ASSIGNED_TO_SPECIFIC_USER,
        taskEngine.ASSIGNED_TO_SUITABILITY_PLANNER
    };

    @TestSetup
    static void makeData(){
       //List<sObject> ls5 = Test.loadData(OW_task_information__c.sObjectType, 'taskInformationRef');

        DataFactory df = new DataFactory();

        Id accountTestId = df.createHousehold(HOUSEHOLD_IDENTIFIER, 2, 1, 'Withdrawn', 'Full');
        Case testCase = df.createCase(CASE_IDENTIFIER, accountTestId);
        Opportunity testOpportunity = df.craeteOpportunity(accountTestId, OPPORTUNITY_IDENTIFIER);
        Advice__c testAdvice = df.createTopUpAdvice(accountTestId);

        List<OW_task_information__c> taskInfoList = new List<OW_task_information__c>();

        //Scope to insert in list to conserve DML statements
        testUser = df.createUser(USER_IDENTIFIER);
        testPartner = df.createUser(PARTNER_IDENTIFIER);
        testChosenUser = df.createUser(CHOSEN_USER_IDENTIFIER);
        testCaseOwner = df.createUser(CASE_OWNER_IDENTIFIER);
        testOpportunityOwner = df.createUser(OPPORTUNITY_OWNER_IDENTIFIER);
        testSuitibilityPlanner = df.createUser(SUITIBILITY_PLANNER_IDENTIFIER);

        //update partner as owner of household
        Account testHousehold = new Account(Id = accountTestId, OwnerId = testPartner.Id, OW_queue__c = HOUSEHOLD_QUEUE_IDENTIFIER);
        update testHousehold;

        testCase.OwnerId = testCaseOwner.Id;
        update testCase;

        testOpportunity.OwnerId = testOpportunityOwner.Id;
        update testOpportunity;

        testAdvice.Assigned_planner__c = testSuitibilityPlanner.Id;
        update testAdvice;

        testQueue = df.createQueue(QUEUE_IDENTIFIER);
        testHouseholdQueue = df.createQueue(HOUSEHOLD_QUEUE_IDENTIFIER);

        Integer i = 0;
        for(String assignmentType : assignmentTypeList){
            OW_task_information__c taskInfo = new OW_task_information__c();
            taskInfo.Name = 'task information ' + i;
            taskInfo.OW_task_type__c = 'task_information_' + i;
            taskInfo.OW_record_type_developer_name__c = 'task_information_' + i;
            taskInfo.OW_subject__c = assignmentType; //slightly hacky to reference in test to see if correct logic worked
            taskInfo.OW_status__c = taskEngine.TASK_TYPE_STATUS_ACTIVE;
            taskInfo.OW_task_credit__c = i;
            taskInfo.OW_due_date_offset__c = i;
            taskInfo.OW_turnaround_time__c = i + 2;
            taskInfo.OW_assigned_to__c = assignmentType;
            taskInfo.OW_priority__c = 'Medium';
            taskInfo.OW_process_variant__c = 'Protection advice';
            taskInfo.OW_stage__c = 'N/A';

            //have to deal with picklist dependancies
            if(new List<String>{TaskEngine.ASSIGNED_TO_CASE_OWNER, TaskEngine.ASSIGNED_TO_CHOSEN_USER, TaskEngine.ASSIGNED_TO_DEDICATED_TEAM, TaskEngine.ASSIGNED_TO_HOUSEHOLD_TEAM}.contains(assignmentType)){
                taskInfo.OW_team__c = TEAM_OPERATIONS;
            
            } else if(assignmentType == TaskEngine.ASSIGNED_TO_OPPORTUNITY_OWNER || assignmentType == TaskEngine.ASSIGNED_TO_SUITABILITY_PLANNER){
                taskInfo.OW_team__c = TEAM_MORTGAGES;

            } else if(assignmentType == taskEngine.ASSIGNED_TO_QUEUE){
                taskInfo.OW_queue__c = QUEUE_IDENTIFIER;
                taskInfo.OW_team__c = TEAM_OPERATIONS;

            } else if(assignmentType == taskEngine.ASSIGNED_TO_SPECIFIC_USER){
                taskInfo.OW_specific_user__c = testUser.Id;
                taskInfo.OW_team__c = TEAM_BUSINESS_OPERATIONS;
            
            } else if(assignmentType == TaskEngine.ASSIGNED_TO_PARTNER){
                taskInfo.OW_Team__c = TEAM_PARTNERS;
            }

            taskInfoList.add(taskInfo);
            i++;
        }

        insert taskInfoList;

    }

    @isTest
    static void testTaskEngine(){

        //query household to use as test data
        User chosenUser = [SELECT Id FROM User WHERE Username = :CHOSEN_USER_IDENTIFIER LIMIT 1];
        User testUser = [SELECT Id FROM User WHERE Username = :USER_IDENTIFIER LIMIT 1];
        User testSuitibilityPlanner = [SELECT Id FROM User WHERE Username = :SUITIBILITY_PLANNER_IDENTIFIER LIMIT 1];

        Account accountTest = [SELECT Id, Name, OwnerId FROM Account WHERE OW_admin_notes__c = :HOUSEHOLD_IDENTIFIER LIMIT 1];
        Case caseTest = [SELECT Id, ownerId FROM Case WHERE Subject = :CASE_IDENTIFIER LIMIT 1];
        Opportunity opportunityTest = [SELECT Id, ownerId FROM Opportunity WHERE AccountId = :accountTest.Id AND PlatformId__c = :OPPORTUNITY_IDENTIFIER LIMIT 1];
        Advice__c adviceTest = [SELECT Id, Assigned_planner__c FROM Advice__c WHERE Assigned_planner__c = :testSuitibilityPlanner.Id LIMIT 1];
        
        Group testQueue = [SELECT Id FROM Group WHERE DeveloperName = :QUEUE_IDENTIFIER LIMIT 1];
        Group testHouseholdQueue = [SELECT Id FROM Group WHERE DeveloperName = :HOUSEHOLD_QUEUE_IDENTIFIER LIMIT 1];

        List<OW_task_information__c> taskInformationList = [SELECT Id, OW_assigned_to__c, OW_task_type__c, OW_task_credit__c, OW_subject__c, OW_due_date_offset__c, OW_turnaround_time__c FROM OW_task_information__c];

        Map<String, OW_task_information__c> assignmentTypeTaskInfoMap = new Map<String, OW_task_information__c>();

        //find an example of one task for each assingment type
        for(String assignmentType : assignmentTypeList){
            for(OW_task_information__c taskInfo : taskInformationList){
                if(taskInfo.OW_assigned_to__c == assignmentType){
                    assignmentTypeTaskInfoMap.put(assignmentType, taskInfo);
                    break;
                }
            }
        }

        List<TaskEngineRequest> taskRequests = new List<TaskEngineRequest>();
        for(OW_task_information__c taskInfo : assignmentTypeTaskInfoMap.values()){
            TaskEngineRequest taskEngineRequest = new TaskEngineRequest();
            taskEngineRequest.taskType = taskInfo.OW_task_type__c;
            taskEngineRequest.householdId = accountTest.Id;
            taskEngineRequest.whatId = accountTest.Id;

            if(taskInfo.OW_assigned_to__c == TaskEngine.ASSIGNED_TO_CASE_OWNER){
                taskEngineRequest.whatId = caseTest.Id;
            }

            if(taskInfo.OW_assigned_to__c == TaskEngine.ASSIGNED_TO_OPPORTUNITY_OWNER){
                taskEngineRequest.whatId = opportunityTest.Id;
            }

            if(taskInfo.OW_assigned_to__c == TaskEngine.ASSIGNED_TO_CHOSEN_USER){
                taskEngineRequest.chosenUser = chosenUser.Id;   
            }

            if(taskInfo.OW_assigned_to__c == TaskEngine.ASSIGNED_TO_CASE_OWNER){
                taskEngineRequest.whatId = caseTest.Id;
            }

            if(taskInfo.OW_assigned_to__c == TaskEngine.ASSIGNED_TO_OPPORTUNITY_OWNER){
                taskEngineRequest.whatId = opportunityTest.Id;
            }

            if(taskInfo.OW_assigned_to__c == TaskEngine.ASSIGNED_TO_SUITABILITY_PLANNER){
                taskEngineRequest.whatId = adviceTest.Id;
            }

            taskRequests.add(taskEngineRequest);
            
        }

        //teskInvokable method too
        FlowUtilityTaskCreateList.FlowInputs taskRequestFlowInput = new FlowUtilityTaskCreateList.FlowInputs();
        taskRequestFlowInput.taskRequests = taskRequests;

        List<FlowUtilityTaskCreateList.FlowInputs> taskRequestFlowInputList = new List<FlowUtilityTaskCreateList.FlowInputs>();
        taskRequestFlowInputList.add(taskRequestFlowInput);

        //test method directly and via invokable method together as setup for test taks a long time
        Test.startTest();
        TaskEngine.generateTasks(taskRequests);
        List<FlowUtilityTaskCreateList.FlowOutputs> flowOutputs = FlowUtilityTaskCreateList.invocableGenerateTasks(taskRequestFlowInputList);
        Test.stopTest();

        for(FlowUtilityTaskCreateList.FlowOutputs flowOutput : flowOutputs){
            Assert.isTrue(flowOutput.isSuccess, 'Invokable apex task creation failure');
        }

        List<Task> generatedTaskList = [SELECT Id, Subject, OW_credit__c, ActivityDate, OW_target_start_date__c, OwnerId, WhatId FROM Task];

        Map<String, OW_task_information__c> taskAssignmentToInfoMap = new Map<String, OW_task_information__c>();

        for(OW_task_information__c t : taskInformationList){
            taskAssignmentToInfoMap.put(t.OW_assigned_to__c, t);
        }

        Assert.isTrue(generatedTaskList.size() > 0, 'No tasks were generated');
        Assert.areEqual(taskRequests.size() * 2, generatedTaskList.size(), 'An incorrect number of tasks have been generated');

        for(Task task : generatedTaskList){
            OW_task_information__c taskInfo = taskAssignmentToInfoMap.get(task.Subject);
            
            Assert.areEqual(task.OW_credit__c, taskInfo.OW_task_credit__c, 'Task credit not properly assinged');
            Assert.areEqual(task.Subject, taskInfo.OW_subject__c, 'Task subject not properly assinged');
             
            Date dueDate = Utility.getOffsetBusinessDate(Date.today(), (integer) taskInfo.OW_due_date_offset__c);
            Date startDate = Utility.getOffsetBusinessDate(dueDate,  (integer) -taskInfo.OW_turnaround_time__c);

            Assert.areEqual(dueDate, task.ActivityDate, 'Task due date not properly calculated');
            Assert.areEqual(startDate, task.OW_target_start_date__c, 'Task start date not properly calculated');

            if (task.WhatId != null && task.WhatId.getSObjectType() == Opportunity.sObjectType) {
                //assert opp user
                Assert.areEqual(opportunityTest.OwnerId, task.OwnerId, 'Task Owner is not the same as the Opportunity Owner');
            
            } else if (task.WhatId != null && task.WhatId.getSObjectType() == Case.sObjectType) {
                //assert opp user
                Assert.areEqual(caseTest.OwnerId, task.OwnerId, 'Task Owner is not the same as the Case Owner');
            
            } else if(taskInfo.OW_assigned_to__c == TaskEngine.ASSIGNED_TO_QUEUE){
                //assert queue user
                Assert.areEqual(testQueue.Id, task.OwnerId, 'Task Owner is not the same as the Queue Id');

            } else if(taskInfo.OW_assigned_to__c == TaskEngine.ASSIGNED_TO_HOUSEHOLD_TEAM){
                //assert household queue
                Assert.areEqual(testHouseholdQueue.Id, task.OwnerId, 'Task Owner is not the same as the Houshold Queue Id');
            
            } else if(taskInfo.OW_assigned_to__c == TaskEngine.ASSIGNED_TO_PARTNER){
                //assert partner user
                Assert.areEqual(accountTest.OwnerId, task.OwnerId, 'Task Owner is not the same as the Partner User Id');
            
            } else if(taskInfo.OW_assigned_to__c == taskEngine.ASSIGNED_TO_SUITABILITY_PLANNER){
                //assert suitability planner user
                Assert.areEqual(testSuitibilityPlanner.Id, task.OwnerId, 'Task Owner is not the same as the Suitability Planner Id');
            
            }
        }

    }
}