force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The post-CheerIO product this relates to</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Financial Products</relationshipLabel>
    <relationshipName>Financial_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Public_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Public_Provider_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Public Provider Name</label>
    <referenceTo>Public_Provider_Names__c</referenceTo>
    <relationshipLabel>Financial Products</relationshipLabel>
    <relationshipName>Financial_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/RegisteredContact__c.field-meta.xml
<CustomField>
    <fullName>RegisteredContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For junior products, this is the adult registered on the account</description>
    <label>Registered contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Products (Registered contact)</relationshipLabel>
    <relationshipName>Financial_Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment__c/Fulfilment__c.object-meta.xml
<CustomObject>
    <description>An object to store the progress of fulfilling recommendations</description>
    <label>Fulfilment</label>
    <nameField>
        <displayFormat>Flfl-{0000000}</displayFormat>
        <label>Fulfilment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment__c/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation which resulted in this fulfilment</description>
    <label>Recommendation</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment__c/fields/ResidualCash__c.field-meta.xml
<CustomField>
    <fullName>ResidualCash__c</fullName>
    <description>Indicates whether residual cash was left behind after a transfer and, if so, where we are with receiving it from the ceding provider.</description>
    <label>Residual cash</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
                <label>None</label>
            </value>
            <value>
                <fullName>AWAITING</fullName>
                <label>Awaiting</label>
            </value>
            <value>
                <fullName>RECEIVED</fullName>
                <label>Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Will store the kinds of products we can provide in the post-cheerIO world.</description>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Provider_Names__c/Public_Provider_Names__c.object-meta.xml
<CustomObject>
    <label>Public Provider List</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Provider List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/Recommendation__c.object-meta.xml
<CustomObject>
    <description>Contains all the information given by planners when making a recommendation of an action for a change in a clients financial circumstances.</description>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>Rec-{0000000}</displayFormat>
        <label>Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/fields/DestinationLegacy__c.field-meta.xml
<CustomField>
    <fullName>DestinationLegacy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account which is receiving funds or undergoing a change</description>
    <label>Destination</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The household to which this recommendation is being made.</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Recommendation__c/fields/PreRequisiteRecommendation__c.field-meta.xml
<CustomField>
    <fullName>PreRequisiteRecommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the recommendation which must be completed before this one can be done</description>
    <label>Pre-requisite recommendation destination</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>PrimaryOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the main client that this recommendation relates to, the primary owner of the destination product</description>
    <label>Primary owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation (Primary owner)</relationshipLabel>
    <relationshipName>Recommendation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of product this recommendation relates to. Likely only used for open product recommendations</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/RegisteredContact__c.field-meta.xml
<CustomField>
    <fullName>RegisteredContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The adult associated with this junior account</description>
    <inlineHelpText>The adult associated with this junior account</inlineHelpText>
    <label>Registered contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation (Registered contact)</relationshipLabel>
    <relationshipName>Recommendation4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/SourceLegacy__c.field-meta.xml
<CustomField>
    <fullName>SourceLegacy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The source of funds for this recommendations. Related to pre-CheerIO financial product object.</description>
    <label>Source</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Recommendation (Source)</relationshipLabel>
    <relationshipName>Recommendation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/TransferType__c.field-meta.xml
<CustomField>
    <fullName>TransferType__c</fullName>
    <description>Denotes whether transfer is full or partial</description>
    <label>Transfer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailPensionTransferCompleteAutomated.cls
/**
 * This class is the controller for a SIPP/JSIPP transfer cancellation notice email template. 
 * It exists only to produce the content for this email and should be used for no other purpose. 
 */
public class EmailPensionTransferCompleteAutomated {

    public String objectId{get;set;}
    private Fulfilment__c fulfilment = new Fulfilment__c();
    Boolean constructorRun = false;
    
    // Constructor to set the fulfilment record
    public void EmailPensionTransferCompleteAutomated() {
        if(!constructorRun){
            constructorRun = true;
            if(String.isBlank(objectId)){
                objectId = ApexPages.currentPage().getParameters().get('objectId');
            }
            if (String.isNotBlank(objectId)) {
                fulfilment = [
                    SELECT 
                        Id, 
                        Recommendation__c,
                        Recommendation__r.PrimaryOwner__r.AddressedName__pc,
                        Recommendation__r.RegisteredContact__c,
                        Recommendation__r.RegisteredContact__r.AddressedName__pc,
                        Recommendation__r.Product__r.Name,
                        ResidualCash__c,
                        Recommendation__r.SourceLegacy__r.Public_Provider_Name__r.Name,
                        Recommendation__r.DestinationLegacy__r.Public_Provider_Name__r.Name,
                        Recommendation__r.TransferType__c
                    FROM
                        Fulfilment__c 
                    WHERE
                        Id = :objectId
                ];
            }
        }
    }
    
    // Method to format today's date into a client friendly format
    public String dateString {
        get {
            UtilityString us = new UtilityString();
            return us.formatDateForNovaEmail(Datetime.now());
        }
    }
    
    // Determines if there is residual cash or not, allowing the associate passage of text to be hidden/shown as appopriate.
    public Boolean residualCash {
        get{
            if (fulfilment.ResidualCash__c == 'NONE') {
                return false;
            } else {
                return true;
            }
        }
    }

    // Method to provide the friendly name of the destination
    public String finProdNameDestination{
        get{
            String result = '';
            if( fulfilment.Recommendation__r.RegisteredContact__c == null ) {
                result = result + 'your ';
            } else {
                result = result + fulfilment.Recommendation__r.PrimaryOwner__r.AddressedName__pc + '\'s ';
            }
            result = result 
                + fulfilment.Recommendation__r.DestinationLegacy__r.Public_Provider_Name__r.Name 
                + ' ' 
                + fulfilment.Recommendation__r.Product__r.Name;
            return result;
        }
    }
    
    // Method to provide the friendly name of the source
    public String finProdNameSource{
        get{
            String result = '';
            if( fulfilment.Recommendation__r.RegisteredContact__c == null ) {
                result = result + 'your ';
            } else {
                result = result + fulfilment.Recommendation__r.PrimaryOwner__r.AddressedName__pc + '\'s ';
            }
            result = result 
                + fulfilment.Recommendation__r.SourceLegacy__r.Public_Provider_Name__r.Name 
                + ' pension';
            return result;
        }
    }
    
    // Method to provide string for a partial transfer if required
    public String partialString{
        get{
            EmailPensionTransferCompleteAutomated();
            if (fulfilment.recommendation__r.TransferType__c == 'Partial') {
                return ' partial ';
            } else {
                return '';
            }
        }
    }
}