force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Primary Owner&#39;s household</inlineHelpText>
    <label>Household Lookup</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household.

(Admin message: lookup filter criteria not met on Household on the financial product object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/InformationRequest__c.object-meta.xml
<CustomObject>
    <description>Used to track the process of gathering information for financial products</description>
    <label>Information Request</label>
    <nameField>
        <displayFormat>IR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Information Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformationRequest__c/fields/FinancialProductFinServ__c.field-meta.xml
<CustomField>
    <fullName>FinancialProductFinServ__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The financial product that this information request is for</description>
    <label>Financial product</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>InformationRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/InformationRequestType__c.field-meta.xml
<CustomField>
    <fullName>InformationRequestType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of information request process needed</description>
    <label>Information Request Type</label>
    <referenceTo>InformationRequestType__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>InformationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the overall progression of the data gathering process for this policy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Awaiting policy pre-requisites</fullName>
            </value>
            <value>
                <fullName>Awaiting advice progression</fullName>
            </value>
            <value>
                <fullName>Information request to be sent</fullName>
            </value>
            <value>
                <fullName>Awaiting initial information</fullName>
            </value>
            <value>
                <fullName>Checklist review</fullName>
            </value>
            <value>
                <fullName>Fund analysis</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting ad hoc action</fullName>
            </value>
            <value>
                <fullName>Additional checklist review</fullName>
                <isActive>false</isActive>
                <label>Additional checklist review</label>
            </value>
            <value>
                <fullName>Awaiting additional information</fullName>
                <isActive>false</isActive>
                <label>Awaiting additional information</label>
            </value>
            <value>
                <fullName>Awaiting approval</fullName>
                <isActive>false</isActive>
                <label>Awaiting approval</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>Waiting for provider</fullName>
                <isActive>false</isActive>
                <label>Waiting for provider</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InformationRequestType__c/InformationRequestType__c.object-meta.xml
<CustomObject>
    <description>Used to specify process for different data gathering scenarios</description>
    <label>Information Request Type</label>
    <nameField>
        <label>Information Request Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Information Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformationRequestType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates if this is a current process</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InformationRequestHouseholdDisplay.cls
/**
 * This class exists exclusively to provide support for the Information Request Related List for households LWC.
 * It should not be used in any other contexts.
 * It gets information requests for any financial product related to the household and formats the data into a list of maps for an LWC to use. 
 */
public with sharing class InformationRequestHouseholdDisplay {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> formattedData(String recordId) {
    	List<Map<String, String>> outputs = new List<Map<String, String>>();
        
        List<FinServ__FinancialAccount__c> accounts = [SELECT Id FROM FinServ__FinancialAccount__c WHERE Household__c =: recordId];
        Set<Id> ids = new Set<Id>(new Map<Id, FinServ__FinancialAccount__c>(accounts).keySet());
        List<InformationRequest__c> listIrs= [SELECT Id, Name, Status__c, InformationRequestType__r.Name, FinancialProductFinServ__c, InformationRequestType__c, FinancialProductFinServ__r.Name FROM InformationRequest__c WHERE FinancialProductFinServ__c IN :ids AND Status__c NOT IN ('Complete', 'Cancelled')];
        String urlPrefix = URL.getOrgDomainURL().toExternalForm() + '/';
        
        List<Schema.PicklistEntry> statusValues = InformationRequest__c.Status__c.getDescribe().getPicklistValues();
        Map<String,String> statusApiToLabelMap = new Map<String,String>();
        For(Schema.PicklistEntry sp : statusValues){
            //Map to hold Picklist API as Key and Picklist Label as Value
            statusApiToLabelMap.put(sp.getValue(), sp.getLabel());
        }

        for( InformationRequest__c ir : listIrs ) {
        	Map<String, String> tempMap = new Map<String, String>();
        	tempMap.put('Id',ir.Id);
            tempMap.put('Name',ir.Name);
            tempMap.put('Link', urlPrefix + ir.Id);
			tempMap.put('Status',statusApiToLabelMap.get(ir.Status__c));
            tempMap.put('FinancialProductName',ir.FinancialProductFinServ__r.Name);
            tempMap.put('FinancialProductLink',urlPrefix + ir.FinancialProductFinServ__c);
            tempMap.put('Type',ir.InformationRequestType__r.Name);
            System.debug(tempMap);

            outputs.add(tempMap);
    	}
        System.debug(outputs);
        return outputs;
    }
    public List<Map<String, String>> getOutputs(String recordId){
        return formattedData(recordId);
    }
}