force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Primary Owner&#39;s household</inlineHelpText>
    <label>Household Lookup</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household.

(Admin message: lookup filter criteria not met on Household on the financial product object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/InformationRequest__c.object-meta.xml
<CustomObject>
    <description>Used to track the process of gathering information for financial products</description>
    <label>Information Request</label>
    <nameField>
        <displayFormat>IR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Information Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformationRequest__c/fields/AuthorityStatus__c.field-meta.xml
<CustomField>
    <fullName>AuthorityStatus__c</fullName>
    <description>Indicates the progress of our authority on this plan</description>
    <label>Authority status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be requested</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/FinancialProductFinServ__c.field-meta.xml
<CustomField>
    <fullName>FinancialProductFinServ__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The financial product that this information request is for</description>
    <label>Financial product</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>InformationRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/InformationRequestType__c.field-meta.xml
<CustomField>
    <fullName>InformationRequestType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of information request process needed</description>
    <label>Information Request Type</label>
    <referenceTo>InformationRequestType__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>InformationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the overall progression of the data gathering process for this policy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Awaiting policy pre-requisites</fullName>
            </value>
            <value>
                <fullName>Awaiting advice progression</fullName>
            </value>
            <value>
                <fullName>Information request to be sent</fullName>
            </value>
            <value>
                <fullName>Awaiting initial information</fullName>
            </value>
            <value>
                <fullName>Checklist review</fullName>
            </value>
            <value>
                <fullName>Fund analysis</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting ad hoc action</fullName>
            </value>
            <value>
                <fullName>Additional checklist review</fullName>
                <isActive>false</isActive>
                <label>Additional checklist review</label>
            </value>
            <value>
                <fullName>Awaiting additional information</fullName>
                <isActive>false</isActive>
                <label>Awaiting additional information</label>
            </value>
            <value>
                <fullName>Awaiting approval</fullName>
                <isActive>false</isActive>
                <label>Awaiting approval</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>Waiting for provider</fullName>
                <isActive>false</isActive>
                <label>Waiting for provider</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InformationRequestType__c/InformationRequestType__c.object-meta.xml
<CustomObject>
    <description>Used to specify process for different data gathering scenarios</description>
    <label>Information Request Type</label>
    <nameField>
        <label>Information Request Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Information Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformationRequestType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates if this is a current process</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LwcHelperDynamicRecordList.cls
public with sharing class LwcHelperDynamicRecordList {

    public class DataWrapperException extends Exception {}
    private static final Set<String> VALID_COLUMN_TYPES = new Set<String>{'text', 'url', 'currency', 'number', 'date', 'percent', 'location'};

    @AuraEnabled
    public static DataWrapper getDynamicData(String logicReference, Id contextId) {
        DataWrapper dataWrapper = new DataWrapper();
        switch on logicReference {
            /*when 'LOGIC_NAME_HERE'{
                dataWrapper = ClassName.functionName(contextId);
            }*/
            when else{
                dataWrapper.errorMessage = 'No logic reference matched';
            }
        }

        List<String> errors = validateDataWrapper(dataWrapper);
        if(errors.size() > 0) {
            System.debug(errors);
            dataWrapper.errorMessage += String.join(errors, '; ');
        }
        return dataWrapper;
    }

    public class DataWrapper{
        @AuraEnabled public List<ColumnWrapper> columns = new List<ColumnWrapper>();
        @AuraEnabled public List<RowWrapper> rows = new List<RowWrapper>();
        @AuraEnabled public ConfigWrapper config = new ConfigWrapper();
        @AuraEnabled public string errorMessage;
    }

    public class ConfigWrapper{
        //@AuraEnabled public String objectAPIName;
        //@AuraEnabled public String sobjectLabel;
        @AuraEnabled public String keyFieldName;
        //@AuraEnabled public String idFieldNameToReference;
        //@AuraEnabled public String nameFieldNameToReference;
        //@AuraEnabled public boolean allowNew;
        //@AuraEnabled public boolean allowEdit;
        //@AuraEnabled public boolean allowDelete;
    }

    public class ColumnWrapper{
        @AuraEnabled public String label;
        @AuraEnabled public String fieldName;
        @AuraEnabled public String type;
        @AuraEnabled public Boolean sortable = true;
        @AuraEnabled public TypeAttributesWrapper typeAttributes = new TypeAttributesWrapper();
        @AuraEnabled public string iconName;
        @AuraEnabled public boolean hideLabel;

        public ColumnWrapper(String label, String fieldName, String type){
            this.label = label;
            this.fieldName = fieldName;
            this.type = type;
        }
    }

    public class TypeAttributesWrapper{
        //LWC will sort through and only apply relevant ones based on type
        
        //url
        @AuraEnabled public Map<String, String> label = new Map<String, String>{'fieldName' => ''};
        @AuraEnabled public String target = '_blank';
        @AuraEnabled public String tooltip;
        
        //currency - https://developer.salesforce.com/docs/component-library/bundle/lightning-formatted-number/specification
        @AuraEnabled public string currencyCode;
        @AuraEnabled public string currencyDisplayAs;
        @AuraEnabled public double step; // also used for percentacge
        //Also used for number & percentage
        @AuraEnabled public double minimumIntegerDigits;
        @AuraEnabled public double minimumFractionDigits;
        @AuraEnabled public double maximumFractionDigits;
        @AuraEnabled public double minimumSignificantDigits;
        @AuraEnabled public double maximumSignificantDigits;

        //date - https://developer.salesforce.com/docs/component-library/bundle/lightning-formatted-date-time/specification
        @AuraEnabled public string era;
        @AuraEnabled public string hour;
        @AuraEnabled public boolean hour12;
        @AuraEnabled public string minute;
        @AuraEnabled public string second;
        @AuraEnabled public string timeZone;
        @AuraEnabled public string timeZoneName;
        @AuraEnabled public string weekday;
        //also used for date-local
        @AuraEnabled public string day;
        @AuraEnabled public string month;
        @AuraEnabled public string year;

        //location
        @AuraEnabled public string latitude;
        @AuraEnabled public string longitude;
    }

    public class RowWrapper{
        @AuraEnabled public List<FieldWrapper> fields = new List<FieldWrapper>();
    }

    public class FieldWrapper{
        @AuraEnabled public String fieldName;
        @AuraEnabled public String value;

        public FieldWrapper(String fieldName, String value){
            this.fieldName = fieldName;
            this.value = value;
        }
    }


    public static List<String> validateDataWrapper(DataWrapper wrapper) {
        List<String> errors = new List<String>();

        Set<String> columnFieldNames = new Set<String>();

        // Validate columns
        for (ColumnWrapper col : wrapper.columns) {
            if (String.isBlank(col.fieldName)) {
                errors.add('Column is missing fieldName.');
            } else {
                columnFieldNames.add(col.fieldName);
            }

            if (String.isBlank(col.type) || !VALID_COLUMN_TYPES.contains(col.type)) {
                errors.add('Invalid or missing type for column: ' + col.label);
            }

            if (String.isBlank(col.label) && String.isBlank(col.iconName)) {
                errors.add('Column must have either label or iconName.');
            }

            // Validate typeAttributes for specific types
            if (col.type == 'url' && (col.typeAttributes == null || String.isBlank(col.typeAttributes.target))) {
                errors.add('URL column is missing required typeAttributes');
            }
            if (col.type == 'currency' && (col.typeAttributes == null || String.isBlank(col.typeAttributes.currencyCode))) {
                errors.add('Currency column is missing required typeAttributes');
            }
        }
        // Validate rows
        for (RowWrapper row : wrapper.rows) {
            Set<String> rowFieldNames = new Set<String>();
            for (FieldWrapper field : row.fields) {
                if (String.isBlank(field.fieldName)) {
                    errors.add('Field in row is missing fieldName.');
                }
                rowFieldNames.add(field.fieldName);
            }

            for (String colFieldName : columnFieldNames) {
                if (!rowFieldNames.contains(colFieldName)) {
                    errors.add('Row is missing field for column fieldName: ' + colFieldName);
                }
            }

            if(wrapper.config.keyFieldName == null || !rowFieldNames.contains(wrapper.config.keyFieldName)){
                errors.add('Key field not present in row list: ' + wrapper.config.keyFieldName);
            }
        }

        return errors;
    }

    public static DataWrapper getHouseholdMembers(Id householdId){
        DataWrapper dataWrapper = new DataWrapper();

        dataWrapper.config.keyFieldName = 'id';

        ColumnWrapper nameLinkColumn = new ColumnWrapper('Name', 'nameLink', 'url');
        nameLinkColumn.typeAttributes.label.put('fieldName', 'name');

        dataWrapper.columns.add(new ColumnWrapper('ID', 'id', 'text'));
        dataWrapper.columns.add(nameLinkColumn);
        
        List<AccountContactRelation> householdMembers = [SELECT Contact.AccountId, Contact.FirstName, Contact.LastName FROM AccountContactRelation WHERE AccountId =: householdId];

        for(AccountContactRelation householdMember: householdMembers){
            RowWrapper rowWrapper = new RowWrapper();
            rowWrapper.fields.add(new FieldWrapper('id', householdMember.Contact.AccountId));
            rowWrapper.fields.add(new FieldWrapper('name', householdMember.Contact.FirstName + ' ' + Contact.LastName));
            rowWrapper.fields.add(new FieldWrapper('nameLink', '/'+householdMember.Contact.Id));

            dataWrapper.rows.add(rowWrapper);
        }

        return dataWrapper;
    }

    public static DataWrapper getInformationRequests(Id recordId) {
        DataWrapper dataWrapper = new DataWrapper();
        dataWrapper.config.keyFieldName = 'id';

        ColumnWrapper nameLinkColumn = new ColumnWrapper('Name', 'nameLink', 'url');
        nameLinkColumn.typeAttributes.label.put('fieldName', 'name');

        ColumnWrapper finaicialProductLinkColumn = new ColumnWrapper('Financial Product', 'financialProductLink', 'url');
        finaicialProductLinkColumn.typeAttributes.label.put('fieldName', 'financialProduct');

        dataWrapper.columns.add(nameLinkColumn);
        dataWrapper.columns.add(new ColumnWrapper('Status', 'status', 'text'));
        dataWrapper.columns.add(finaicialProductLinkColumn);
        dataWrapper.columns.add(new ColumnWrapper('Type', 'type', 'text'));
        dataWrapper.columns.add(new ColumnWrapper('Authority Status', 'authStatus', 'text'));

        List<InformationRequest__c> informationRequests = [SELECT Id, Name, Status__c, AuthorityStatus__c,InformationRequestType__r.Name, FinancialProductFinServ__c, InformationRequestType__c, FinancialProductFinServ__r.Name FROM InformationRequest__c WHERE FinancialProductFinServ__r.Household__c =: recordId AND Status__c NOT IN ('Complete','Cancelled') ORDER BY Status__c ASC];
        String urlPrefix = URL.getOrgDomainURL().toExternalForm() + '/';
        Map<String,String> statusApiToLabelMap = getPicklistApiLabelMap();
        for( InformationRequest__c informationRequest : informationRequests ) {


            RowWrapper rowWrapper = new RowWrapper();
            rowWrapper.fields.add(new FieldWrapper('id', informationRequest.Id));
            rowWrapper.fields.add(new FieldWrapper('name', informationRequest.Name));
            rowWrapper.fields.add(new FieldWrapper('nameLink', urlPrefix+informationRequest.Id));
            rowWrapper.fields.add(new FieldWrapper('status', statusApiToLabelMap.get(informationRequest.Status__c)));
            rowWrapper.fields.add(new FieldWrapper('financialProduct', informationRequest.FinancialProductFinServ__r.Name));
            rowWrapper.fields.add(new FieldWrapper('financialProductLink', urlPrefix+informationRequest.FinancialProductFinServ__c));
            rowWrapper.fields.add(new FieldWrapper('type', informationRequest.InformationRequestType__r.Name));
            rowWrapper.fields.add(new FieldWrapper('authStatus', informationRequest.AuthorityStatus__c));

            dataWrapper.rows.add(rowWrapper);
    	}
        return dataWrapper;
    }

    // Get a map of picklist values to labels so that we can display the labels in the list
    private static Map<String,String> getPicklistApiLabelMap(){
        List<Schema.PicklistEntry> picklistItems = InformationRequest__c.Status__c.getDescribe().getPicklistValues();
        Map<String,String> picklistApiLabelMap = new Map<String,String>();
        For(Schema.PicklistEntry picklistItem : picklistItems){
            picklistApiLabelMap.put(picklistItem.getValue(), picklistItem.getLabel());
        }
        return picklistApiLabelMap; 
    }
}