force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/ProviderContact__c.field-meta.xml
<CustomField>
    <fullName>ProviderContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Link to provider</description>
    <label>Provider Contact</label>
    <referenceTo>ProviderContact__c</referenceTo>
    <relationshipLabel>Financial Products</relationshipLabel>
    <relationshipName>FinancialProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/InformationRequest__c.object-meta.xml
<CustomObject>
    <description>Used to track the process of gathering information for financial products</description>
    <label>Information Request</label>
    <nameField>
        <displayFormat>IR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Information Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformationRequest__c/fields/FinancialProductFinServ__c.field-meta.xml
<CustomField>
    <fullName>FinancialProductFinServ__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The financial product that this information request is for</description>
    <label>Financial product</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>InformationRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/ProviderContact__c.field-meta.xml
<CustomField>
    <fullName>ProviderContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The contact details for the third party provider of this product</description>
    <label>Provider contact</label>
    <referenceTo>ProviderContact__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>InformationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/ProviderSecret__c.field-meta.xml
<CustomField>
    <fullName>ProviderSecret__c</fullName>
    <description>Use this field to capture any information the provider has asked us to quote in relation to a particular product. For example, a PIN, policy reference etc.</description>
    <inlineHelpText>Use this field to capture any information the provider has asked us to quote in relation to a particular product. For example, a PIN, policy reference etc.</inlineHelpText>
    <label>Provider secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProviderContact__c/ProviderContact__c.object-meta.xml
<CustomObject>
    <description>Used to detail different departments within each provider and their contact details</description>
    <label>Provider Contact</label>
    <nameField>
        <label>Provider Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProviderContact__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Contact email of provider</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ProviderContact__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <description>Phone number of provider</description>
    <label>Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/InformationRequestContactDisplay.cls
public class InformationRequestContactDisplay {
    private final InformationRequest__c ir;
    public String callName{get;set;}
    public String callNumber{get;set;}
    public String callOutcomes{get;set;}
    public Boolean visibleButton{get;set;}
    public Boolean visibleJoint{get;set;}

    public InformationRequestContactDisplay() {
        System.debug(ApexPages.currentPage().getParameters().get('irId'));
        ir = [SELECT 
              	Id,
              	ProviderSecret__c,
              	ProviderContact__c,
             	ProviderContact__r.Telephone__c,
              	FinancialProductFinServ__r.FinServ__PrimaryOwner__c,
              	FinancialProductFinServ__r.FinServ__JointOwner__c
              FROM InformationRequest__c WHERE Id = :ApexPages.currentPage().getParameters().get('irId')];
        callNumber = ir.ProviderContact__r.Telephone__c;
        visibleButton = true;
        if( ir.FinancialProductFinServ__r.FinServ__JointOwner__c == null ) {
            visibleJoint = false;
        } else {
        	visibleJoint = true;
        }
    }

    public InformationRequest__c getInfoReq() {
        return ir;
    }
    
    public PageReference save() {
        update ir;
        return null;
    }
    
    public PageReference postToChatter() {
        FeedItem feed = new FeedItem();
		feed.ParentId =  ir.Id;
        String message = datetime.now().format('dd/MM/yy') + ' -- ' + callNumber + ' -- ' + callName + '   |   ' + callOutcomes;
        feed.body = message;
        insert feed;
		visibleButton = false;
        callName = '';
        callOutcomes ='';
        return null;
    }
    
    public Account getPrimaryOwner(){
        InformationRequest__c ir = getInfoReq();
        return [SELECT 
                Id, 
                Name,
                PersonBirthdate,
                National_Insurance_Number__pc,
                FinServ__ShippingAddress__pc
                FROM Account WHERE Id =: ir.FinancialProductFinServ__r.FinServ__PrimaryOwner__c
               ];    
    }
    public Account getJointOwner(){
        InformationRequest__c ir = getInfoReq();
        if( ir.FinancialProductFinServ__r.FinServ__JointOwner__c == null ) {
            visibleJoint = false;
            return null;
        } else {
        return [SELECT 
                Id,
                Name,
                PersonBirthdate,
                National_Insurance_Number__pc 
                FROM Account WHERE Id =: ir.FinancialProductFinServ__r.FinServ__JointOwner__c
                ];   
        }
    }
    public ProviderContact__c getProviderContact(){
        InformationRequest__c ir = getInfoReq();
        return [SELECT Id, Name, Email__c, Telephone__c FROM ProviderContact__c WHERE Id =: ir.ProviderContact__c];    
    }
    

}