force-app/main/default/objects/AdviceType__c/AdviceType__c.object-meta.xml
<CustomObject>
    <description>Models the types of advice that we provide to customers and how things vary between them. Used to drive business logic on actual advice.</description>
    <label>Advice Type</label>
    <nameField>
        <label>Advice Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AdviceTypeRecommendation__c/AdviceTypeRecommendation__c.object-meta.xml
<CustomObject>
    <description>Captures the types of recommendations that apply to a given advice type.</description>
    <label>Advice Type Recommendation</label>
    <nameField>
        <displayFormat>ATR-{00000}</displayFormat>
        <label>Advice Type Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advice Type Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdviceTypeRecommendation__c/fields/AdviceType__c.field-meta.xml
<CustomField>
    <fullName>AdviceType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The advice type that supports the recommendation type.</description>
    <label>Advice Type</label>
    <referenceTo>AdviceType__c</referenceTo>
    <relationshipLabel>Advice Type Recommendations</relationshipLabel>
    <relationshipName>AdviceTypeRecommendations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AdviceTypeRecommendation__c/fields/RecommendationType__c.field-meta.xml
<CustomField>
    <fullName>RecommendationType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The recommendation types that can be applied to the given advice type.</description>
    <label>Recommendation Type</label>
    <referenceTo>RecommendationType__c</referenceTo>
    <relationshipLabel>Advice Type Recommendations</relationshipLabel>
    <relationshipName>AdviceTypeRecommendations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AdviceTypeStatus__c/AdviceTypeStatus__c.object-meta.xml
<CustomObject>
    <description>A child of advice type, this retains information about how advice should be controlled at each status.</description>
    <label>Advice Type Status</label>
    <nameField>
        <label>Advice Type Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice Type Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdviceTypeStatus__c/fields/AdviceType__c.field-meta.xml
<CustomField>
    <fullName>AdviceType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The advice type this advice type status record relates to.</description>
    <label>Advice Type</label>
    <referenceTo>AdviceType__c</referenceTo>
    <relationshipLabel>Advice Type Statuses</relationshipLabel>
    <relationshipName>AdviceTypeStatuses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AssetType__c/AssetType__c.object-meta.xml
<CustomObject>
    <label>Asset Type</label>
    <nameField>
        <label>Asset type name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailConfiguration__c/EmailConfiguration__c.object-meta.xml
<CustomObject>
    <description>Holds the details of emails that is used to drive automation and business validation.</description>
    <label>Email Configuration</label>
    <nameField>
        <label>Email Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fact__c/Fact__c.object-meta.xml
<CustomObject>
    <label>Fact</label>
    <nameField>
        <label>Fact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fact__c/fields/FactCategory__c.field-meta.xml
<CustomField>
    <fullName>FactCategory__c</fullName>
    <description>Link to high level category</description>
    <label>Fact category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FactCategory__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FactCategory__c</referenceTo>
    <relationshipLabel>Facts</relationshipLabel>
    <relationshipName>MasterFacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FactCategory__c/FactCategory__c.object-meta.xml
<CustomObject>
    <label>Fact Category</label>
    <nameField>
        <label>Fact category name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fact Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FeeModel__c/FeeModel__c.object-meta.xml
<CustomObject>
    <description>Establishes what fields should be displayed for which fees</description>
    <label>Fee model</label>
    <nameField>
        <label>Fee model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FeeModel__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The kind of product that this fee model is related tp</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Fee models</relationshipLabel>
    <relationshipName>Fee_models</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FeeModel__c/fields/RecommendationType__c.field-meta.xml
<CustomField>
    <fullName>RecommendationType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation type that this fee model is related to</description>
    <label>Recommendation Type</label>
    <referenceTo>RecommendationType__c</referenceTo>
    <relationshipLabel>Fee models</relationshipLabel>
    <relationshipName>Fee_models</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinancialProductType__c/FinancialProductType__c.object-meta.xml
<CustomObject>
    <description>Used to indicate which fields are required for each type of product</description>
    <label>Financial Product Type</label>
    <nameField>
        <label>Product Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Product Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FulfilmentType__c/FulfilmentType__c.object-meta.xml
<CustomObject>
    <description>Used to store process specific information for each type of fulfilment</description>
    <label>Fulfilment Type</label>
    <nameField>
        <label>Fulfilment Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfilment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FulfilmentType__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The product that  this fulfilment type is associated with</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Fulfilment Types</relationshipLabel>
    <relationshipName>Fulfilment_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FulfilmentType__c/fields/RecommendationType__c.field-meta.xml
<CustomField>
    <fullName>RecommendationType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation type that this fulfilment type relates to</description>
    <label>Recommendation Type</label>
    <referenceTo>RecommendationType__c</referenceTo>
    <relationshipName>Fulfilment_types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FulfilmentTypeStatus__c/FulfilmentTypeStatus__c.object-meta.xml
<CustomObject>
    <description>A place to store specific process details for each stage for each type</description>
    <label>Fulfilment Type Status</label>
    <nameField>
        <label>Fulfilment Type Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfilment Type Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FulfilmentTypeStatus__c/fields/FulfilmentType__c.field-meta.xml
<CustomField>
    <fullName>FulfilmentType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The fulfilment type that this process point relates to</description>
    <label>Fulfilment type</label>
    <referenceTo>FulfilmentType__c</referenceTo>
    <relationshipLabel>Fulfilment Type Statuses</relationshipLabel>
    <relationshipName>FulfilmentTypeStatuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequestType__c/InformationRequestType__c.object-meta.xml
<CustomObject>
    <description>Used to specify process for different data gathering scenarios</description>
    <label>Information Request Type</label>
    <nameField>
        <label>Information Request Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Information Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LiabilityType__c/LiabilityType__c.object-meta.xml
<CustomObject>
    <description>Used to store types of liabilities you can have. Depending on the liability type, fields become required on the related liability.</description>
    <label>Liability Type</label>
    <nameField>
        <label>Liability type name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Liability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_task_information__c/OW_task_information__c.object-meta.xml
<CustomObject>
    <description>This object stores reference data related to tasks carried out by people across Octopus Wealth. In addition to a description of how to perform the task, there is useful information stored like which team performs it, whether the task is active, and which part of the process it falls under.</description>
    <label>Task Information</label>
    <nameField>
        <label>Task Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Will store the kinds of products we can provide in the post-cheerIO world.</description>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product category this falls under</description>
    <label>Product type</label>
    <referenceTo>ProductType__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductType__c/ProductType__c.object-meta.xml
<CustomObject>
    <description>Used to indicate which fields are relevant for the Product object</description>
    <label>Product type</label>
    <nameField>
        <label>Product type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Provider_Names__c/Public_Provider_Names__c.object-meta.xml
<CustomObject>
    <label>Public Provider List</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Provider List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecommendationType__c/RecommendationType__c.object-meta.xml
<CustomObject>
    <description>Object to control which fields are visible on recommendations, based on the kind of recommendation they are.</description>
    <label>Recommendation Type</label>
    <nameField>
        <label>Recommendation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommendation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataFactoryConfigurationData.cls
/**
 * This class can be used for test purposes only. 
 * It will load configuration data with the Test.loadData method.
 * The configuration data is loaded from static resource csv files for each object. 
 * This only supports the simpler configuration data objects without relationships right now. 
 * It should expanded to support the others once we can easily transform our files in config-data to the appropriate format as part of our CI/CD pipeline.
 */
public without sharing class DataFactoryConfigurationData {
    
    // The currently supported configuration data objects. 
    public static final List<String> VALID_CONFIG_DATA_TEST_OBJECTS = new List<String>{
        'AdviceType__c',
        'AdviceTypeStatus__c',
        'AssetType__c',
        'EmailConfiguration__c',
        'FactCategory__c',
        'InformationRequestType__c',
        'Public_Provider_Names__c',
        'RecommendationType__c',
        'LiabilityType__c'
    };

    // The method that loads the configuration data. This is somewhat messy at this stage but is being left to allow expansion. 
    public static void load() {
        List<sObject> configData01 = Test.loadData(AdviceType__c.sObjectType, 'AdviceType');
        List<sObject> configData04 = Test.loadData(AdviceTypeStatus__c.sObjectType, 'AdviceTypeStatus');
        List<sObject> configData05 = Test.loadData(AssetType__c.sObjectType, 'AssetType');
        List<sObject> configData06 = Test.loadData(EmailConfiguration__c.sObjectType, 'EmailConfiguration');
        List<sObject> configData08 = Test.loadData(FactCategory__c.sObjectType, 'FactCategory');
        List<sObject> configData13 = Test.loadData(InformationRequestType__c.sObjectType, 'InformationRequestType');
        List<sObject> configData16 = Test.loadData(Public_Provider_Names__c.sObjectType, 'Public_Provider_Names');
        List<sObject> configData17 = Test.loadData(RecommendationType__c.sObjectType, 'RecommendationType');
        List<sObject> configData18 = Test.loadData(LiabilityType__c.sObjectType, 'LiabilityType');
		
        // The following can be made to work bug the static resource files will need some work
        //List<sObject> configData02 = Test.loadData(OW_task_information__c.sObjectType, 'OW_task_information');
        //List<sObject> configData03 = Test.loadData(AdviceTypeRecommendation__c.sObjectType, 'AdviceTypeRecommendation');
        //List<sObject> configData07 = Test.loadData(Fact__c.sObjectType, 'Fact');
        //List<sObject> configData09 = Test.loadData(FeeModel__c.sObjectType, 'FeeModel');
        //List<sObject> configData10 = Test.loadData(FinancialProductType__c.sObjectType, 'FinancialProductType');
        //List<sObject> configData11 = Test.loadData(FulfilmentType__c.sObjectType, 'FulfilmentType');
        //List<sObject> configData12 = Test.loadData(FulfilmentTypeStatus__c.sObjectType, 'FulfilmentTypeStatus');
        //List<sObject> configData14 = Test.loadData(Product__c.sObjectType, 'Product');
        //List<sObject> configData15 = Test.loadData(ProductType__c.sObjectType, 'ProductType');
    }
}