force-app/main/default/objects/Fulfillment__c/Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Fulfilment</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfilment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fulfillment__c/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the recommendation that triggered this fulfilment</description>
    <label>Recommendation</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Fulfilment</relationshipLabel>
    <relationshipName>Fulfilment</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fulfillment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
                <default>true</default>
                <label>Setup</label>
            </value>
            <value>
                <fullName>Awaiting suitability outcome</fullName>
            </value>
            <value>
                <fullName>Not taken up</fullName>
            </value>
            <value>
                <fullName>On hold</fullName>
            </value>
            <value>
                <fullName>Submit forms</fullName>
            </value>
            <value>
                <fullName>Awaiting provider action</fullName>
            </value>
            <value>
                <fullName>Chasing transfer (within SLA)</fullName>
            </value>
            <value>
                <fullName>Chasing transfer (outside SLA)</fullName>
            </value>
            <value>
                <fullName>Awaiting client payment</fullName>
            </value>
            <value>
                <fullName>Processing Protection</fullName>
            </value>
            <value>
                <fullName>Investment Checks</fullName>
            </value>
            <value>
                <fullName>Finalise fulfilment</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Collect pre-requisites</fullName>
            </value>
            <value>
                <fullName>Submit fulfilment</fullName>
            </value>
            <value>
                <fullName>Chase transfer</fullName>
            </value>
            <value>
                <fullName>Chase client payment</fullName>
            </value>
            <value>
                <fullName>Await first regular</fullName>
            </value>
            <value>
                <fullName>Chase provider</fullName>
            </value>
            <value>
                <fullName>Replaced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfilment__c/Fulfilment__c.object-meta.xml
<CustomObject>
    <description>An object to store the progress of fulfilling recommendations</description>
    <label>Fulfilment</label>
    <nameField>
        <displayFormat>Flfl-{0000000}</displayFormat>
        <label>Fulfilment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment__c/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation which resulted in this fulfilment</description>
    <label>Recommendation</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fulfilment__c/fields/SearchName__c.field-meta.xml
<CustomField>
    <fullName>SearchName__c</fullName>
    <description>Human readable name for this fulfilment</description>
    <label>Search name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfilment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used to describe at what stage in the process this piece of fulfilment is in</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On hold</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Awaiting pre-requisites</fullName>
            </value>
            <value>
                <fullName>Awaiting ad hoc action</fullName>
            </value>
            <value>
                <fullName>Submit fulfilment</fullName>
            </value>
            <value>
                <fullName>Chase client payment</fullName>
            </value>
            <value>
                <fullName>Chase transfer</fullName>
            </value>
            <value>
                <fullName>Chase provider</fullName>
            </value>
            <value>
                <fullName>Chase client action</fullName>
            </value>
            <value>
                <fullName>Await first regular</fullName>
            </value>
            <value>
                <fullName>Investment checks</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting bank details</fullName>
                <isActive>false</isActive>
                <label>Awaiting bank details</label>
            </value>
            <value>
                <fullName>Awaiting client payment</fullName>
                <isActive>false</isActive>
                <label>Awaiting client payment</label>
            </value>
            <value>
                <fullName>Awaiting client signature</fullName>
                <isActive>false</isActive>
                <label>Awaiting client signature</label>
            </value>
            <value>
                <fullName>Awaiting form processing</fullName>
                <isActive>false</isActive>
                <label>Awaiting form processing</label>
            </value>
            <value>
                <fullName>Awaiting pre-requisite fulfilment</fullName>
                <isActive>false</isActive>
                <label>Awaiting pre-requisite fulfilment</label>
            </value>
            <value>
                <fullName>Awaiting transfer</fullName>
                <isActive>false</isActive>
                <label>Awaiting transfer</label>
            </value>
            <value>
                <fullName>Ready for submission</fullName>
                <isActive>false</isActive>
                <label>Ready for submission</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recommendation__c/Recommendation__c.object-meta.xml
<CustomObject>
    <description>Contains all the information given by planners when making a recommendation of an action for a change in a clients financial circumstances.</description>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>Rec-{0000000}</displayFormat>
        <label>Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount tied to a recommendation such as the lump sum, regular deposit or expected value of a transfer.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/DestinationLegacy__c.field-meta.xml
<CustomField>
    <fullName>DestinationLegacy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account which is receiving funds or undergoing a change</description>
    <label>Destination</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/FulfilmentLegacy__c.field-meta.xml
<CustomField>
    <fullName>FulfilmentLegacy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Unused
The related fulfilment used to carry out this recommendation. Filled automatically when fulfilment is created</description>
    <label>Fulfilment</label>
    <referenceTo>Fulfillment__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Recommendation__c/fields/PreRequisiteRecommendation__c.field-meta.xml
<CustomField>
    <fullName>PreRequisiteRecommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the recommendation which must be completed before this one can be done</description>
    <label>Pre-requisite recommendation destination</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The progress of the recommendation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Awaiting decision</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In place</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ringfence__c/Ringfence__c.object-meta.xml
<CustomObject>
    <description>Used to record when ringfences have been applied against a financial product, in the context of fulfilment.</description>
    <label>Ringfence</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Ringfence Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ringfences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ringfence__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of ringfence applied to this financial product specifically in relation to this fulfilment.</description>
    <inlineHelpText>The amount of ringfence applied to this financial product specifically in relation to this fulfilment.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ringfence__c/fields/Fulfilment__c.field-meta.xml
<CustomField>
    <fullName>Fulfilment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The fulfilment that required this ringfence.</description>
    <label>Fulfilment</label>
    <referenceTo>Fulfilment__c</referenceTo>
    <relationshipLabel>Ringfences</relationshipLabel>
    <relationshipName>Ringfences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ringfence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of this specific ringfence.</description>
    <inlineHelpText>Indicates the status of this specific ringfence.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LwcHelperFinProdRelatedRingfences.cls
public class LwcHelperFinProdRelatedRingfences {

    public static LwcHelperDynamicRecordList.DataWrapper getRingfences(Id recordId) {
        LwcHelperDynamicRecordList.DataWrapper dataWrapper = new LwcHelperDynamicRecordList.DataWrapper();
        dataWrapper.config.keyFieldName = 'id';
        
        LwcHelperDynamicRecordList.ColumnWrapper nameLinkColumn = new LwcHelperDynamicRecordList.ColumnWrapper('Name', 'nameLink', 'url');
    	nameLinkColumn.typeAttributes.label.put('fieldName', 'name');
        dataWrapper.columns.add(nameLinkColumn);    
        
        LwcHelperDynamicRecordList.ColumnWrapper fulfilmentLinkColumn = new LwcHelperDynamicRecordList.ColumnWrapper('Fulfilment', 'fulfilmentLink', 'url');
        fulfilmentLinkColumn.typeAttributes.label.put('fieldName', 'fulfilment');
        dataWrapper.columns.add(fulfilmentLinkColumn); 
        
        dataWrapper.columns.add(new LwcHelperDynamicRecordList.ColumnWrapper('Status', 'status', 'text'));
        
        LwcHelperDynamicRecordList.ColumnWrapper amountColumn = new LwcHelperDynamicRecordList.ColumnWrapper('Amount', 'amount', 'currency');
        amountColumn.typeAttributes.currencyCode = 'GBP';
        dataWrapper.columns.add(amountColumn); 
        
        
        List<Ringfence__c> ringfences = [SELECT 
                                         Id, 
                                         Name, 
                                         Amount__c, 
                                         Status__c, 
                                         Fulfilment__c,
                                         Fulfilment__r.SearchName__c
                                         FROM 
                                         Ringfence__c 
                                         WHERE 
                                         Fulfilment__r.Recommendation__r.DestinationLegacy__c =: recordId 
                                         ORDER BY Status__c, Fulfilment__c ASC
                                        ];
        
        String urlPrefix = URL.getOrgDomainURL().toExternalForm() + '/';
        Map<String,String> statusApiToLabelMap = Utility.getPicklistApiLabelMap('Ringfence__c','Status__c');
        
        for( Ringfence__c ringfence : ringfences ) {
            
            LwcHelperDynamicRecordList.RowWrapper rowWrapper = new LwcHelperDynamicRecordList.RowWrapper();
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('name', ringfence.Name));
        	rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('nameLink', urlPrefix+ringfence.Id));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('id', ringfence.Id));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('amount', ringfence.Amount__c.toString()));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('status', statusApiToLabelMap.get(ringfence.Status__c)));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('fulfilment', ringfence.Fulfilment__r.SearchName__c));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('fulfilmentLink', urlPrefix+ringfence.Fulfilment__c));

            
            dataWrapper.rows.add(rowWrapper);
        }
        return dataWrapper;
    }
    



}