force-app/main/default/objects/CustomerFact__c/CustomerFact__c.object-meta.xml
<CustomObject>
    <label>Customer Fact</label>
    <nameField>
        <label>Customer fact name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Facts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerFact__c/fields/Fact__c.field-meta.xml
<CustomField>
    <fullName>Fact__c</fullName>
    <description>Link to fact</description>
    <label>Fact</label>
    <referenceTo>Fact__c</referenceTo>
    <relationshipLabel>Customer Facts</relationshipLabel>
    <relationshipName>Facts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/FactCategory__c.field-meta.xml
<CustomField>
    <fullName>FactCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to fact category (unused)</description>
    <label>Fact category</label>
    <referenceTo>FactCategory__c</referenceTo>
    <relationshipLabel>Customer Facts</relationshipLabel>
    <relationshipName>Facts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Facts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Free text notes to record further detail on a fact</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Facts (Person)</relationshipLabel>
    <relationshipName>CustomerFactsPerson</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates if fact is active or not</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fact__c/Fact__c.object-meta.xml
<CustomObject>
    <label>Fact</label>
    <nameField>
        <label>Fact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fact__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Managed by product team, displays to user when creating facts.</description>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Fact__c/fields/FactCategory__c.field-meta.xml
<CustomField>
    <fullName>FactCategory__c</fullName>
    <description>Link to high level category</description>
    <label>Fact category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FactCategory__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FactCategory__c</referenceTo>
    <relationshipLabel>Facts</relationshipLabel>
    <relationshipName>MasterFacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FactCategory__c/FactCategory__c.object-meta.xml
<CustomObject>
    <label>Fact Category</label>
    <nameField>
        <label>Fact category name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fact Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FactCategory__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of fact category</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FactCategory__c/fields/Enum__c.field-meta.xml
<CustomField>
    <fullName>Enum__c</fullName>
    <description>Unique identifier of fact category</description>
    <label>Enum</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FactCategory__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of fact category</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/LwcHelperCustomerFactsListTest.cls
/* Test class to support LwcHelperCustomerFactsList 
 * Create a fact category, fact and customer fact linked to household and ensure it appears on the manage facts data table
 */
@isTest
public with sharing class LwcHelperCustomerFactsListTest {
    @isTest
    static void createList(){
        List<Account> testAccounts = TestDataFactory.createHousehold(2,0,'1239');
        Id hhRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
        Id personRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        Account household = [SELECT Id, Name, AccountNumber FROM Account WHERE Id IN: testAccounts AND RecordTypeId =: hhRT LIMIT 1];
        Account person = [SELECT Id, Name, AccountNumber FROM Account WHERE Id IN: testAccounts AND RecordTypeId =: personRT LIMIT 1];
        
        FactCategory__c factCat = new FactCategory__c();
        factCat.Name = 'Objectives';
        factCat.Enum__c = 'OBJECTIVES';
        insert factCat;
        
        Fact__c fact = new Fact__c();
        fact.Name = 'General review';
        fact.Description__c = 'Add this fact if the client would like to see how their finances are performing and where we can improve things. E.g. asset performance, weighting of product types';
        fact.FactCategory__c = factCat.Id;
        insert fact;
        
        
        CustomerFact__c custFact = new CustomerFact__c();
        custFact.Fact__c = fact.Id;
        custFact.Name = fact.Name;
        custFact.Household__c = household.Id;
        custFact.Person__c = person.Id;
        custFact.Status__c = 'Active';
        custFact.Notes__c = 'General review';
        insert custFact;
        
        LwcHelperDynamicRecordList.configWrapper config = new LwcHelperDynamicRecordList.configWrapper();
        config.keyFieldName = 'factId';
        LwcHelperDynamicRecordList.DataWrapper data = LwcHelperCustomerFactsList.getCustomerFactData(household.Id);
        System.Assert.areEqual(1, data.rows.size(), 'Expected 1 row');
        
    }    
}