force-app/main/default/objects/CustomerFact__c/CustomerFact__c.object-meta.xml
<CustomObject>
    <label>Customer Fact</label>
    <nameField>
        <label>Customer fact name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Facts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerFact__c/fields/Fact__c.field-meta.xml
<CustomField>
    <fullName>Fact__c</fullName>
    <description>Link to fact</description>
    <label>Fact</label>
    <referenceTo>Fact__c</referenceTo>
    <relationshipLabel>Customer Facts</relationshipLabel>
    <relationshipName>Facts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/FactCategoryName__c.field-meta.xml
<CustomField>
    <fullName>FactCategoryName__c</fullName>
    <description>Used to display the fact category name using the fact relationship</description>
    <formula>Fact__r.FactCategory__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fact category name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Facts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Free text notes to record further detail on a fact</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates if fact is active or not</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fact__c/Fact__c.object-meta.xml
<CustomObject>
    <label>Fact</label>
    <nameField>
        <label>Fact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LwcHelperCustomerFactsList.cls
/* This class exists exclusively to get active customer facts to display for a given household
 * From a given household ID, this class gets all active customer facts and constructs a table to display them
 */
public with sharing class LwcHelperCustomerFactsList {
    public static LwcHelperDynamicRecordList.DataWrapper getCustomerFactData(Id contextId) {
        LwcHelperDynamicRecordList.DataWrapper dataWrapper = new LwcHelperDynamicRecordList.DataWrapper();
        dataWrapper.config.keyFieldName = 'factId';

        //define columns
        LwcHelperDynamicRecordList.ColumnWrapper factNameLink = new LwcHelperDynamicRecordList.ColumnWrapper('Fact', 'Id', 'url');
        factNameLink.typeAttributes.label.put('fieldName', 'Name');

        dataWrapper.columns.add(factNameLink);
        dataWrapper.columns.add(new LwcHelperDynamicRecordList.ColumnWrapper('Category', 'FactCategoryName__c', 'text'));
        dataWrapper.columns.add(new LwcHelperDynamicRecordList.ColumnWrapper('Notes', 'Notes__c', 'text'));
        dataWrapper.columns.add(new LwcHelperDynamicRecordList.ColumnWrapper('Last modified date', 'LastModifiedDate', 'date'));

        List<CustomerFact__c> customerFacts = [SELECT Id, Name, Fact__c, FactCategoryName__c, Household__c, Notes__c, LastModifiedDate FROM CustomerFact__c WHERE  Household__c =: contextId AND Status__c = 'Active' ORDER BY FactCategoryName__c];
        String urlPrefix = URL.getOrgDomainURL().toExternalForm() + '/';

        for(CustomerFact__c cf : customerFacts) {
            LwcHelperDynamicRecordList.RowWrapper rowWrapper = new LwcHelperDynamicRecordList.RowWrapper();
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('factId', cf.Id));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('FactCategoryName__c', cf.FactCategoryName__c));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('Id', urlPrefix + cf.Id));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('Name', cf.Name));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('Notes__c', cf.Notes__c));
            rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('LastModifiedDate', cf.LastModifiedDate.toString()));
            dataWrapper.rows.add(rowWrapper);
        }
        return dataWrapper;
    }
}