force-app/main/default/objects/Licence__c/Licence__c.object-meta.xml
<CustomObject>
    <description>Describes a permission that we can assign to a user.</description>
    <label>Licence</label>
    <nameField>
        <label>Licence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique reference name for this object</description>
    <label>Developer name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UserLicence__c/UserLicence__c.object-meta.xml
<CustomObject>
    <description>Used to record which users have access to which licences</description>
    <label>User Licence</label>
    <nameField>
        <displayFormat>UL-{000000}</displayFormat>
        <label>User Licence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Licences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserLicence__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the assignment of this user to this licence is currently active</description>
    <inlineHelpText>Indicates whether the assignment of this user to this licence is currently active</inlineHelpText>
    <label>Is active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserLicence__c/fields/Licence__c.field-meta.xml
<CustomField>
    <fullName>Licence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The licence being assigned to this user</description>
    <label>Licence</label>
    <referenceTo>Licence__c</referenceTo>
    <relationshipLabel>User Licences</relationshipLabel>
    <relationshipName>UserLicences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserLicence__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user with the licence being assigned</description>
    <inlineHelpText>The user with the licence being assigned</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserLicences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LicenceTest.cls
@IsTest
public class LicenceTest {

    @TestVisible private static final List<String> USERNAMES = new List<String>{'licencedcolleague1@test.novawm.com', 'licencedcolleague2@test.novawm.com', 'licencedcolleague3@test.novawm.com'};
    @TestVisible private static final String LICENCE_DEVELOPER_NAME = 'ADVICE_WRITE_TOP_UP';
    
    @TestSetup
    static void setupData(){
        setUpLicenceTestData();
    }

    public static void setUpLicenceTestData(){
        List<User> licencedColleagues = DataFactoryUser.createColleagues(usernames);
        Licence__c licence = new Licence__c(
            Name = 'Test licence',
            DeveloperName__c = LICENCE_DEVELOPER_NAME,
            Type__c = 'ADVICE_WRITE',
            Reference__c = 'TOP_UP'
        );
        insert licence;

        List<UserLicence__c> userLicences = new List<UserLicence__c>();
        for(User licencedColleague : licencedColleagues){
            UserLicence__c userLicence = new UserLicence__c(
                User__c = licencedColleague.Id,
                Licence__c = licence.Id,
                IsActive__c = true
            );
            userLicences.add(userLicence);
        }
        insert userLicences;
    }


    

    @IsTest
    static void getLicencedUsers_success(){
        List<User> licencedUsers = Licence.getLicencedUsers(LICENCE_DEVELOPER_NAME);
        for(User licencedUser : licencedUsers){
            System.assert(USERNAMES.contains(licencedUser.Username));
        }
        System.assertEquals(USERNAMES.size(), licencedUsers.size(), 'Unexpected number of licenced users');
    }

    @IsTest
    static void getLicencedUsersExcludesInactiveUser_success(){
        List<User> licencedUsers = [SELECT Id, IsActive FROM User WHERE Username IN :USERNAMES];
        for(User licencedUser : licencedUsers){
            licencedUser.IsActive = false;
        }
        update licencedUsers;
        
        licencedUsers = Licence.getLicencedUsers(LICENCE_DEVELOPER_NAME);
        System.assertEquals(0, licencedUsers.size(), 'Expected 0 licenced users');
    }

    @IsTest
    static void getLicencedUsersExcludesInactiveLicences_success(){
        List<UserLicence__c> userLicences = [SELECT Id, IsActive__c FROM UserLicence__c];
        for(UserLicence__c userLicence : userLicences){
            userLicence.IsActive__c = false;
        }
        update userLicences;
        
        List<User> licencedUsers = Licence.getLicencedUsers(LICENCE_DEVELOPER_NAME);
        System.assertEquals(0, licencedUsers.size(), 'Expected 0 licenced users');
    }
}