force-app/main/default/objects/Licence__c/Licence__c.object-meta.xml
<CustomObject>
    <description>Describes a permission that we can assign to a user.</description>
    <label>Licence</label>
    <nameField>
        <label>Licence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Licence__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique reference name for this object</description>
    <label>Developer name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UserLicence__c/UserLicence__c.object-meta.xml
<CustomObject>
    <description>Used to record which users have access to which licences</description>
    <label>User Licence</label>
    <nameField>
        <displayFormat>UL-{000000}</displayFormat>
        <label>User Licence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Licences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserLicence__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the assignment of this user to this licence is currently active</description>
    <inlineHelpText>Indicates whether the assignment of this user to this licence is currently active</inlineHelpText>
    <label>Is active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserLicence__c/fields/Licence__c.field-meta.xml
<CustomField>
    <fullName>Licence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The licence being assigned to this user</description>
    <label>Licence</label>
    <referenceTo>Licence__c</referenceTo>
    <relationshipLabel>User Licences</relationshipLabel>
    <relationshipName>UserLicences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserLicence__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user with the licence being assigned</description>
    <inlineHelpText>The user with the licence being assigned</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserLicences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Licence.cls
/**
 * This class handles logic for returning users who are licensed. 
 * It should be expanded in time to handle other scenarios and support licensing use cases, like finding unlicensed users, adding and removing licences etc. 
 */
public without sharing class Licence {

    // Get all users for a single licence
    public static List<User> getLicensedUsers(String licenceDeveloperName){
        Set<String> licenceDeveloperNames = new Set<String>{licenceDeveloperName};
        Map<String, List<User>> usersByLicence = getLicensedUsers(licenceDeveloperNames);
        return usersByLicence.get(licenceDeveloperName);
    }

    // Get all users for a collection of licences
    public static Map<String, List<User>> getLicensedUsers(Set<String> licenceDeveloperNames){
        Map<String, List<User>> usersByLicence = new Map<String, List<User>>();
        for(String licenceDeveloperName : licenceDeveloperNames){
            usersByLicence.put(licenceDeveloperName, new List<User>());
        }
        List<User> users = [SELECT Id, FirstName, LastName, Name, Email, UserName, (SELECT Licence__r.DeveloperName__c FROM UserLicences__r WHERE IsActive__c = true AND Licence__r.DeveloperName__c IN :licenceDeveloperNames) FROM User WHERE IsActive = true AND Id IN (SELECT User__c FROM UserLicence__c WHERE Licence__r.DeveloperName__c IN :licenceDeveloperNames AND IsActive__c = true) ORDER BY FirstName ASC];
        for(User user : users){
            for(UserLicence__c userLicence : user.UserLicences__r){
                usersByLicence.get(userLicence.Licence__r.DeveloperName__c).add(user);
            }
        }
        return usersByLicence;
    }
}