force-app/main/default/objects/Fulfilment__c/Fulfilment__c.object-meta.xml
<CustomObject>
    <description>An object to store the progress of fulfilling recommendations</description>
    <label>Fulfilment</label>
    <nameField>
        <displayFormat>Flfl-{0000000}</displayFormat>
        <label>Fulfilment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment__c/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation which resulted in this fulfilment</description>
    <label>Recommendation</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Will store the kinds of products we can provide in the post-cheerIO world.</description>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/Recommendation__c.object-meta.xml
<CustomObject>
    <description>Contains all the information given by planners when making a recommendation of an action for a change in a clients financial circumstances.</description>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>Rec-{0000000}</displayFormat>
        <label>Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The household to which this recommendation is being made.</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Recommendation__c/fields/PreRequisiteRecommendation__c.field-meta.xml
<CustomField>
    <fullName>PreRequisiteRecommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the recommendation which must be completed before this one can be done</description>
    <label>Pre-requisite recommendation destination</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>PrimaryOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the main client that this recommendation relates to, the primary owner of the destination product</description>
    <label>Primary owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation (Primary owner)</relationshipLabel>
    <relationshipName>Recommendation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of product this recommendation relates to. Likely only used for open product recommendations</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/RegisteredContact__c.field-meta.xml
<CustomField>
    <fullName>RegisteredContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The adult associated with this junior account</description>
    <inlineHelpText>The adult associated with this junior account</inlineHelpText>
    <label>Registered contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation (Registered contact)</relationshipLabel>
    <relationshipName>Recommendation4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailCancellationNoticeNewProduct.cls
public class EmailCancellationNoticeNewProduct {
    
    public String objectId {get;set;}
    private static Fulfilment__c fulfilment;
    
    // Constructor to set the fulfilment record
    public static Map<String, String> getParameters(Fulfilment__c fulfilmentInput) {
        fulfilment = fulfilmentInput;
        Map<String, String> parameters = new Map<String, String>();
        parameters.put('{{hiLine}}','Hi Bobbbbb');
        parameters.put('{{clientName}}', clientName);
        parameters.put('{{productName}}', productName);
        parameters.put('{{dateTodayString}}', dateString);
        return parameters;
    }
    
    private static String clientName {
        get{ 
            String result = '';
            if( fulfilment.Recommendation__r.RegisteredContact__c == null) {
                result = result + 'your ';
            } else {
                result = result + fulfilment.Recommendation__r.PrimaryOwner__r.AddressedName__pc + '\'s ';
            }
            return result;
        }
    }
    
    private static String productName{
        get{
            return fulfilment.Recommendation__r.Product__r.Name ;
        }
    }
    
    private static String dateString{
        get{
            UtilityString us = new UtilityString();
            return us.formatDateForNovaEmail(Datetime.now());
        }
    }

    public static String getSubject(Fulfilment__c fulfilment){
        String subject = 'Your new SIPP';
        return subject;
    }
    
    public class EmailCancellationNoticeNewProductException extends Exception {}
}