force-app/main/default/objects/Fulfilment__c/Fulfilment__c.object-meta.xml
<CustomObject>
    <description>An object to store the progress of fulfilling recommendations</description>
    <label>Fulfilment</label>
    <nameField>
        <displayFormat>Flfl-{0000000}</displayFormat>
        <label>Fulfilment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used to describe at what stage in the process this piece of fulfilment is in</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On hold</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Awaiting pre-requisites</fullName>
            </value>
            <value>
                <fullName>Awaiting ad hoc action</fullName>
            </value>
            <value>
                <fullName>Submit fulfilment</fullName>
            </value>
            <value>
                <fullName>Chase client payment</fullName>
            </value>
            <value>
                <fullName>Chase transfer</fullName>
            </value>
            <value>
                <fullName>Chase provider</fullName>
            </value>
            <value>
                <fullName>Chase client action</fullName>
            </value>
            <value>
                <fullName>Await first regular</fullName>
            </value>
            <value>
                <fullName>Investment checks</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting bank details</fullName>
                <isActive>false</isActive>
                <label>Awaiting bank details</label>
            </value>
            <value>
                <fullName>Awaiting client payment</fullName>
                <isActive>false</isActive>
                <label>Awaiting client payment</label>
            </value>
            <value>
                <fullName>Awaiting client signature</fullName>
                <isActive>false</isActive>
                <label>Awaiting client signature</label>
            </value>
            <value>
                <fullName>Awaiting form processing</fullName>
                <isActive>false</isActive>
                <label>Awaiting form processing</label>
            </value>
            <value>
                <fullName>Awaiting pre-requisite fulfilment</fullName>
                <isActive>false</isActive>
                <label>Awaiting pre-requisite fulfilment</label>
            </value>
            <value>
                <fullName>Awaiting transfer</fullName>
                <isActive>false</isActive>
                <label>Awaiting transfer</label>
            </value>
            <value>
                <fullName>Ready for submission</fullName>
                <isActive>false</isActive>
                <label>Ready for submission</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FulfilmentTriggerHelperTest.cls
@isTest(SeeAllData=true)
public class FulfilmentTriggerHelperTest {
    @istest
    static void runTest(){
        Fulfilment__c testFulfil = [SELECT Id FROM Fulfilment__c WHERE Id = 'a2iQz00000247JVIAY'][0];

		testFulfil.Status__c = 'Investment checks';
		update testFulfil;
        testFulfil.Status__c = 'Complete';
        update testFulfil;
        
        Integer emailsSent = Limits.getEmailInvocations();
        System.assertEquals(2, emailsSent, 'Expected 2 emails but not true');
    }

}