force-app/main/default/objects/Account/fields/Annual_Review_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review_Schedule__c</fullName>
    <defaultValue>&quot;Scheduled&quot;</defaultValue>
    <description>Picklist for whether the annual review is scheduled or outstanding</description>
    <label>Annual review schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/BankDetailsStatus__c.field-meta.xml
<CustomField>
    <fullName>BankDetailsStatus__c</fullName>
    <defaultValue>&quot;Hidden&quot;</defaultValue>
    <description>The status of this clients bank details</description>
    <label>Bank details status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting replacement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Colleague__c.field-meta.xml
<CustomField>
    <fullName>Colleague__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colleague</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fact_Find_Type__c.field-meta.xml
<CustomField>
    <fullName>Fact_Find_Type__c</fullName>
    <defaultValue>&quot;Discovery&quot;</defaultValue>
    <inlineHelpText>This field toggles what version of the fact find the client sees in the portal</inlineHelpText>
    <label>Profile Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discovery</fullName>
                <default>true</default>
                <label>Discovery</label>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Verifying</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Reported Deceased</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To be classified</fullName>
            </value>
            <value>
                <fullName>Forgotten</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MigrationGiving__c.field-meta.xml
<CustomField>
    <fullName>MigrationGiving__c</fullName>
    <description>Field indicating review of giving value in migration</description>
    <label>Migration giving</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No action</fullName>
                <default>true</default>
                <label>No action</label>
            </value>
            <value>
                <fullName>Review needed</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Reviewed with Jemma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MigrationSpendingSaving__c.field-meta.xml
<CustomField>
    <fullName>MigrationSpendingSaving__c</fullName>
    <label>MigrationSpendingSaving</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No action</fullName>
                <default>true</default>
                <label>No action</label>
            </value>
            <value>
                <fullName>Review needed</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/OW_aml_check_account__c.field-meta.xml
<CustomField>
    <fullName>OW_aml_check_account__c</fullName>
    <description>The status of the AML check. Applies to people only.</description>
    <inlineHelpText>Indicates if the person has passed AML via the new process using Experian, WC1, and managed in Salesforce. If  incomplete, they may still have passed AML but via the old process and you should look at the KYC status field.</inlineHelpText>
    <label>AML status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/OW_rtq_status__c.field-meta.xml
<CustomField>
    <fullName>OW_rtq_status__c</fullName>
    <description>Hold the status of the household or customer with regards to risk tolerance. This is used to drive automation and validation in relation to RTQs.</description>
    <label>RTQ status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OW_terms_of_Business_Status__c.field-meta.xml
<CustomField>
    <fullName>OW_terms_of_Business_Status__c</fullName>
    <description>The status of Terms of Business records which are to be signed by a customer. Applies to people only.</description>
    <label>Terms of business status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ColleagueAccountId__c.field-meta.xml
<CustomField>
    <fullName>ColleagueAccountId__c</fullName>
    <description>This field will store the ID of the user&apos;s colleague account. This will be used by Cognito and passed through to it in the connected app.</description>
    <label>Colleague account ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/UserType__c.field-meta.xml
<CustomField>
    <fullName>UserType__c</fullName>
    <description>User type attribute is used to control business logic relating to users like whether there should be an associated colleague account.</description>
    <label>User type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>COLLEAGUE</fullName>
                <label>Colleague</label>
            </value>
            <value>
                <fullName>CONSULTANT</fullName>
                <label>Consultant</label>
            </value>
            <value>
                <fullName>INTEGRATION</fullName>
                <label>Integration</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/UserEvent__e/UserEvent__e.object-meta.xml
<CustomObject>
    <description>Used to publish changes to users.</description>
    <label>User Event</label>
    <pluralLabel>User Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/UserEvent__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Stores the Salesforce ID of the user.</description>
    <label>User ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserEventTriggerHelper.cls
public with sharing class UserEventTriggerHelper {

    @TestVisible private static final String COLLEAGUE_ACCOUNT_RECORD_TYPE_DEVELOPER_NAME = 'Colleague';
    @TestVisible private static final String COLLEAGUE_ACCOUNT_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Colleague').getRecordTypeId();
    @TestVisible private static final String NOVA_USER_TYPE_COLLEAGUE = 'COLLEAGUE';

    // The purpose of this method is to process user events and run any logic required for the given users.
    public void processUserEvents(List<UserEvent__e> userEvents){
        System.debug('uysdfasdfadsas');

        // Build a list of the user IDs from the events
        Set<Id> userIds = new Set<Id>();
        for(UserEvent__e userEvent : userEvents){
            userIds.add(userEvent.UserId__c);
        }

        // Given the user IDs from the events, retrieve all users that should have colleague accounts. 
        Map<Id, User> userMap = new Map<Id, User>([SELECT Id, FirstName, LastName, Username, ColleagueAccountId__c FROM User WHERE Id IN :userIds AND UserType__c = :NOVA_USER_TYPE_COLLEAGUE AND IsActive = True]);
        /*
        TBC if any of this is needed. This is if we want to run checks on existing accounts 1st. 
        List<Account> colleagueAccountsExisting = [SELECT Id, FirstName, LastName FROM Account WHERE RecordTypeId = :COLLEAGUE_ACCOUNT_RECORD_TYPE_ID AND Colleague__c IN :userIds];
        Map<Id, Account> userColleagueAccountMap = new Map<Id, Account>();
        for(Account colleagueAccount : colleagueAccountsExisting){
            userColleagueAccountMap.put(colleagueAccount.Colleague__c, colleagueAccount);
        }
        */

        // Loop the users and build a list of colleague accounts to upsert
        List<Account> colleagueAccounts = new List<Account>();
        for(User user : userMap.values()){
            // Define a colleague account variable for the current user. This will be used either to create or update/sync the account if existing. 
            Account colleagueAccount = new Account(
                RecordTypeId = COLLEAGUE_ACCOUNT_RECORD_TYPE_ID,
                OwnerId = user.Id,
                Colleague__c = user.Id,
                Type = NOVA_USER_TYPE_COLLEAGUE,
                FirstName = user.FirstName,
                LastName = user.LastName,
                PersonEmail = user.Username,
                ServiceContactPreferences__pc = '',
                Fact_Find_Type__c = '',
                BankDetailsStatus__c = '',
                OW_aml_check_account__c = '',
                OW_rtq_status__c = '',
                Wealth_Marketing_Opt_In__pc = '',
                MigrationGiving__c = '',
                MigrationSpendingSaving__c = '',
                OW_terms_of_Business_Status__c = '',
                FinServ__Status__c = '',
                Annual_Review_Schedule__c =''
            );

            // If we already have a colleague account, define the ID so we update that.
            if(!String.isBlank(user.ColleagueAccountId__c)){
                colleagueAccount.Id = user.ColleagueAccountId__c;
            }
            colleagueAccounts.add(colleagueAccount);
        }

        // If there are colleague accounts requiring upsert, do that. 
        if(!colleagueAccounts.isEmpty()){
            upsert colleagueAccounts;
        }

        // Identify any of the users that will need a ColleagueAccountId__c value and fire these off
        List<User> users = new List<User>();
        for(Account colleagueAccount : colleagueAccounts){
            if(String.isBlank(userMap.get(colleagueAccount.Colleague__c).ColleagueAccountId__c)){
                users.add(new User(Id = colleagueAccount.Colleague__c, ColleagueAccountId__c = colleagueAccount.Id));
            }
        }
        if(!users.isEmpty()){
            update users;
        }
    }
}