force-app/main/default/objects/Account/fields/ConflictOfInterest__c.field-meta.xml
<CustomField>
    <fullName>ConflictOfInterest__c</fullName>
    <label>Conflict of Interest?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DateConflictOfInterestAssessed__c.field-meta.xml
<CustomField>
    <fullName>DateConflictOfInterestAssessed__c</fullName>
    <description>Date the conflict of interest was assessed.</description>
    <label>Date conflict of interest assessed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/CustomerFact__c.object-meta.xml
<CustomObject>
    <label>Customer Fact</label>
    <nameField>
        <label>Customer fact name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Facts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerFact__c/fields/Fact__c.field-meta.xml
<CustomField>
    <fullName>Fact__c</fullName>
    <description>Link to fact</description>
    <label>Fact</label>
    <referenceTo>Fact__c</referenceTo>
    <relationshipLabel>Customer Facts</relationshipLabel>
    <relationshipName>Facts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/FactCategory__c.field-meta.xml
<CustomField>
    <fullName>FactCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to fact category (unused)</description>
    <label>Fact category</label>
    <referenceTo>FactCategory__c</referenceTo>
    <relationshipLabel>Customer Facts</relationshipLabel>
    <relationshipName>Facts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Facts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Free text notes to record further detail on a fact</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerFact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates if fact is active or not</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fact__c/Fact__c.object-meta.xml
<CustomObject>
    <label>Fact</label>
    <nameField>
        <label>Fact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fact__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Managed by product team, displays to user when creating facts.</description>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Fact__c/fields/FactCategory__c.field-meta.xml
<CustomField>
    <fullName>FactCategory__c</fullName>
    <description>Link to high level category</description>
    <label>Fact category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FactCategory__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FactCategory__c</referenceTo>
    <relationshipLabel>Facts</relationshipLabel>
    <relationshipName>MasterFacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FactCategory__c/FactCategory__c.object-meta.xml
<CustomObject>
    <label>Fact Category</label>
    <nameField>
        <label>Fact category name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fact Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FactCategory__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of fact category</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FactCategory__c/fields/Enum__c.field-meta.xml
<CustomField>
    <fullName>Enum__c</fullName>
    <description>Unique identifier of fact category</description>
    <label>Enum</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FactCategory__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of fact category</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/CustomerFactConflictEvaluationTest.cls
@isTest
public class CustomerFactConflictEvaluationTest {
    
    @testSetup
    static void testSetup(){
        List<Account> testAccounts = TestDataFactory.createHousehold(2,0,'1235');
        Id hhRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
        Id personRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        Account household = [SELECT Id, Name, AccountNumber FROM Account WHERE Id IN: testAccounts AND RecordTypeId =: hhRT LIMIT 1];
        Account person = [SELECT Id, Name, AccountNumber FROM Account WHERE Id IN: testAccounts AND RecordTypeId =: personRT LIMIT 1];
    
        FactCategory__c coiFC = new FactCategory__c();
        coiFC.Name = 'Conflict of interest';
        coiFC.Enum__c = 'CONFLICT_OF_INTEREST';
        insert coiFC;
        
        Fact__c coiFact = new Fact__c();
        coiFact.Name = 'Friend';
        coiFact.Description__c = 'Add if this person is vulnerable as a result of someone close to them going through an illness we should be aware of';
        coiFact.FactCategory__c = coiFC.Id;
        insert coiFact;
        
        CustomerFact__c coiCF = new CustomerFact__c();
        coiCF.Fact__c = coiFact.Id;
        coiCF.Household__c = household.Id;
        coiCF.Notes__c = 'Mate of mine';
        coiCF.Status__c = 'Active';
        insert coiCF;
    }
    
    @isTest
    static void conflictTestMethod(){
        
        List<Account> testAccounts = new List<Account>();
        Id hhRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
        Account household = [SELECT Id, Name, ConflictOfInterest__c, IsPersonAccount, DateConflictOfInterestAssessed__c FROM Account WHERE AccountNumber = '1235' LIMIT 1];
        testAccounts.add(household);
        
        CustomerFactConflictEvaluation.FlowInputs accs = new CustomerFactConflictEvaluation.FlowInputs();
        accs.accountList = testAccounts;
        List<CustomerFactConflictEvaluation.FlowInputs> accsList = new List<CustomerFactConflictEvaluation.FlowInputs>();
        accsList.add(accs);
        
        test.StartTest();
        CustomerFactConflictEvaluation.evaluateConflicts(accsList);
        Account hh = [SELECT Id, Name, ConflictOfInterest__c, DateConflictOfInterestAssessed__c FROM Account WHERE AccountNumber = '1235' LIMIT 1];
        test.StopTest();
        
        System.AssertEquals('Yes', hh.ConflictOfInterest__c);
    }
    
    @isTest
    static void noConflictTestMethod(){
        
        List<Account> testAccounts = new List<Account>();
        Id hhRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
        Account household = [SELECT Id, Name, ConflictOfInterest__c, IsPersonAccount, DateConflictOfInterestAssessed__c FROM Account WHERE AccountNumber = '1235' LIMIT 1];
        testAccounts.add(household);
        
        CustomerFactConflictEvaluation.FlowInputs accs = new CustomerFactConflictEvaluation.FlowInputs();
        accs.accountList = testAccounts;
        List<CustomerFactConflictEvaluation.FlowInputs> accsList = new List<CustomerFactConflictEvaluation.FlowInputs>();
        accsList.add(accs);
        
        CustomerFact__c cf = [SELECT Id, Name FROM CustomerFact__c WHERE Name = 'Friend' AND Household__c =: household.Id LIMIT 1];
        cf.Status__c = 'Inactive';
        update cf;
        
        
        test.StartTest();
        CustomerFactConflictEvaluation.evaluateConflicts(accsList);
        Account hh = [SELECT Id, Name, ConflictOfInterest__c, DateConflictOfInterestAssessed__c FROM Account WHERE AccountNumber = '1235' LIMIT 1];
        test.StopTest();
        
        System.AssertEquals('No', hh.ConflictOfInterest__c);
    }
}