force-app/main/default/objects/Account/fields/Dashboard_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Dashboard_Visibility__c</fullName>
    <description>Toggles visibility of the dashboard on the portal. If visibility is &quot;off&quot;, clients can only access their profile.</description>
    <inlineHelpText>Toggles visibility of the dashboard on the portal. If visibility is &quot;off&quot;, clients can only access their profile.</inlineHelpText>
    <label>Dashboard visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Off</fullName>
                <default>true</default>
                <label>Off</label>
            </value>
            <value>
                <fullName>On</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Exclude_From_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Exclude_From_Reporting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude From Reporting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fact_Find_Type__c.field-meta.xml
<CustomField>
    <fullName>Fact_Find_Type__c</fullName>
    <defaultValue>&quot;Discovery&quot;</defaultValue>
    <inlineHelpText>This field toggles what version of the fact find the client sees in the portal</inlineHelpText>
    <label>Profile Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discovery</fullName>
                <default>true</default>
                <label>Discovery</label>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Verifying</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Reported Deceased</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To be classified</fullName>
            </value>
            <value>
                <fullName>Forgotten</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nominated_Bank_Details_Visible__c.field-meta.xml
<CustomField>
    <fullName>Nominated_Bank_Details_Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Deprecated by enhanced bank details. When enabled, the client can enter their nominated bank details and view payment details in the portal.</description>
    <inlineHelpText>When enabled, the client can enter their nominated bank details and view payment details in the portal.</inlineHelpText>
    <label>Bank Details Visible (Legacy)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Test_Record__c.field-meta.xml
<CustomField>
    <fullName>Test_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/FinServ__PrimaryGroup__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryGroup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates a person&#39;s primary group</description>
    <label>Primary Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

unpackaged/main/default/classes/createTestData.cls
public class createTestData {
    
    public static String createHousehold (Integer numClients, Integer numChildren, String factFindType) {
        
        // Set variables used throughout the flow
        String HouseholdRecordTypeDevName = 'IndustriesHousehold';
        String PersonRecordTypeDevName = 'PersonAccount';   
        String HouseholdRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(HouseholdRecordTypeDevName).getRecordTypeId();
        String PersonRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(PersonRecordTypeDevName).getRecordTypeId();
        Id userId = System.UserInfo.getUserId();
        String runTime = String.valueOf(Datetime.now()).deleteWhiteSpace().remove('-').remove(':');
        String runIdentifier = userId + runTime;
        String personLastName = System.UserInfo.getLastName() + runTime;
        
        // Build the list of accounts that are to be inserted in this flow
        List<Account> accounts = new List<Account>();
        
        // Create household
        Account household = new Account(
            RecordTypeId = HouseholdRecordTypeId,
            Test_Record__c = true,
            Exclude_From_Reporting__c = true,
            AccountNumber = 'hh' + runIdentifier,
            OwnerId = userId,
            Name = 'Test ' + System.UserInfo.getLastName() + runTime, 
            AccountSource = 'Test data',
            FinServ__Status__c = 'Prospect',
            Fact_Find_Type__c = factFindType,
            Dashboard_Visibility__c = 'Off',
            Nominated_Bank_Details_Visible__c = true
        );
        accounts.add(household);
        
        // Create adult clients
        for( Integer i = 0; i < numClients; i++) {
            Account client = new Account(
                RecordTypeId = PersonRecordTypeId,
                Test_Record__c = true,
                Exclude_From_Reporting__c = true,
                AccountNumber = 'cl' + i + runIdentifier,
                OwnerId = userId,
                FirstName = System.UserInfo.getFirstName() + i,
                LastName = personLastName,
                FinServ__Status__c = 'Prospect',
                AccountSource = 'Test data',
                PersonEmail = 'owemailtest2108+' + String.valueOf(Integer.valueof((Math.random() * 1000))) + '@gmail.com'
            );
            accounts.add(client);
        }
        
        // Create children
        for( Integer i = 0; i < numChildren; i++) {
            Account child = new Account(
                RecordTypeId = PersonRecordTypeId,
                Test_Record__c = true,
                Exclude_From_Reporting__c = true,
                AccountNumber = 'ch' + i + runIdentifier,
                OwnerId = userId,
                FirstName = 'Child ' + i,
                LastName = personLastName,
                FinServ__Status__c = 'Prospect',
                AccountSource = 'Test data',
                PersonEmail = 'owemailtest2108+' + String.valueOf(Integer.valueof((Math.random() * 1000))) + '@gmail.com'          
            ); 
            accounts.add(child);
        }
        
        // Insert all accounts
        insert accounts;
        
        // Get the household ID and create a variable containing all the inserted person accounts
        String householdId;
        for (Account acc : accounts){
            if ( acc.RecordTypeId == HouseholdRecordTypeId ){
                householdId = acc.Id;
            }
        }
        
        // Get the details of the person accounts - query needed as we need the ID of the contact associated with the person account
        List<Account> personAccounts = [SELECT PersonContactId, AccountNumber FROM Account WHERE LastName =: personLastName];
        
        List<AccountContactRelation> relationships = new List<AccountContactRelation>();
        AccountContactRelation relationship = new AccountContactRelation( AccountId = householdId );
        for (Account personAccount : personAccounts){
            if ( personAccount.AccountNumber.left(2) == 'cl' ){
                relationship.ContactId = personAccount.PersonContactId;
                relationship.FinServ__PrimaryGroup__c = true;
                relationship.Roles = 'Client';
                relationships.add(relationship);
                relationship = new AccountContactRelation( AccountId = householdId );                
            } else if ( personAccount.AccountNumber.left(2) == 'ch' ) {
                relationship.ContactId = personAccount.PersonContactId;
                relationship.FinServ__PrimaryGroup__c = true;                
                relationship.Roles = 'Child';
                relationships.add(relationship);
                relationship = new AccountContactRelation( AccountId = householdId );
            }
        }
        insert relationships;
        
        return householdId;
    }
}