force-app/main/default/objects/Account/fields/Fact_Find_Type__c.field-meta.xml
<CustomField>
    <fullName>Fact_Find_Type__c</fullName>
    <defaultValue>&quot;Discovery&quot;</defaultValue>
    <inlineHelpText>This field toggles what version of the fact find the client sees in the portal</inlineHelpText>
    <label>Profile Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discovery</fullName>
                <default>true</default>
                <label>Discovery</label>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Verifying</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Reported Deceased</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To be classified</fullName>
            </value>
            <value>
                <fullName>Forgotten</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OW_role_in_primary_household__c.field-meta.xml
<CustomField>
    <fullName>OW_role_in_primary_household__c</fullName>
    <description>This field will be updated by a flow to reflect this person&#39;s role on the primary household.</description>
    <label>Role in primary household</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/utm_medium__c.field-meta.xml
<CustomField>
    <fullName>utm_medium__c</fullName>
    <description>Marketing tracking field to capture medium of lead came through</description>
    <label>utm_medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/FinServ__PrimaryGroup__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryGroup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates a person&#39;s primary group</description>
    <label>Primary Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Advice_Status__c.field-meta.xml
<CustomField>
    <fullName>Advice_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
                <default>true</default>
                <label>Setup</label>
            </value>
            <value>
                <fullName>Data gathering</fullName>
            </value>
            <value>
                <fullName>Risk Call</fullName>
            </value>
            <value>
                <fullName>Ready for suitability</fullName>
            </value>
            <value>
                <fullName>Suitability in progress</fullName>
            </value>
            <value>
                <fullName>Prepare advice</fullName>
            </value>
            <value>
                <fullName>Present advice</fullName>
            </value>
            <value>
                <fullName>Deck complete</fullName>
            </value>
            <value>
                <fullName>Await decision</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>In fulfilment</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Suitability Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Meeting held</fullName>
                <isActive>false</isActive>
                <label>Meeting held</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Fact_find_requirements__c.field-meta.xml
<CustomField>
    <fullName>Fact_find_requirements__c</fullName>
    <label>Fact find requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update required</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Fact_find_type__c.field-meta.xml
<CustomField>
    <fullName>Fact_find_type__c</fullName>
    <label>Fact find type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/G_Drive_Advice_Folder__c.field-meta.xml
<CustomField>
    <fullName>G_Drive_Advice_Folder__c</fullName>
    <label>Google Drive advice folder</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/New_LOAs_required__c.field-meta.xml
<CustomField>
    <fullName>New_LOAs_required__c</fullName>
    <inlineHelpText>This will start a workflow to create and send out new LOAs</inlineHelpText>
    <label>Additional LOAs required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/New_or_existing_client__c.field-meta.xml
<CustomField>
    <fullName>New_or_existing_client__c</fullName>
    <label>New or existing client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Update_valuations__c.field-meta.xml
<CustomField>
    <fullName>Update_valuations__c</fullName>
    <inlineHelpText>Yes - will create a task for a specialist to update valuations for related financial products</inlineHelpText>
    <label>Update valuations</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/recordTypes/Advice_RT_General_Advice.recordType-meta.xml
<RecordType>
    <fullName>Advice_RT_General_Advice</fullName>
    <active>true</active>
    <description>RT for general advice, this will be broken into many</description>
    <label>General Advice</label>
</RecordType>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Fulfilment</fullName>
            </value>
            <value>
                <fullName>Not Taken Up</fullName>
            </value>
            <value>
                <fullName>Deleted by client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Primary Owner&#39;s household</inlineHelpText>
    <label>Household Lookup</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household.

(Admin message: lookup filter criteria not met on Household on the financial product object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/recordTypes/FP_General_Investment_Account_GIA.recordType-meta.xml
<RecordType>
    <fullName>FP_General_Investment_Account_GIA</fullName>
    <active>true</active>
    <label>GIA</label>
</RecordType>

force-app/main/default/objects/FinServ__FinancialAccount__c/recordTypes/FP_Stocks_Shares_ISA.recordType-meta.xml
<RecordType>
    <fullName>FP_Stocks_Shares_ISA</fullName>
    <active>true</active>
    <label>Stocks &amp; Shares ISA</label>
</RecordType>

force-app/main/default/objects/LOA__c/LOA__c.object-meta.xml
<CustomObject>
    <label>LOA</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LOA__c/fields/Provider_Database__c.field-meta.xml
<CustomField>
    <fullName>Provider_Database__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider_Database__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Fulfilment</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider_Database__c</referenceTo>
    <relationshipLabel>LOAs (Provider Database)</relationshipLabel>
    <relationshipName>LOAs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOA__c/recordTypes/Pre_LOA.recordType-meta.xml
<RecordType>
    <fullName>Pre_LOA</fullName>
    <active>true</active>
    <label>LOA</label>
</RecordType>

force-app/main/default/objects/LOA_to_Advice__c/LOA_to_Advice__c.object-meta.xml
<CustomObject>
    <label>LOA to Advice</label>
    <nameField>
        <displayFormat>LTA-{00000}</displayFormat>
        <label>LOA to Advice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LOA to Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LOA_to_Advice__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <label>Advice</label>
    <referenceTo>Advice__c</referenceTo>
    <relationshipLabel>LOAs for Advice</relationshipLabel>
    <relationshipName>LOA_to_Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/fake_data_factory.cls
public class fake_data_factory {
    
    /**
* TITLE:	Create test household
* GOAL:		Generates household data for demo and test purposes.
* NOTES:	Stored in production so available in refreshed sandboxes but should not be used in production, though is initially for portal purposes. 
* 			Takes inputs of:
* 				- number of clients in the household
* 				- number of children in the household
* 				- status of the household
* 				- fact find type
* 				- identifier used to find this data after creation
**/    
    
    // Takes a number of clients, children, and status as inputs and generates the data   
    public Id create_household (String identifier, Integer num_clients, Integer num_children, String status, String profile_type) {
        
        // Define a few variables used throughout
        String HouseholdRecordTypeDevName = 'IndustriesHousehold';
        String PersonRecordTypeDevName = 'PersonAccount';
        List<Account> accounts = new List<Account>(); // The list of accounts that will ultimately be inserted
        
        // Create the family name
        random_name_generator rng = new random_name_generator();
        String family_name = rng.generate_name('last_name');
        String household_name = family_name;
        
        // Create the clients
        for( Integer i = 0; i < num_clients; i++) {
            Account person = new Account(
                FirstName = rng.generate_name('first_name'), 
                LastName = family_name,  
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(PersonRecordTypeDevName).getRecordTypeId(),
                OW_role_in_primary_household__c = 'Client',
                FinServ__Status__c = status,
                PersonEmail = family_name + i + '@fakeemail.com',
                utm_medium__c = identifier // Set an identifier specified by the requestor in a random unused text field so that these records can be identified by the requestor
            );
            accounts.add(person);
            
            // Add to the household name the initial of this client
            household_name = household_name + ', ' + person.FirstName.left(1);
        }
        
        // Create the children
        for( Integer i = 0; i < num_children; i++) {
            Account person = new Account(
                FirstName = rng.generate_name('first_name'), 
                LastName = family_name,  
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(PersonRecordTypeDevName).getRecordTypeId(),
                OW_role_in_primary_household__c = 'Child',
                FinServ__Status__c = status,
                utm_medium__c = identifier // Set an identifier specified by the requestor in a random unused text field so that these records can be identified by the requestor
            );
            accounts.add(person);
        }
        
        // Create the household then insert all the accounts
        Account household = new Account(
            Name = household_name,
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(HouseholdRecordTypeDevName).getRecordTypeId(),
            FinServ__Status__c = status,
            Fact_Find_Type__c = profile_type,
            utm_medium__c = identifier // Set an identifier specified by the requestor in a random unused text field so that these records can be identified by the requestor            
        );
        accounts.add(household);
        insert accounts;
        
        // Identify the household ID and the list of person account IDs now that they have been inserted
        String household_id;
        List<Id> person_ids = new List<Id>();
        for (Account acc : accounts){
            if( acc.RecordTypeId == Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(HouseholdRecordTypeDevName).getRecordTypeId() ){
                household_id = acc.Id;
            } else {
                person_ids.add(acc.Id);
            }
        }
        
        // Return full details of the person accounts created earlier so the contact ID is known
        List<Account> person_accounts = [SELECT Id, PersonContactId, OW_role_in_primary_household__c FROM Account WHERE Id in: person_ids];
        
        // Create the account contact relationships between the household and the clients and children
        List<AccountContactRelation> acrs = new List<AccountContactRelation>();
        Boolean primary_client_set = false;
        for (Account acc : person_accounts){
            AccountContactRelation acr = new AccountContactRelation(
                AccountId = household_id,
                ContactId = acc.PersonContactId,
                FinServ__PrimaryGroup__c = true,
                Roles = acc.OW_role_in_primary_household__c,
                FinServ__SourceSystemId__c = identifier // Set an identifier specified by the requestor in a random unused text field so that these records can be identified by the requestor
            );
            if( primary_client_set == false && acr.Roles == 'Client'){
                acr.FinServ__Primary__c = true;
                primary_client_set = true;
            }
            acrs.add(acr);
        }
        insert acrs;
        return household_id;
    }
    
    // Takes a given household and creates a defined number of products per person with associated LOAs
    public Advice__c create_advice (String identifier, Integer num_products_pp, Id household_id){
        
        // Define constants used throughout
        String advice_record_type_dev_name = 'Advice_RT_General_Advice';
		String financial_product_record_type_dev_name = 'FP_Stocks_Shares_ISA';
        String financial_product_record_type_dev_name_joint = 'FP_General_Investment_Account_GIA';
        String public_provider_name = 'Big bank of biznizz';
        
        // Define and insert the advice record
        Advice__c advice = new Advice__c(
            Advice_Household__c = household_id,
            RecordTypeId = Schema.SObjectType.Advice__c.getRecordTypeInfosByDeveloperName().get(advice_record_type_dev_name).getRecordTypeId(),
            New_or_existing_client__c = 'Existing',
            Partner__c = [ SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ].Id,
            Fact_find_requirements__c = 'Not required',
            G_Drive_Advice_Folder__c = 'google.com',
            Update_valuations__c = 'No',
            New_LOAs_required__c = 'No', 
            Advice_Status__c = 'Data Gathering',
            Subject__c = identifier,
            Name = identifier
        );
        insert advice;
        
        // Create the products
        if( num_products_pp != 0){
            
            // Identify an existing fake public provider or create a new one if none exists
            Public_Provider_Names__c public_provider = new Public_Provider_Names__c();
            Public_Provider_Names__c[] public_providers = [SELECT Id FROM Public_Provider_Names__c WHERE Name =: public_provider_name];
            if(public_providers.size() == 0){
                public_provider = new Public_Provider_Names__c (
                    Name = public_provider_name
                );
                insert public_provider;
            } else {
                public_provider = public_providers[0];
            }
            
            //Might not be needed as hoping this is not mandatory. 
            //Provider_Database__c providerDB = new Provider_Database__c (Name = 'John Smith', Provider_Name__c = 'Test provider DB');
            //insert providerDB;
            
            // Get the clients from the household
            AccountContactRelation[] acrs = [SELECT Id, Contact.AccountId FROM AccountContactRelation WHERE Roles = 'Client' AND AccountId =: household_id];
            
            // Start list of financial products to create
            List<FinServ__FinancialAccount__c> financial_products = new List<FinServ__FinancialAccount__c>();
            
            // Create financial products for each of the clients in the household
            for(AccountContactRelation acr : acrs) {
                Integer i;
                for( i = 0 ; i < num_products_pp; i++) {
                    FinServ__FinancialAccount__c financial_product = new FinServ__FinancialAccount__c(
                        Name = 'Test',
                        Subtype__c  = 'Stocks & Shares ISA',
                        FinServ__PrimaryOwner__c = acr.Contact.AccountId,
                        Household__c = household_id,
                        FinServ__Ownership__c = 'Individual',
                        FinServ__Status__c = 'Open',
                        Public_Provider_Name__c = public_provider.Id,
                        //Provider_Contact_Details__c = providerDB.Id,
                        RecordTypeId = Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByDeveloperName().get(financial_product_record_type_dev_name).getRecordTypeId()
                    );
                    financial_products.add(financial_product);
                }
            }
            
            // Create a joint account if there are 2 or more clients in the household
            if(acrs.size() >= 2){
                FinServ__FinancialAccount__c financial_product = new FinServ__FinancialAccount__c(
                    Name = 'Test',
                    Subtype__c  = 'General Investment Account',
                    FinServ__PrimaryOwner__c = acrs[0].Contact.AccountId,
                    FinServ__JointOwner__c = acrs[1].Contact.AccountId,
                    FinServ__Ownership__c = 'Joint',
                    Household__c = household_id,
                    FinServ__Status__c = 'Open',
                    Public_Provider_Name__c = public_provider.Id,
                    //Provider_Contact_Details__c = providerDB.Id,
                    RecordTypeId = Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByDeveloperName().get(financial_product_record_type_dev_name_joint).getRecordTypeId()
                );
                financial_products.add(financial_product);
            }
            insert financial_products;
            
            // Create LOAs for the financial products
            List<LOA__c> loas = new List<LOA__c>();
            for( FinServ__FinancialAccount__c financial_product : financial_products){
                LOA__c loa = new LOA__c(
                    Name = 'Test LOA',
                    LOA_Financial_Account__c = financial_product.Id,
                    Household_Lookup__c = household_id,
                    MainLOAStatus__c = 'LOA Received Awaiting Information',
                    Date_LOA_sent_to_provider__c = Date.today(),
                    Date_LOA_accepted_by_provider__c = Date.today(),
                    Date_Last_Chased__c = Date.today(),
                    RecordTypeId = Schema.SObjectType.LOA__c.getRecordTypeInfosByDeveloperName().get('Pre_LOA').getRecordTypeId() 
                );
                loas.add(loa);
            }
            insert loas;
            
            // Link the LOAs to the advice
            List<LOA_to_Advice__c> ltas = new List<LOA_to_Advice__c>();
            for(LOA__c loa : loas){
                LOA_to_Advice__c lta = new LOA_to_Advice__c(
                    Advice__c = advice.Id,
                    LOA__c = loa.Id
                );
                ltas.add(lta);
            }
            insert ltas;
        }
        return advice;
    }
}