force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Verifying</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Reported Deceased</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To be classified</fullName>
            </value>
            <value>
                <fullName>Forgotten</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/OW_aml_check_account__c.field-meta.xml
<CustomField>
    <fullName>OW_aml_check_account__c</fullName>
    <description>The status of the AML check. Applies to people only.</description>
    <inlineHelpText>Indicates if the person has passed AML via the new process using Experian, WC1, and managed in Salesforce. If  incomplete, they may still have passed AML but via the old process and you should look at the KYC status field.</inlineHelpText>
    <label>AML status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/OW_rtq_status__c.field-meta.xml
<CustomField>
    <fullName>OW_rtq_status__c</fullName>
    <description>Hold the status of the household or customer with regards to risk tolerance. This is used to drive automation and validation in relation to RTQs.</description>
    <label>RTQ status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OW_terms_of_Business_Status__c.field-meta.xml
<CustomField>
    <fullName>OW_terms_of_Business_Status__c</fullName>
    <description>The status of Terms of Business records which are to be signed by a customer. Applies to people only.</description>
    <label>Terms of business status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TempBankDetailIssues__c.field-meta.xml
<CustomField>
    <fullName>TempBankDetailIssues__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Temporary field to indicate whether this account is currently outside of bank account rules</description>
    <label>TEMP bank detail issues</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vulnerable_Client__c.field-meta.xml
<CustomField>
    <fullName>Vulnerable_Client__c</fullName>
    <description>Indicates if person is deemed vulnerable and adjustments or mitigations are needed</description>
    <label>Vulnerable client status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Vulnerable</fullName>
            </value>
            <value>
                <fullName>Not vulnerable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LwcHelperAccountStatusFlags.cls
public with sharing class LwcHelperAccountStatusFlags {

    public static final String ROLE_CLIENT = 'Client';
    
    public static Set<Id> getHouseholdAccountIds(Id householdId){
        Set<Id> accountIds = new Set<Id>();
        for(AccountContactRelation relation : [SELECT Id, ContactId, Contact.AccountId FROM AccountContactRelation WHERE AccountId = :householdId AND IsActive = True AND Roles = :ROLE_CLIENT]){
            accountIds.add(relation.Contact.AccountId);
        }
        return accountIds;
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getAccountsByHouseholdId(Id householdId) {
        Set<Id> accountIds = getHouseholdAccountIds(householdId);
        List<Account> accounts = [
            SELECT Id, FinServ__Status__c, OW_terms_of_Business_Status__c, OW_aml_check_account__c, OW_rtq_status__c, Vulnerable_Client__c, TempBankDetailIssues__c
            FROM Account
            WHERE Id 
            IN :accountIds
        ];

        return accounts;

    }

    @AuraEnabled(cacheable=true)
    public static flagWrapper getWrapperFromRecord(Id recordId, String objectName) {
        flagWrapper flags = new flagWrapper();
        if(objectName == 'Advice__c'){
            Advice__c advice = [SELECT Id, Advice_Household__c FROM Advice__c WHERE Id = :recordId];
            flags.householdId = advice.Advice_Household__c;
        }
        return flags;
    }

    public class flagWrapper {
        @AuraEnabled public String householdId;
        @AuraEnabled public Boolean exampleFlagValue;
    }
}