force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Verifying</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Reported Deceased</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To be classified</fullName>
            </value>
            <value>
                <fullName>Forgotten</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Household_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Household_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to primary household from person account</description>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Household_Lookup on the Account object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Person Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Fulfilment</fullName>
            </value>
            <value>
                <fullName>Not Taken Up</fullName>
            </value>
            <value>
                <fullName>Deleted by client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Primary Owner&#39;s household</inlineHelpText>
    <label>Household Lookup</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household.

(Admin message: lookup filter criteria not met on Household on the financial product object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The post-CheerIO product this relates to</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Financial Products</relationshipLabel>
    <relationshipName>Financial_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FulfilmentType__c/FulfilmentType__c.object-meta.xml
<CustomObject>
    <description>Used to store process specific information for each type of fulfilment</description>
    <label>Fulfilment Type</label>
    <nameField>
        <label>Fulfilment Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfilment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FulfilmentType__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product that  this fulfilment type is associated with</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Fulfilment Types</relationshipLabel>
    <relationshipName>Fulfilment_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FulfilmentType__c/fields/RecommendationType__c.field-meta.xml
<CustomField>
    <fullName>RecommendationType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation type that this fulfilment type relates to</description>
    <label>Recommendation Type</label>
    <referenceTo>RecommendationType__c</referenceTo>
    <relationshipName>Fulfilment_types</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/LOA__c/LOA__c.object-meta.xml
<CustomObject>
    <label>LOA</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LOA__c/fields/Household_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Household_Lookup__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on household_lookup__c on the LOA__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LOAs</relationshipLabel>
    <relationshipName>HouseholdLOAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Will store the kinds of products we can provide in the post-cheerIO world.</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product category this falls under</description>
    <label>Product type</label>
    <referenceTo>ProductType__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductType__c/ProductType__c.object-meta.xml
<CustomObject>
    <description>Used to indicate which fields are relevant for the Product object</description>
    <label>Product type</label>
    <nameField>
        <label>Product type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Provider_Names__c/Public_Provider_Names__c.object-meta.xml
<CustomObject>
    <label>Public Provider List</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Provider List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecommendationType__c/RecommendationType__c.object-meta.xml
<CustomObject>
    <description>Object to control which fields are visible on recommendations, based on the kind of recommendation they are.</description>
    <label>Recommendation Type</label>
    <nameField>
        <label>Recommendation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommendation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/DataFactoryTest.cls
@isTest
global class DataFactoryTest {

    @TestSetup
    static void testDataSetup() {
        // Set up reference data
        List<sObject> ls = Test.loadData(Public_Provider_Names__c.sObjectType, 'ProviderRef');
        List<sObject> ls3 = Test.loadData(RecommendationType__c.sObjectType, 'RecRef');
        List<sObject> ls4 = Test.loadData(ProductType__c.sObjectType, 'ProductTypeRef');
        List<sObject> ls2 = Test.loadData(Product__c.sObjectType, 'ProductRef');
        List<sObject> ls5 = Test.loadData(FulfilmentType__c.sObjectType, 'FTRef');
    }

    @istest
    static void testHouseholdCreation(){
        Integer numClients = 2;
        Integer numChildren = 3;
        String status = 'Active';
        String identifier = 'cth_test_run';
        String profileType = 'Full'; 
        DataFactory df = new DataFactory();
        String householdId = df.createHousehold(identifier, numClients, numChildren, status, profileType);
        
        //Account[] accounts = [SELECT Id FROM Account WHERE FinServ__Status__c =: status and Household_lookup__c =: householdId];
        AccountContactRelation[] acrs = [SELECT Id, Roles FROM AccountContactRelation WHERE AccountId =: householdId];
        
        // Check that there is a relationship for each client and child.
        Integer numChildRelationships = 0;
        Integer numClientRelationships = 0;      
        for(AccountContactRelation acr : acrs){
            if(acr.Roles == 'Client'){
                numClientRelationships++;
            } else if(acr.Roles == 'Child'){
                numChildRelationships++;
            }
        }
        System.assert(numChildRelationships == numChildren); 
        System.assert(numClientRelationships == numClients);
    }
    
    @istest
    static void testAdviceCreation(){
        Integer numClients = 2;
        Integer numProducts = 1;
        Integer numChildren = 0;
        String status = 'Active';
        String identifier = 'cth_test_run_advice';
        String profileType = 'Full'; 
        DataFactory df = new DataFactory();
        Id householdId = df.createHousehold(identifier, numClients, numChildren, status, profileType);
        Advice__c advice = df.createAdvice(numProducts, householdId);
        
        // Get the financial products and LOAs back
        FinServ__FinancialAccount__c[] financial_products = [SELECT Id FROM FinServ__FinancialAccount__c WHERE Household__c =: householdId];
        LOA__c[] loas = [SELECT Id FROM LOA__c WHERE Household_Lookup__c =: householdId];
        
        //System.assert(numClients * numProducts + 1 == financial_products.size()); // Check that there is a financial product for each client plus a joint product
        System.assert(numClients * numProducts + 1 == loas.size()); // Check that there is an LOA for each client plus a joint product
    }
}