force-app/main/default/objects/Account/fields/FinServ__NextReview__c.field-meta.xml
<CustomField>
    <fullName>FinServ__NextReview__c</fullName>
    <inlineHelpText>This is the due date, not the date of the actual meeting</inlineHelpText>
    <label>Next Review</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Verifying</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Reported Deceased</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To be classified</fullName>
            </value>
            <value>
                <fullName>Forgotten</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/OW_rtq_status__c.field-meta.xml
<CustomField>
    <fullName>OW_rtq_status__c</fullName>
    <description>Hold the status of the household or customer with regards to risk tolerance. This is used to drive automation and validation in relation to RTQs.</description>
    <label>RTQ status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Advice_Status__c.field-meta.xml
<CustomField>
    <fullName>Advice_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
                <default>true</default>
                <label>Setup</label>
            </value>
            <value>
                <fullName>Data gathering</fullName>
            </value>
            <value>
                <fullName>Risk Call</fullName>
            </value>
            <value>
                <fullName>Ready for suitability</fullName>
            </value>
            <value>
                <fullName>Suitability in progress</fullName>
            </value>
            <value>
                <fullName>Prepare advice</fullName>
            </value>
            <value>
                <fullName>Present advice</fullName>
            </value>
            <value>
                <fullName>Deck complete</fullName>
            </value>
            <value>
                <fullName>Await decision</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>In fulfilment</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Suitability Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Meeting held</fullName>
                <isActive>false</isActive>
                <label>Meeting held</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/AdviceType__c.field-meta.xml
<CustomField>
    <fullName>AdviceType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A reference to advice type where variables are held that control business logic of the advice record.</description>
    <label>Advice type</label>
    <referenceTo>AdviceType__c</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/New_or_existing_client__c.field-meta.xml
<CustomField>
    <fullName>New_or_existing_client__c</fullName>
    <label>New or existing client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/OW_review__c.field-meta.xml
<CustomField>
    <fullName>OW_review__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Concurrent Annual Review to Advice</description>
    <inlineHelpText>This field can be updated by linking to this advice from a review.</inlineHelpText>
    <label>Review</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The advice and annual review must be linked to the same household.

(Admin message: filter criteria on OW_review__c field on the Advice__c object)</errorMessage>
        <filterItems>
            <field>$Source.Advice_Household__c</field>
            <operation>equals</operation>
            <valueField>OW_review__c.OW_household__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OW_review__c</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/RtqStatus__c.field-meta.xml
<CustomField>
    <fullName>RtqStatus__c</fullName>
    <description>Tracks the rtq requirements for this advice</description>
    <label>RTQ status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No update required</fullName>
            </value>
            <value>
                <fullName>Not started</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advice__c/recordTypes/AnnualReview.recordType-meta.xml
<RecordType>
    <fullName>AnnualReview</fullName>
    <active>true</active>
    <description>For any annual review.</description>
    <label>Annual review</label>
</RecordType>

force-app/main/default/objects/AdviceType__c/AdviceType__c.object-meta.xml
<CustomObject>
    <description>Models the types of advice that we provide to customers and how things vary between them. Used to drive business logic on actual advice.</description>
    <label>Advice Type</label>
    <nameField>
        <label>Advice Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AdviceType__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name for an advice type. Used to provide consistency in business logic across environments.</description>
    <label>Developer Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/External_Gains_Losses__c/External_Gains_Losses__c.object-meta.xml
<CustomObject>
    <label>Gains &amp; ISA Contributions</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Gains &amp; ISAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Gains_Losses__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <description>This is the associated household with this fact find.</description>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Household on the Gains &amp; ISA contributions object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>External Gains &amp; ISAs (Household)</relationshipLabel>
    <relationshipName>External_Gains_ISAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OW_review__c/OW_review__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage the review process with existing clients. It&#39;s a fairly lightweight place to manage the upcoming reviews and track the initial conversations. The resulting workflows - preparation of decks, advice etc - are all managed in the advice object.</description>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_review__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <inlineHelpText>Does the advice make sense and seem to be both suitable, but also the right thing for the client? If not, please flat to planner/head planner</inlineHelpText>
    <label>Advice</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/OW_review__c/fields/OW_household__c.field-meta.xml
<CustomField>
    <fullName>OW_household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The household for which this annual review is carried out.</description>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on OW_household__c on the OW_annual_review__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OW_review__c/fields/OW_status__c.field-meta.xml
<CustomField>
    <fullName>OW_status__c</fullName>
    <description>The status of a given annual review in the annual review process</description>
    <label>Review status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prepare</fullName>
                <default>true</default>
                <label>Prepare</label>
            </value>
            <value>
                <fullName>Await fact find</fullName>
            </value>
            <value>
                <fullName>Catch up</fullName>
            </value>
            <value>
                <fullName>Provide advice</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Create Deck</fullName>
                <isActive>false</isActive>
                <label>Create Deck</label>
            </value>
            <value>
                <fullName>Fact Find Update</fullName>
                <isActive>false</isActive>
                <label>Fact Find Update</label>
            </value>
            <value>
                <fullName>Partner Review</fullName>
                <isActive>false</isActive>
                <label>Partner Review</label>
            </value>
            <value>
                <fullName>Review Deck</fullName>
                <isActive>false</isActive>
                <label>Review Deck</label>
            </value>
            <value>
                <fullName>Review Slides</fullName>
                <isActive>false</isActive>
                <label>Review Slides</label>
            </value>
            <value>
                <fullName>Voyant Update</fullName>
                <isActive>false</isActive>
                <label>Voyant Update</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OW_review__c/recordTypes/OW_annual_review.recordType-meta.xml
<RecordType>
    <fullName>OW_annual_review</fullName>
    <active>true</active>
    <label>Annual review</label>
</RecordType>

force-app/main/default/classes/AnnualReviewGenerator.cls
/**
 * Kicks off the annual review process for households that need one based on status and proximity to the due date
 */
@SuppressWarnings('PMD.ApexCRUDViolation')
public without sharing class AnnualReviewGenerator{

    private final static String ACCOUNT_HOUSEHOLD_RECORD_TYPE_DEVELOPER_NAME = 'IndustriesHousehold';
    private final static String REVIEW_ANNUAL_RECORD_TYPE_DEVELOPER_NAME = 'OW_annual_review';
    private final static String ADVICE_ANNUAL_REVIEW_RECORD_TYPE_DEVELOPER_NAME = 'AnnualReview';
    private final static Id ACCOUNT_HOUSEHOLD_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCOUNT_HOUSEHOLD_RECORD_TYPE_DEVELOPER_NAME)?.getRecordTypeId();
    private final static Id REVIEW_ANNUAL_RECORD_TYPE_ID = Schema.SObjectType.OW_review__c.getRecordTypeInfosByDeveloperName().get(REVIEW_ANNUAL_RECORD_TYPE_DEVELOPER_NAME)?.getRecordTypeId();
    private final static Id ADVICE_ANNUAL_REVIEW_RECORD_TYPE_ID = Schema.SObjectType.Advice__c.getRecordTypeInfosByDeveloperName().get(ADVICE_ANNUAL_REVIEW_RECORD_TYPE_DEVELOPER_NAME)?.getRecordTypeId(); 
    private final static Date MAX_DATE = Date.today().addMonths(2).addDays(-1);
    private final static String STATUS_ACTIVE = 'Active';
    private final static String TYPE_EXECUTION_ONLY = 'Execution Only';
    private final static List<String> ADVICE_CONVERTIBLE_STATUSES = new List<String>{'Setup','Data gathering','Data analysis','Risk Call'};
    private final static List<String> ADVICE_CONVERTIBLE_TYPES = new List<String>{'AD_HOC','DRAWDOWN'};
    private final static String ADVICE_TYPE_ANNUAL_REVIEW = 'ANNUAL_REVIEW_ACCUMULATION';

    // The core method that retrieves the accounts and creates the annual review
    public static void createAnnualReviews(){

        // Find households that need an annual review
        List<Account> households = [
            SELECT
                Id, OwnerId, Name, FinServ__NextReview__c, OW_rtq_status__c, (SELECT Id FROM Advice__r WHERE Advice_Status__c IN :ADVICE_CONVERTIBLE_STATUSES AND AdviceType__r.DeveloperName__c IN :ADVICE_CONVERTIBLE_TYPES) FROM Account WHERE RecordType.DeveloperName = :ACCOUNT_HOUSEHOLD_RECORD_TYPE_DEVELOPER_NAME AND FinServ__Status__c = :STATUS_ACTIVE AND Type != :TYPE_EXECUTION_ONLY AND FinServ__NextReview__c <= :MAX_DATE
        ];

        // Get the members of the household
        AccountHouseholdMembers getMembers = new AccountHouseholdMembers();
        List<AccountHouseholdMembers.HouseholdMemberRequest> householdMemberRequests = new List<AccountHouseholdMembers.HouseholdMemberRequest>(); // Requests to get the clients that will need EGIs
        Set<String> roles = new Set<String>{'Client'};
        for (Account household : households) {
            AccountHouseholdMembers.HouseholdMemberRequest householdMemberRequest = new AccountHouseholdMembers.HouseholdMemberRequest();
            householdMemberRequest.householdId = household.Id;
            householdMemberRequest.roles = roles;
            householdMemberRequests.add(householdMemberRequest);
        }
        Map<Id, AccountHouseholdMembers.HouseholdMemberResult> householdMemberResults = getMembers.getHouseholdMembers(householdMemberRequests);

        // Create the lists we'll need for insert and update later on
        List<OW_review__c> annualReviews = new List<OW_review__c>();                                // The annual reviews for each household
        Map<Id, Advice__c> annualReviewAdviceMap = new Map<Id, Advice__c>();                        // The annual review advice for households that don't have any convertible advice in progress
        Map<External_Gains_Losses__c> egiMap = new Map<External_Gains_Losses__c>();         // The EGI records for each client in the households

        // Loop the households
        for (Account household : households) {
            String annualReviewYear = String.valueOf(household.FinServ__NextReview__c.year());

            // Push the household annual review date back 1 year
            household.FinServ__NextReview__c = Date.newInstance(household.FinServ__NextReview__c.year() + 1, household.FinServ__NextReview__c.month() + 1, 1).addDays(-1);

            // If there are no convertible advice, create the annual review advice
            if(household.Advice__r.isEmpty()){

                Advice__c advice = new Advice__c(
                    Advice_Household__c = household.Id,
                    Partner__c = household.OwnerId,
                    Name = 'Annual review ' + annualReviewYear,
                    Subject__c = 'Annual review ' + annualReviewYear,
                    RecordTypeId = ADVICE_ANNUAL_REVIEW_RECORD_TYPE_ID,
                    Advice_Status__c = 'Data gathering',
                    AdviceType__c = annualReviewAdviceTypeId,
                    New_or_existing_client__c = 'Existing'
                );

                // To do - define the link between the review and the advice. Will need to be done after insert.

                if(household.OW_rtq_status__c == 'Complete'){
                    advice.RtqStatus__c = 'No update required';
                } else if(household.OW_rtq_status__c == 'Pending'){
                    advice.RtqStatus__c = 'In progress';
                } else {
                    advice.RtqStatus__c = 'Not started';
                }
                annualReviewAdviceMap.put(household.Id, advice);
            }

            // Define the annual review 
            OW_review__c annualReview = new OW_review__c(
                OW_household__c = household.Id,
                OW_status__c = 'Prepare',
                OwnerId = household.OwnerId,
                RecordTypeId = REVIEW_ANNUAL_RECORD_TYPE_ID,
                Name = household.Name + ' - Annual review ' + annualReviewYear,
                OW_due_date__c = household.FinServ__NextReview__c
            );
            annualReviews.add(annualReview);

            for (Account client : householdMemberResults.get(household.Id).memberAccountsByRole.get('Client')){
                External_Gains_Losses__c egi = new External_Gains_Losses__c(
                    Name = client.FirstName + ' | ' + annualReviewYear,
                    Owner__c = client.Id,
                    Household__c = household.Id,
                    OW_stop_internal_change_processing__c = 1.0
                );
                egis.add(egi);
            }
        }
        
        try {
            insert annualReviews;
            insert egis;
            update households;
        } catch(DmlException e) {
            // To-do - handle exception
        }

        // To do - insert the advice
    }

    private static Id annualReviewAdviceTypeId{
        get{
            // to-do - handle no result, throw exception
            annualReviewAdviceTypeId = annualReviewAdviceTypeId == null ? [SELECT Id FROM AdviceType__c WHERE DeveloperName__c = :ADVICE_TYPE_ANNUAL_REVIEW].Id : annualReviewAdviceTypeId;
            return annualReviewAdviceTypeId;
        }
        set;
    }
}