force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Verifying</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Reported Deceased</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To be classified</fullName>
            </value>
            <value>
                <fullName>Forgotten</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/FinServ__PrimaryGroup__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PrimaryGroup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates a person&#39;s primary group</description>
    <label>Primary Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_confirmed_with_client__c.field-meta.xml
<CustomField>
    <fullName>Advice_confirmed_with_client__c</fullName>
    <inlineHelpText>Advice need to have been discussed and confirmed with the client before commencement.</inlineHelpText>
    <label>zDel - Advice confirmed with client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Advice_Status__c.field-meta.xml
<CustomField>
    <fullName>Advice_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
                <default>true</default>
                <label>Setup</label>
            </value>
            <value>
                <fullName>Data gathering</fullName>
            </value>
            <value>
                <fullName>Risk Call</fullName>
            </value>
            <value>
                <fullName>Ready for suitability</fullName>
            </value>
            <value>
                <fullName>Suitability in progress</fullName>
            </value>
            <value>
                <fullName>Prepare advice</fullName>
            </value>
            <value>
                <fullName>Present advice</fullName>
            </value>
            <value>
                <fullName>Deck complete</fullName>
            </value>
            <value>
                <fullName>Await decision</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>In fulfilment</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Suitability Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Meeting held</fullName>
                <isActive>false</isActive>
                <label>Meeting held</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Fact_find_requirements__c.field-meta.xml
<CustomField>
    <fullName>Fact_find_requirements__c</fullName>
    <label>Fact find requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update required</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/G_Drive_Advice_Folder__c.field-meta.xml
<CustomField>
    <fullName>G_Drive_Advice_Folder__c</fullName>
    <label>Google Drive advice folder</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/New_LOAs_required__c.field-meta.xml
<CustomField>
    <fullName>New_LOAs_required__c</fullName>
    <inlineHelpText>This will start a workflow to create and send out new LOAs</inlineHelpText>
    <label>Additional LOAs required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/New_or_existing_client__c.field-meta.xml
<CustomField>
    <fullName>New_or_existing_client__c</fullName>
    <label>New or existing client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Ready_to_start_data_gathering__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_start_data_gathering__c</fullName>
    <defaultValue>false</defaultValue>
    <label>zDel - Ready to start data gathering</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Scope_of_advice_status__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_advice_status__c</fullName>
    <label>zDel - Scope of advice status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be sent</fullName>
            </value>
            <value>
                <fullName>Sent to client</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Update_valuations__c.field-meta.xml
<CustomField>
    <fullName>Update_valuations__c</fullName>
    <inlineHelpText>Yes - will create a task for a specialist to update valuations for related financial products</inlineHelpText>
    <label>Update valuations</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/recordTypes/Advice_RT_General_Advice.recordType-meta.xml
<RecordType>
    <fullName>Advice_RT_General_Advice</fullName>
    <active>true</active>
    <description>RT for general advice, this will be broken into many</description>
    <label>General Advice</label>
</RecordType>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Primary Owner&#39;s household</inlineHelpText>
    <label>Household Lookup</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household.

(Admin message: lookup filter criteria not met on Household on the financial product object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <inlineHelpText>This is what the client will see under the highlevel  &quot;Type&quot; field in the portal.</inlineHelpText>
    <label>Portal Display Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Financial_Product_Subtypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/recordTypes/FP_Current_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Current_Account</fullName>
    <active>false</active>
    <label>Current Account</label>
</RecordType>

force-app/main/default/objects/FinServ__FinancialAccount__c/recordTypes/FP_Stocks_Shares_ISA.recordType-meta.xml
<RecordType>
    <fullName>FP_Stocks_Shares_ISA</fullName>
    <active>true</active>
    <label>Stocks &amp; Shares ISA</label>
</RecordType>

force-app/main/default/objects/LOA__c/LOA__c.object-meta.xml
<CustomObject>
    <label>LOA</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LOA__c/fields/Provider_Database__c.field-meta.xml
<CustomField>
    <fullName>Provider_Database__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Provider_Database__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Fulfilment</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Provider_Database__c</referenceTo>
    <relationshipLabel>LOAs (Provider Database)</relationshipLabel>
    <relationshipName>LOAs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOA__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Contact Details</label>
    <referenceTo>Provider_Database__c</referenceTo>
    <relationshipLabel>LOAs</relationshipLabel>
    <relationshipName>LOAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOA__c/recordTypes/Pre_LOA.recordType-meta.xml
<RecordType>
    <fullName>Pre_LOA</fullName>
    <active>true</active>
    <label>LOA</label>
</RecordType>

force-app/main/default/objects/LOA_to_Advice__c/LOA_to_Advice__c.object-meta.xml
<CustomObject>
    <label>LOA to Advice</label>
    <nameField>
        <displayFormat>LTA-{00000}</displayFormat>
        <label>LOA to Advice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LOA to Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LOA_to_Advice__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <label>Advice</label>
    <referenceTo>Advice__c</referenceTo>
    <relationshipLabel>LOAs for Advice</relationshipLabel>
    <relationshipName>LOA_to_Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Provider_Database__c/Provider_Database__c.object-meta.xml
<CustomObject>
    <label>Provider Contact Database</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Database</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provider_Database__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Financial_Product_Subtypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accident Sickness &amp; Unemployment</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Voluntary Contribution (AVC)</fullName>
    </customValue>
    <customValue>
        <fullName>Annuity</fullName>
    </customValue>
    <customValue>
        <fullName>Cash ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Critical Illness Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Current Account</fullName>
    </customValue>
    <customValue>
        <fullName>Defined Benefit</fullName>
    </customValue>
    <customValue>
        <fullName>Defined Contribution</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Equity Holding</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Gilt/Bond Holding</fullName>
    </customValue>
    <customValue>
        <fullName>Endowment</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Investment Scheme (EIS)</fullName>
    </customValue>
    <customValue>
        <fullName>Family Income Benefit</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Term Deposit</fullName>
    </customValue>
    <customValue>
        <fullName>General Investment Account</fullName>
    </customValue>
    <customValue>
        <fullName>Help To Buy ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Income Protection</fullName>
    </customValue>
    <customValue>
        <fullName>Inheritance Tax Investment Service</fullName>
    </customValue>
    <customValue>
        <fullName>Inheritance Tax Investment Service ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Junior ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Junior ISA / Child Trust Fund</fullName>
    </customValue>
    <customValue>
        <fullName>Life &amp; Critical Illness Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Life Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Life Cover (Whole of Life)</fullName>
    </customValue>
    <customValue>
        <fullName>Lifetime ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Offset Mortgage Cash Account</fullName>
    </customValue>
    <customValue>
        <fullName>Offshore Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Onshore Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Peer-to-Peer/Innovative Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Peer-to-Peer/Innovative Finance ISA</fullName>
    </customValue>
    <masterLabel>Financial Product Subtypes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory  {
    
    public static List<Account> createHousehold (Integer numClients, Integer numChildren, String identifier) {
        String HouseholdRecordTypeDevName = 'IndustriesHousehold';
        String PersonRecordTypeDevName = 'PersonAccount';
        String HouseholdSourceIdentifier = 'TestDataFactory';   
        List<Account> accounts = new List<Account>();
        Account household = new Account(Name = 'Test Household', AccountSource = HouseholdSourceIdentifier, AccountNumber = identifier, RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(HouseholdRecordTypeDevName).getRecordTypeId());
        accounts.add(household);
        
        for( Integer i = 0; i < numClients; i++) {
            Account a = new Account(FirstName = 'TestClient ' + i, LastName = 'Client', AccountNumber = identifier, RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(PersonRecordTypeDevName).getRecordTypeId());
            if ( Math.mod(i + 1, 2) == 0 ){
                a.FinServ__PreferredName__pc = 'TestytestyClient ' + i;
            }
            accounts.add(a);
        }
        
        for( Integer i = 0; i < numChildren; i++) {
            Account a = new Account(FirstName = 'TestChild ' + i, LastName = 'Child', AccountNumber = identifier, RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(PersonRecordTypeDevName).getRecordTypeId()); 
            accounts.add(a);
        }
        insert accounts;
        
        String householdId;
        for (Account acc : accounts){
            if ( householdId == null && acc.RecordTypeId == Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(HouseholdRecordTypeDevName).getRecordTypeId() ){
                householdId = acc.Id;
            }
        }
        
        List<Account> personAccounts = [SELECT Id, PersonContactId, RecordTypeId, LastName FROM Account WHERE AccountNumber =: identifier];
        
        List<AccountContactRelation> relationships = new List<AccountContactRelation>();
        AccountContactRelation tempRelationship = new AccountContactRelation( AccountId = householdId );
        for (Account acc : personAccounts){
            if ( acc.RecordTypeId == Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(PersonRecordTypeDevName).getRecordTypeId() && acc.LastName == 'Client' ){
                tempRelationship.ContactId = acc.PersonContactId;
                tempRelationship.FinServ__PrimaryGroup__c = true;
                tempRelationship.Roles = 'Client';
                relationships.add(tempRelationship);
                tempRelationship = new AccountContactRelation( AccountId = householdId );                
            } else if ( acc.RecordTypeId == Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(PersonRecordTypeDevName).getRecordTypeId() && acc.LastName == 'Client' ) {
                tempRelationship.ContactId = acc.PersonContactId;
                tempRelationship.FinServ__PrimaryGroup__c = true;                
                tempRelationship.Roles = 'Child';
                relationships.add(tempRelationship);
                tempRelationship = new AccountContactRelation( AccountId = householdId );
            }
        }
        insert relationships;
        return accounts;
    }
    
    public static Advice__c createAdvice (Id HouseholdId, Integer numLOAs) {
        String HouseholdSourceIdentifier = 'TestDataFactory';
        householdId = [SELECT Id FROM Account WHERE AccountSource =: HouseholdSourceIdentifier LIMIT 1].Id;
        String adviceRecordTypeDevName = 'Advice_RT_General_Advice';
        Advice__c advice = new Advice__c(
            Advice_Household__c = householdId,
            RecordTypeId = Schema.SObjectType.Advice__c.getRecordTypeInfosByDeveloperName().get(adviceRecordTypeDevName).getRecordTypeId(),
            New_or_existing_client__c = 'New',
            Partner__c = [ SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ].Id,
            Fact_find_requirements__c = 'Not required',
            Scope_of_advice_status__c = 'Not required',
            G_Drive_Advice_Folder__c = 'google.com',
            Update_valuations__c = 'No',
            New_LOAs_required__c = 'Yes',
            Advice_confirmed_with_client__c = 'Yes', 
            Ready_to_start_data_gathering__c = true,
            Advice_Status__c = 'Data Gathering',
            Subject__c = 'Test Advice',
            Name = 'Test Advice'
        );
        
        insert advice;
        
        if( numLOAs != 0){
            Public_Provider_Names__c publicProvider = new Public_Provider_Names__c (Name = 'Test provider');
            insert publicProvider;
            Provider_Database__c providerDB = new Provider_Database__c (Name = 'John Smith', Provider_Name__c = 'Test provider DB');
            insert providerDB;
            List<AccountContactRelation> customers = [SELECT Id, Contact.AccountId, Roles FROM AccountContactRelation WHERE AccountId =: householdId];
            String client1Id;
            String client2Id;
            for(AccountContactRelation customer : customers) {
                if(customer.Roles == 'Client' && client1Id == null){
                    client1Id = customer.Contact.AccountId;
                } else if (customer.Roles == 'Client' && client2Id == null){
                    client2Id = customer.Contact.AccountId;
                }
            }
            
            List<FinServ__FinancialAccount__c> productsCreate = new List<FinServ__FinancialAccount__c>();
            
            for(AccountContactRelation customer : customers) {
                Integer i;
                for( i = 0 ; i < numLOAs; i++) {
                    FinServ__FinancialAccount__c product = new FinServ__FinancialAccount__c(
                        Name = 'Test Product ' + i,
                        Subtype__c  = 'Stocks & Shares ISA',
                        FinServ__PrimaryOwner__c = customer.Contact.AccountId,
                        Household__c = householdId,
                        FinServ__Ownership__c = 'Individual',
                        FinServ__Status__c = 'Open',
                        Public_Provider_Name__c = publicProvider.Id,
                        Provider_Contact_Details__c = providerDB.Id,
                        RecordTypeId = Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByDeveloperName().get('FP_Stocks_Shares_ISA').getRecordTypeId()
                    );
                    productsCreate.add(product);
                }
            }
            
            FinServ__FinancialAccount__c product = new FinServ__FinancialAccount__c(
                Name = 'Test joint account',
                Subtype__c  = 'Current Account',
                FinServ__PrimaryOwner__c = client1Id,
                FinServ__JointOwner__c = client2Id,
                FinServ__Ownership__c = 'Joint',
                Household__c = householdId,
                FinServ__Status__c = 'Open',
                Public_Provider_Name__c = publicProvider.Id,
                Provider_Contact_Details__c = providerDB.Id,
                RecordTypeId = Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByDeveloperName().get('FP_Current_Account').getRecordTypeId()
            );
            productsCreate.add(product);
            
            insert productsCreate;
            
            List<LOA__c> loasCreate = new List<LOA__c>();
            for( FinServ__FinancialAccount__c prod : productsCreate){
                LOA__c loa = new LOA__c(
                    Name = 'Test LOA',
                    LOA_Financial_Account__c = prod.Id,
                    Household_Lookup__c = householdId,
                    MainLOAStatus__c = 'LOA Received Awaiting Information',
                    Date_LOA_sent_to_provider__c = Date.today(),
                    Date_LOA_accepted_by_provider__c = Date.today(),
                    Date_Last_Chased__c = Date.today(),
                    RecordTypeId = Schema.SObjectType.LOA__c.getRecordTypeInfosByDeveloperName().get('Pre_LOA').getRecordTypeId() 
                );
                loasCreate.add(loa);
            }
            insert loasCreate;
            
            List<LOA_to_Advice__c> ltas = new List<LOA_to_Advice__c>();
            for( LOA__c loaLoop : loasCreate){
                LOA_to_Advice__c lta = new LOA_to_Advice__c(
                    Advice__c = advice.Id,
                    LOA__c = loaLoop.Id
                );
                ltas.add(lta);
            }
            insert ltas;
        }
        return advice;
    }
}