force-app/main/default/objects/Account/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Junior Policy Holder</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Verifying</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Reported Deceased</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>To be classified</fullName>
            </value>
            <value>
                <fullName>Forgotten</fullName>
            </value>
            <value>
                <fullName>Split</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Household_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Household_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to primary household from person account</description>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Household_Lookup on the Account object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Person Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/utm_medium__c.field-meta.xml
<CustomField>
    <fullName>utm_medium__c</fullName>
    <description>Marketing tracking field to capture medium of lead came through</description>
    <label>utm_medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__Status__c.field-meta.xml
<CustomField>
    <fullName>FinServ__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Fulfilment</fullName>
            </value>
            <value>
                <fullName>Not Taken Up</fullName>
            </value>
            <value>
                <fullName>Deleted by client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Primary Owner&#39;s household</inlineHelpText>
    <label>Household Lookup</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household.

(Admin message: lookup filter criteria not met on Household on the financial product object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOA__c/LOA__c.object-meta.xml
<CustomObject>
    <label>LOA</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LOA__c/fields/Household_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Household_Lookup__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on household_lookup__c on the LOA__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LOAs</relationshipLabel>
    <relationshipName>HouseholdLOAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>false</active>
    <label>zDel Test</label>
</RecordType>

force-app/main/default/classes/fake_data_factory_v2_test.cls
@isTest(SeeAllData=true)
public class fake_data_factory_v2_test {
    
	/**
	* TITLE:	Create test household test class
	* GOAL:		Test the creation of a test household
	* NOTES: 	SeeAllData is true so that task information records are visible
	**/
    
    @istest
    static void test_household_creation(){
        Integer num_clients = 2;
        Integer num_children = 3;
        String status = 'Active';
        String identifier = 'cth_test_run';
        String profile_type = 'Full'; 
        fake_data_factory_v2 cth = new fake_data_factory_v2();
        String household_id = cth.create_household(identifier, num_clients, num_children, status, profile_type);
        
        Account[] accounts = [SELECT Id FROM Account WHERE FinServ__Status__c =: status and utm_medium__c =: identifier];
        AccountContactRelation[] acrs = [SELECT Id, Roles FROM AccountContactRelation WHERE FinServ__SourceSystemId__c =: identifier];
        
        System.assert(num_clients + num_children + 1 == accounts.size()); // Check that there is an account for the household and each client and child. 
        
        // Check that there is a relationship for each client and child.
        Integer num_child_relationships = 0;
        Integer num_client_relationships = 0;      
        for(AccountContactRelation acr : acrs){
            if(acr.Roles == 'Client'){
                num_client_relationships++;
            } else if(acr.Roles == 'Child'){
                num_child_relationships++;
            }
        }
        System.assert(num_child_relationships == num_children); 
        System.assert(num_client_relationships == num_clients);
    }
    
    @istest
    static void test_advice_creation(){
        Integer num_clients = 2;
        Integer num_products = 1;
        Integer num_children = 0;
        String status = 'Active';
        String identifier = 'cth_test_run_advice';
        String profile_type = 'Full'; 
        fake_data_factory_v2 cth = new fake_data_factory_v2();
        Id household_id = cth.create_household(identifier, num_clients, num_children, status, profile_type);
        Advice__c advice = cth.create_advice(identifier, num_products, household_id);
        
        // Get the financial products and LOAs back
        FinServ__FinancialAccount__c[] financial_products = [SELECT Id FROM FinServ__FinancialAccount__c WHERE Household__c =: household_id];
        LOA__c[] loas = [SELECT Id FROM LOA__c WHERE Household_Lookup__c =: household_id];
        
        //System.assert(num_clients * num_products + 1 == financial_products.size()); // Check that there is a financial product for each client plus a joint product
        System.assert(num_clients * num_products + 1 == loas.size()); // Check that there is an LOA for each client plus a joint product
    }
}