force-app/main/default/objects/Account/fields/Household_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Household_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up to primary household from person account</description>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Household_Lookup on the Account object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Person Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/EmailConfiguration__c.object-meta.xml
<CustomObject>
    <description>Holds the details of emails that is used to drive automation and business validation.</description>
    <label>Email Configuration</label>
    <nameField>
        <label>Email Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailConfiguration__c/fields/ClientsAddressed__c.field-meta.xml
<CustomField>
    <fullName>ClientsAddressed__c</fullName>
    <description>Indicates if one or both clients should be included in an email</description>
    <label>Clients addressed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>One only</fullName>
            </value>
            <value>
                <fullName>User defined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name of the email template this email configuration is associated with.</description>
    <externalId>true</externalId>
    <inlineHelpText>Must match the developer name of the email template.</inlineHelpText>
    <label>Developer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Necessity__c.field-meta.xml
<CustomField>
    <fullName>Necessity__c</fullName>
    <label>Necessity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfilment__c/Fulfilment__c.object-meta.xml
<CustomObject>
    <description>An object to store the progress of fulfilling recommendations</description>
    <label>Fulfilment</label>
    <nameField>
        <displayFormat>Flfl-{0000000}</displayFormat>
        <label>Fulfilment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The advice that the recommendation this is fulfilling was associated to</description>
    <label>Advice</label>
    <referenceTo>Advice__c</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The household that this fulfilment is related to</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment__c/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation which resulted in this fulfilment</description>
    <label>Recommendation</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/Recommendation__c.object-meta.xml
<CustomObject>
    <description>Contains all the information given by planners when making a recommendation of an action for a change in a clients financial circumstances.</description>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>Rec-{0000000}</displayFormat>
        <label>Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The advice that this recommendation is a part of</description>
    <label>Advice</label>
    <referenceTo>Advice__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The household to which this recommendation is being made.</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Recommendation__c/fields/PreRequisiteRecommendation__c.field-meta.xml
<CustomField>
    <fullName>PreRequisiteRecommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the recommendation which must be completed before this one can be done</description>
    <label>Pre-requisite recommendation destination</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>PrimaryOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the main client that this recommendation relates to, the primary owner of the destination product</description>
    <label>Primary owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation (Primary owner)</relationshipLabel>
    <relationshipName>Recommendation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailAddressRecipients.cls
public class EmailAddressRecipients {
    public String objectIdString{get;set;}
	public String emailTemplateDevName{get;set;}
    private Id accountId;
    private Id householdId;
    Public EmailConfiguration__c emailConfig;
    public String hiString;
    
    public Configs emailAddressRecipients() {
        Configs result = new Configs();
        if(String.isBlank(objectIdString)){
            objectIdString = ApexPages.currentPage().getParameters().get('objectIdString');
        }
        Id objectId = Id.valueOf(objectIdString);
        String objectApiName = objectId.getSObjectType().getDescribe().getName();
        switch on objectApiName {
            when 'Fulfilment__c' {
                Fulfilment__c flfl = [SELECT Id, Recommendation__r.PrimaryOwner__c, Household__c FROM Fulfilment__c WHERE Id =: objectId LIMIT 1];
                result.accountId = flfl.Recommendation__r.PrimaryOwner__c;
                result.householdId = flfl.Household__c;
            }
            when 'Account' {
                Account acc = [SELECT Id, RecordType.DeveloperName, Household_Lookup__c FROM Account WHERE Id =: objectId LIMIT 1];
                if ( acc.RecordType.DeveloperName == 'IndustriesHousehold' ) {
                    result.householdId = objectId;
                	result.accountId = null;
                } else {
                    result.accountId = objectId;
                	result.householdId = acc.Household_Lookup__c;
                }
            }
            when 'Advice__c' {
                Advice__c adv = [SELECT Id, Advice_Household__c FROM Advice__c WHERE Id =: objectId LIMIT 1];
                result.accountId = null;
                result.householdId = adv.Advice_Household__c;
            }
            when else {
                result.accountId = '001Qz00000LlyOAIAZ';
                result.householdId = '001Qz00000LmDDTIA3';
            }
            
        }
        
        if(String.isBlank(emailTemplateDevName)){
            emailTemplateDevName = ApexPages.currentPage().getParameters().get('emailTemplateDevName');
        }
        
        result.emailConfig = [SELECT Id, ClientsAddressed__c, Necessity__c FROM EmailConfiguration__c WHERE DeveloperName__c =: emailTemplateDevName LIMIT 1];  
        return result;
    }
        
    
    public String getAddressRecipients() {
        Configs config = emailAddressRecipients();
        accountId = config.accountId;
        householdId = config.householdId;
        emailConfig = config.emailConfig;
        if( emailConfig.ClientsAddressed__c == 'All' || accountId == null ) {
            return getHiStringHousehold(householdId, emailConfig);
        } else if ( emailConfig.ClientsAddressed__c == 'One only' ) {
            return getHiStringIndividual(accountId);
        } 
        return '';
    }
    
    public String getHiStringIndividual(Id accountId) {
		Account client = [SELECT Id, AddressedName__pc FROM Account WHERE Id =: accountId LIMIT 1];
        return 'Hi ' + client.AddressedName__pc;
    }
    
    public String getHiStringHousehold(Id householdId, EmailConfiguration__c emailConfig) {
        AccountHouseholdMembers ahm = new AccountHouseholdMembers();
        AccountHouseholdMembers.HouseholdMemberRequest hmr = new AccountHouseholdMembers.HouseholdMemberRequest();

        
        hmr.householdId = householdId;
        Set<String> roles = new Set<String>();
        roles.add('Client');

        hmr.roles = roles;

        Map<String, List<Account>> hmrResult = ahm.getHouseholdMembers(hmr).memberAccountsByRole;

        
        List<String> recipients = new List<String>();

        for( Account household_member : hmrResult.get('Client') ) {
            if (emailConfig.Necessity__c == 'Required' || household_member.ServiceContactPreferences__pc == 'All emails') {
            	recipients.add(household_member.FinServ__PreferredName__pc);
           	}
        }
        recipients.sort();
        
        // Loop through the recipients to produce the recipient details to be displayed in the email
        Integer n = recipients.size();
        Integer i = 0;
        hiString = 'Hi ';
        
        if ( n == 1 ) {
            hiString = hiString + recipients[0] + ',';
        } else {
            i = 0;
            for(String recipient : recipients){
                if ( i < n - 2 ) {
                    hiString = hiString + recipients[i] + ', ';
                } else if ( i == n - 2 ) {
                    hiString = hiString + recipients[i] + ' & ';
                } else {
                    hiString = hiString + recipients[i] + ',';
                }
                i = i + 1;
            }
        }
        return hiString;  
    }
    
    public class Configs {
        public Id accountId;
        public Id householdId;
        public EmailConfiguration__c emailConfig;
    }

}