force-app/main/default/objects/Account/fields/Intelligent_Office_ID__c.field-meta.xml
<CustomField>
    <fullName>Intelligent_Office_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>https://www.intelligent-office.net/nio/clientDashboard/23541387/dashboard/0

The numbers in the URL</inlineHelpText>
    <label>Intelligent Office ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_system_log__c/OW_system_log__c.object-meta.xml
<CustomObject>
    <description>This object is intended to capture technical logs for monitoring and debugging purposes. Automated processes can write failures and successes to it to allow us to understand how they are performing.</description>
    <label>System log</label>
    <nameField>
        <displayFormat>SL-{0}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_system_log__c/fields/OW_detail__c.field-meta.xml
<CustomField>
    <fullName>OW_detail__c</fullName>
    <description>A text area field in which detail can be captured as part of the process, specific to what needs to be captured as part of that automation.</description>
    <label>Detail</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OW_system_log__c/fields/OW_error__c.field-meta.xml
<CustomField>
    <fullName>OW_error__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if known to be an error that needs addressing or attention.</description>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OW_system_log__c/fields/OW_log_source__c.field-meta.xml
<CustomField>
    <fullName>OW_log_source__c</fullName>
    <description>The component that has created this log. E.g. the name of the apex class or flow.</description>
    <label>Log source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OW_system_log__c/fields/OW_log_type__c.field-meta.xml
<CustomField>
    <fullName>OW_log_type__c</fullName>
    <description>The type of log, as specified by the automation that creates this. This will allow aggregate monitoring of particular processes.</description>
    <label>Log type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_system_log__c/fields/OW_response_code__c.field-meta.xml
<CustomField>
    <fullName>OW_response_code__c</fullName>
    <description>Intended to capture response codes from APIs</description>
    <label>Response code</label>
    <precision>7</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OW_system_log__c/fields/OW_source_type__c.field-meta.xml
<CustomField>
    <fullName>OW_source_type__c</fullName>
    <description>The type of component that created this log - e.g. Apex class.</description>
    <label>Source type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_system_log__c/fields/OW_status__c.field-meta.xml
<CustomField>
    <fullName>OW_status__c</fullName>
    <description>Intended to capture the status of API responses but could also capture similar short messages.</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/OW_update_io_id.cls
public class OW_update_io_id {
    // This class manages the outbound HTTP request to a portal API to let it know of a change to the IO ID of a customer
    // The class contains an invocable method to allow it to be called as part of a flow
    // It also contains a future method so the requests are made asynchronously and can be made after the update of customer records (a DML statement)
    
    //The invocable method - this takes a list of customers IDs from a flow and loops through them, calling the future method for each
    @InvocableMethod(label = 'Sync IO ID to portal' description = 'Given a list of customer accounts, make a callout to a portal endpoint to update the IO ID.' category = 'OW portal')
    public static void process_accounts(List<List<Account>> accounts) {
        
        for(Account account : (List<Account>)accounts[0]){
            make_callout(account.Id, account.Intelligent_Office_ID__c);
        }      
    }
    
    //The future method - this takes a single customer ID and makes a call to the portal API asking that the RTQ email is sent
    @future(callout=true)
    public static void make_callout(Id customer_id, String io_id){
        
        // Debug line to check that IDs are being received: System.debug('In the callout method, customer ID = ' + customerId);
        //Initiate the call
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        
        //Construct the call
        request.setEndpoint('callout:OW_portal/v0/jobs/update-io-id/');
        request.setMethod('PUT');
        request.setHeader('Content-Type', 'application/json');
        request.setBody('{"record_id": "' + customer_id + '", "io_id": "' + io_id + '"}'); 
        
        //Make the call
        HttpResponse response = http.send(request);
        
        // Log the outcome for monitoring purposes
        if (response.getStatusCode() != 200) {
            OW_system_log__c systemLog = new OW_system_log__c(OW_log_type__c = 'Update IO ID request', OW_log_source__c = 'UpdateIOID', OW_source_type__c = 'Apex Class', OW_detail__c = 'Error requesting IO ID update for '+ customer_id, OW_response_code__c = response.getStatusCode(), OW_status__c = response.getStatus(), OW_error__c = true);
            insert systemLog;
        } else {
            OW_system_log__c systemLog = new OW_system_log__c(OW_log_type__c = 'Update IO ID request',  OW_log_source__c = 'UpdateIOID', OW_source_type__c = 'Apex Class', OW_detail__c = 'Request to update IO ID in the portal made successfully for  '+ customer_id, OW_response_code__c = response.getStatusCode(), OW_status__c = response.getStatus(), OW_error__c = false);
            insert systemLog;
        }
    }
}