force-app/main/default/objects/Account/fields/OW_dedicated_specialist__c.field-meta.xml
<CustomField>
    <fullName>OW_dedicated_specialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the dedicated specialist user assigned to this household</description>
    <label>Dedicated specialist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Advice_Status__c.field-meta.xml
<CustomField>
    <fullName>Advice_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
                <default>true</default>
                <label>Setup</label>
            </value>
            <value>
                <fullName>Data gathering</fullName>
            </value>
            <value>
                <fullName>Risk Call</fullName>
            </value>
            <value>
                <fullName>Ready for suitability</fullName>
            </value>
            <value>
                <fullName>Suitability in progress</fullName>
            </value>
            <value>
                <fullName>Prepare advice</fullName>
            </value>
            <value>
                <fullName>Present advice</fullName>
            </value>
            <value>
                <fullName>Deck complete</fullName>
            </value>
            <value>
                <fullName>Await decision</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>In fulfilment</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Suitability Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Meeting held</fullName>
                <isActive>false</isActive>
                <label>Meeting held</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/AdviceType__c.field-meta.xml
<CustomField>
    <fullName>AdviceType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A reference to advice type where variables are held that control business logic of the advice record.</description>
    <label>Advice type</label>
    <referenceTo>AdviceType__c</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Assigned_planner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_planner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suitability planner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_planner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/DataAnalysisStatus__c.field-meta.xml
<CustomField>
    <fullName>DataAnalysisStatus__c</fullName>
    <description>Indicates the progress of data analysis</description>
    <label>Data analysis status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not required</fullName>
            </value>
            <value>
                <fullName>Not started</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/DeckStatus__c.field-meta.xml
<CustomField>
    <fullName>DeckStatus__c</fullName>
    <label>Deck status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planner review</fullName>
            </value>
            <value>
                <fullName>Resolve planner comments</fullName>
            </value>
            <value>
                <fullName>Partner review</fullName>
            </value>
            <value>
                <fullName>Resolve partner comments</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/IsPriority__c.field-meta.xml
<CustomField>
    <fullName>IsPriority__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by planning to capture advice cases that have been prioritised in agreement with the partner.</description>
    <label>Priority</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/NarrativeStatus__c.field-meta.xml
<CustomField>
    <fullName>NarrativeStatus__c</fullName>
    <label>Narrative status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planner review</fullName>
            </value>
            <value>
                <fullName>Resolve planner comments</fullName>
            </value>
            <value>
                <fullName>Partner review</fullName>
            </value>
            <value>
                <fullName>Resolve partner comments</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/New_or_existing_client__c.field-meta.xml
<CustomField>
    <fullName>New_or_existing_client__c</fullName>
    <label>New or existing client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/OW_dedicated_specialist__c.field-meta.xml
<CustomField>
    <fullName>OW_dedicated_specialist__c</fullName>
    <formula>Advice_Household__r.OW_dedicated_specialist__r.FirstName &amp; &quot; &quot; &amp; Advice_Household__r.OW_dedicated_specialist__r.LastName</formula>
    <label>Dedicated specialist</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/OW_review__c.field-meta.xml
<CustomField>
    <fullName>OW_review__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Concurrent Annual Review to Advice</description>
    <inlineHelpText>This field can be updated by linking to this advice from a review.</inlineHelpText>
    <label>Review</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The advice and annual review must be linked to the same household.

(Admin message: filter criteria on OW_review__c field on the Advice__c object)</errorMessage>
        <filterItems>
            <field>$Source.Advice_Household__c</field>
            <operation>equals</operation>
            <valueField>OW_review__c.OW_household__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OW_review__c</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/PlanningNotes__c.field-meta.xml
<CustomField>
    <fullName>PlanningNotes__c</fullName>
    <description>For the planning team to capture notes as part of managing their work.</description>
    <label>Planning notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/RetirementCallStatus__c.field-meta.xml
<CustomField>
    <fullName>RetirementCallStatus__c</fullName>
    <description>This field captures whether the status around retirement call for a given bit of advice - is one required or not and whether it&#39;s complete, if it was required.</description>
    <label>Retirement call status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT_REQUIRED</fullName>
                <label>Not required</label>
            </value>
            <value>
                <fullName>REQUIRED</fullName>
                <label>Required</label>
            </value>
            <value>
                <fullName>PRESENT</fullName>
                <label>Present content</label>
            </value>
            <value>
                <fullName>COMPLETE</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>NEVER_REQUIRED</fullName>
                <label>Never required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/RiskCallDate__c.field-meta.xml
<CustomField>
    <fullName>RiskCallDate__c</fullName>
    <description>The date of the risk call</description>
    <label>Risk call date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/RiskCallStatus__c.field-meta.xml
<CustomField>
    <fullName>RiskCallStatus__c</fullName>
    <defaultValue>&quot;Not ready&quot;</defaultValue>
    <description>Indicates the progress towards the risk call</description>
    <label>Risk call status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
                <default>true</default>
                <label>Not required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/recordTypes/Withdrawal.recordType-meta.xml
<RecordType>
    <fullName>Withdrawal</fullName>
    <active>true</active>
    <description>Lump sum or regular withdrawals from an ISA or GIA only.</description>
    <label>Withdrawal</label>
</RecordType>

force-app/main/default/objects/AdviceType__c/AdviceType__c.object-meta.xml
<CustomObject>
    <description>Models the types of advice that we provide to customers and how things vary between them. Used to drive business logic on actual advice.</description>
    <label>Advice Type</label>
    <nameField>
        <label>Advice Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AdviceType__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name for an advice type. Used to provide consistency in business logic across environments.</description>
    <label>Developer Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OW_review__c/OW_review__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage the review process with existing clients. It&#39;s a fairly lightweight place to manage the upcoming reviews and track the initial conversations. The resulting workflows - preparation of decks, advice etc - are all managed in the advice object.</description>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_review__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <inlineHelpText>Does the advice make sense and seem to be both suitable, but also the right thing for the client? If not, please flat to planner/head planner</inlineHelpText>
    <label>Advice</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OW_review__c/fields/Assigned_Planner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Planner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the user who is the assigned planner for the review.</description>
    <label>Assigned planner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Annual_Reviews1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OW_review__c/fields/OW_due_date__c.field-meta.xml
<CustomField>
    <fullName>OW_due_date__c</fullName>
    <description>The final day of the customer&#39;s annual review month. This value is set at the time of creation so that if the annual review month changes for the future, this due date does not.</description>
    <label>Due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AdvicePlanningPioritisationHelper.cls
/*********************************************************
Apex Class Name    : AdvicePlanningPioritisationHelper
Created Date       : 2024-09-10
@description       : This class is a helper for a planning advice management/prioritisation LWC. Runs without sharing so summary level view always visible. 
@author            : Cian Morrissey
Modification Log:
Date         Author                               Modification
2024-09-10   Cian Morrissey                       Initial Version
*********************************************************/
public without sharing class AdvicePlanningPioritisationHelper {

    /**********************************************************
    @Method Name    : getAdvice
    @author         : Cian Morrissey
    @description    : This method runs a query to get the advice data then returns it
    @param          : N/A
    @return         : advice - the list of advice returned
    *********************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getAdvice(){
        List<Map<String, Object>> adviceDataList = new List<Map<String, Object>>();
        List<String> adviceStatuses = new List<String>{'Data gathering','Risk Call','Suitability in progress','Prepare advice'};
        List<Advice__c> adviceRecords = [SELECT Id, Name, New_or_existing_client__c, Advice_Household__r.OW_dedicated_specialist__r.Name, PlanningNotes__c, IsPriority__c, AdviceType__r.Name, AdviceType__r.DeveloperName__c, Advice_Household__r.Name,  Assigned_planner__c, Assigned_planner__r.Name, Advice_status__c, Partner__r.Name, RetirementCallStatus__c, RiskCallStatus__c, RiskCallDate__c, NarrativeStatus__c, DeckStatus__c, OW_review__c, OW_review__r.OW_due_date__c FROM Advice__c WHERE Advice_status__c IN :adviceStatuses WITH SECURITY_ENFORCED ORDER BY Advice_status__c DESC, DeckStatus__c DESC, NarrativeStatus__c DESC, RiskCallStatus__c DESC, RiskCallDate__c ASC NULLS LAST, DataAnalysisStatus__c DESC, DataGatheringStatus__c DESC, CreatedDate ASC];
        String urlPrefix = URL.getOrgDomainURL().toExternalForm() + '/';

        // Loop data to sort it
        for(Advice__c advice : adviceRecords){
            Map<String, Object> adviceData = new Map<String, Object>();
        	adviceData.put('Id', String.valueOf(advice.Id));
            adviceData.put('Name', advice.Name);
            adviceData.put('RecordLink', urlPrefix + advice.Id);
            adviceData.put('Status', advice.Advice_Status__c);
            adviceData.put('Planner', advice.Assigned_planner__r.Name);
            adviceData.put('AdviceType', advice.AdviceType__r.Name);
            adviceData.put('NewOrExisting', getOnboardingOrExisting(advice));
            adviceData.put('RiskCallDate', advice.RiskCallDate__c);
            adviceData.put('AnnualReviewDate', advice.OW_review__r.OW_due_date__c);
            adviceData.put('NarrativeStatus', advice.NarrativeStatus__c);
            adviceData.put('DeckStatus', advice.DeckStatus__c);
            adviceData.put('RiskCallStatus', advice.RiskCallStatus__c);
            adviceData.put('Partner', advice.Partner__r.Name);
            adviceData.put('IsPriority__c', advice.IsPriority__c);
            adviceData.put('PlanningNotes__c', advice.PlanningNotes__c);
            adviceData.put('Stage', getStage(advice));
            adviceData.put('RetirementCallStatus', getRetirementCallStatus(advice.RetirementCallStatus__c));
            adviceData.put('Specialist', advice.Advice_Household__r.OW_dedicated_specialist__r.Name);
            adviceDataList.add(adviceData);
        }
        return adviceDataList;
    }

    private static String getOnboardingOrExisting(Advice__c advice) {
        if(advice.New_or_existing_client__c == 'New'){
            return 'NEW';
        } else if (advice.AdviceType__r.DeveloperName__c == 'TOP_UP'){
            return 'TOP_UP';
        } else if (advice.AdviceType__r.DeveloperName__c == 'WITHDRAWAL'){
            return 'WITHDRAWAL';
        } else {
            return 'EXISTING';
        }
    }

    private static String getRetirementCallStatus(String retirementCallStatus){
        if(!String.isEmpty(retirementCallStatus)){
            return UtilityString.convertCaseUpperSnakeToSentence(retirementCallStatus);
        } else {
            return '';
        }
    }

    private static String getStage(Advice__c advice){
        String narrativeStatus = advice.NarrativeStatus__c;
        string deckStatus = advice.DeckStatus__c;
        String status = advice.Advice_Status__c;
        String stage;
        if(status == 'Data gathering'){
            stage = status;
        } else if(status == 'Risk Call'){
            stage = status + ' | ' + advice.RiskCallStatus__c;
        } else if (status == 'Suitability in progress' || status == 'Prepare advice'){
            if (narrativeStatus != '' && narrativeStatus != 'Complete'){
                stage = 'Narrative | ' + narrativeStatus;
            } else if (narrativeStatus == 'Complete') {
                stage = 'Deck | ' + deckStatus;
            }
        } 
        return stage;
    }
}