force-app/main/default/objects/Account/fields/OW_Portal_Activated__c.field-meta.xml
<CustomField>
    <fullName>OW_Portal_Activated__c</fullName>
    <label>Portal Activation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activation Email Sent</fullName>
            </value>
            <value>
                <fullName>Activation Email Expired</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PortalAccountStatus__c.field-meta.xml
<CustomField>
    <fullName>PortalAccountStatus__c</fullName>
    <description>Business use: to understand the clients portal status. Shows if client has had their password link sent to them, if their link has expired, or if they have recieved the link and set their password successfully, or if they have been blocked. 
Tech use: Is set by the portal to indicate what their portal status is 
Data Inputters: System based on portal status
Data Users: Users looking to understand if client has a portal account</description>
    <label>Portal account status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Invite expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SandboxSetupAnonymise.cls
public with sharing class SandboxSetupAnonymise implements Database.Batchable<sObject> {

    final private static String NATIONAL_INSURANCE_NUMBER = 'QQ123456A';
    final private static Boolean RUN_ALLOWED = Utility.isSandbox || Test.isRunningTest() ? true : false;
    
    // Query all person accounts in the system
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id FROM Account WHERE IsPersonAccount = true';
        if(!RUN_ALLOWED){
            query += ' LIMIT 0';    // Limit to 0 rows if this is somehow run in production 
        }
        return Database.getQueryLocator(query);
    }

    // Anonymise then update the person accounts
    public void execute(Database.BatchableContext bc, List<Account> people) {
        if(RUN_ALLOWED && !people.isEmpty()){
            for(Account person : people) {
                person.PersonEmail = null;
                person.Phone = null;
                person.PersonMobilePhone = null;
                person.Secondary_Email__pc = null;
                person.National_Insurance_Number__pc = NATIONAL_INSURANCE_NUMBER;
                DataFactoryNameGenerator fakeNameClass = new DataFactoryNameGenerator();
                DataFactoryNameGenerator.RandomName fakeName = fakeNameClass.generateName(true, true, true);
                person.FirstName = fakeName.firstName;
                person.LastName = fakeName.lastName;
                person.FinServ__PreferredName__pc = fakeName.preferredName;
                person.OW_portal_activated__c = null;
                person.PortalAccountStatus__c = null;
            }
            update people;
        }
    }
    
    public void finish(Database.BatchableContext bc) {
    }

    public class SandboxSetupException extends Exception {
    }
}