force-app/main/default/objects/EmailConfiguration__c/EmailConfiguration__c.object-meta.xml
<CustomObject>
    <description>Holds the details of emails that is used to drive automation and business validation.</description>
    <label>Email Configuration</label>
    <nameField>
        <label>Email Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailConfiguration__c/fields/ClientsAddressed__c.field-meta.xml
<CustomField>
    <fullName>ClientsAddressed__c</fullName>
    <description>Indicates if one or both clients should be included in an email</description>
    <label>Clients addressed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>One only</fullName>
            </value>
            <value>
                <fullName>User defined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/CustomPermission__c.field-meta.xml
<CustomField>
    <fullName>CustomPermission__c</fullName>
    <description>If this field has a value, a user must have this custom permission order to send an email of this type</description>
    <inlineHelpText>If this field has a value, a user must have this custom permission order to send an email of this type</inlineHelpText>
    <label>Custom permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the email template</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name of the email template this email configuration is associated with.</description>
    <externalId>true</externalId>
    <inlineHelpText>Must match the developer name of the email template.</inlineHelpText>
    <label>Developer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <description>The email address this email message must come from.</description>
    <label>From</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/GoogleDriveTemplateUrl__c.field-meta.xml
<CustomField>
    <fullName>GoogleDriveTemplateUrl__c</fullName>
    <description>Link to template listed in Google Drive.</description>
    <label>Google drive template URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Necessity__c.field-meta.xml
<CustomField>
    <fullName>Necessity__c</fullName>
    <label>Necessity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/ReviewAtTaxYearEnd__c.field-meta.xml
<CustomField>
    <fullName>ReviewAtTaxYearEnd__c</fullName>
    <description>Does template contain TYE sensitive information such as deadlines, specific dates etc. to be reviewed every tax year end</description>
    <label>Review at tax year end</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of email being sent</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LwcHelperEmailTemplateListTest.cls
/**
 * This class exists exclusively to provide testing coverage for the Email Template List LWC.
 * It should not be used in any other contexts.
 * It generates a creates an email template and email configuration record to display in a table 
 */
@isTest
public with sharing class LwcHelperEmailTemplateListTest {
    
    @isTest
    static void createTemplates() {
        Folder tempFolder = [SELECT Id, Name, Type, DeveloperName FROM Folder WHERE DeveloperName = 'FreeFormEmails' LIMIT 1];
        System.debug(tempFolder);
        
        User currentUser = [ SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
            EmailTemplate emailTemp = new EmailTemplate();
            emailTemp.Name = 'Test';
            emailTemp.FolderId = UserInfo.getUserId();
            emailTemp.Description = 'This is test template';
            //emailTemp.UiType = 'SFX';
        	emailTemp.TemplateType = 'custom';
        	emailTemp.Encoding = 'UTF-8';
        	emailTemp.IsActive = true;
            emailTemp.DeveloperName = 'unique_Test12345';
            emailTemp.TemplateType = 'text';
            System.runAs(currentUser) {
            insert emailTemp;

            EmailConfiguration__c emailConfig = new EmailConfiguration__c();
            emailConfig.Name = 'unique_Test12345';
            emailConfig.DeveloperName__c = 'unique_Test12345';
            emailConfig.ClientsAddressed__c = 'All';
            emailConfig.CustomPermission__c = 'TestPermission';
            emailConfig.Description__c = 'Test';
            emailConfig.ReviewAtTaxYearEnd__c = 'Yes';
            emailConfig.GoogleDriveTemplateUrl__c = 'https://drive.google.com';
            emailConfig.Necessity__c = 'Optional';
            emailConfig.Type__c = 'Service';
            emailConfig.From__c = 'amy@novawm.com';

            insert emailConfig;
        }
        
        EmailTemplate et = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'unique_Test12345' LIMIT 1];
        LwcHelperDynamicRecordList.DataWrapper data = LwcHelperEmailTemplateList.getTemplateData(et.Id);     
        System.AssertEquals(1, data.rows.size());
    }
}