force-app/main/default/objects/EmailConfiguration__c/EmailConfiguration__c.object-meta.xml
<CustomObject>
    <description>Holds the details of emails that is used to drive automation and business validation.</description>
    <label>Email Configuration</label>
    <nameField>
        <label>Email Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailConfiguration__c/fields/AwaitReply__c.field-meta.xml
<CustomField>
    <fullName>AwaitReply__c</fullName>
    <description>Determines whether the related email case should be closed after the related email message using this template is sent. If no reply is expected, the email case is auto closed when the template is sent using the Email Message | Outbound flow. Field was re-labeled for business users to view on Manage email templates page.</description>
    <label>Close after sent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Await a reply</fullName>
            </value>
            <value>
                <fullName>No reply expected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name of the email template this email configuration is associated with.</description>
    <externalId>true</externalId>
    <inlineHelpText>Must match the developer name of the email template.</inlineHelpText>
    <label>Developer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/GoogleDriveTemplateUrl__c.field-meta.xml
<CustomField>
    <fullName>GoogleDriveTemplateUrl__c</fullName>
    <description>Link to template listed in Google Drive.</description>
    <label>Google drive template URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/HasAttachment__c.field-meta.xml
<CustomField>
    <fullName>HasAttachment__c</fullName>
    <description>Does this template include an attachment?</description>
    <label>Has attachment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/ReviewAtTaxYearEnd__c.field-meta.xml
<CustomField>
    <fullName>ReviewAtTaxYearEnd__c</fullName>
    <description>Does template contain TYE sensitive information such as deadlines, specific dates etc. to be reviewed every tax year end</description>
    <label>Review at tax year end</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LwcHelperEmailTemplateList.cls
/*
 * This class exists for the sole purpose of creating a list of all available email templates with their related configuration.
 * It get all templates and their configuration data to display in a list on the Manage Email Templates tab
 */
public with sharing class LwcHelperEmailTemplateList {

    public static LwcHelperDynamicRecordList.DataWrapper getTemplateData(Id contextId) {
        LwcHelperDynamicRecordList.DataWrapper dataWrapper = new LwcHelperDynamicRecordList.DataWrapper();
        dataWrapper.config.keyFieldName = 'TemplateId';

        //Define columns
        LwcHelperDynamicRecordList.ColumnWrapper folderLinkColumn = new LwcHelperDynamicRecordList.ColumnWrapper('Folder', 'Folder.Id', 'url');
        folderLinkColumn.typeAttributes.label.put('fieldName', 'Folder.Name');

        LwcHelperDynamicRecordList.ColumnWrapper nameLinkColumn = new LwcHelperDynamicRecordList.ColumnWrapper('Template Name', 'TemplateId', 'url');
        nameLinkColumn.typeAttributes.label.put('fieldName', 'Name');

        LwcHelperDynamicRecordList.ColumnWrapper googleTemplateLinkColumn = new LwcHelperDynamicRecordList.ColumnWrapper('Google template URL', 'GoogleDriveTemplateUrl__c', 'url');
        googleTemplateLinkColumn.typeAttributes.label.put('fieldName', 'GoogleDriveTemplateUrl__c'); //May not need to define label

        dataWrapper.columns.add(folderLinkColumn);
        dataWrapper.columns.add(nameLinkColumn);
        dataWrapper.columns.add(new LwcHelperDynamicRecordList.ColumnWrapper('Description', 'Description', 'text'));
        dataWrapper.columns.add(googleTemplateLinkColumn);
        dataWrapper.columns.add(new LwcHelperDynamicRecordList.ColumnWrapper('Review at tax year end', 'ReviewAtTaxYearEnd__c', 'text'));
        dataWrapper.columns.add(new LwcHelperDynamicRecordList.ColumnWrapper('Close after send', 'AwaitReply__c', 'text'));
        dataWrapper.columns.add(new LwcHelperDynamicRecordList.ColumnWrapper('Has attachment', 'HasAttachment__c', 'text'));
        dataWrapper.columns.add(new LwcHelperDynamicRecordList.ColumnWrapper('Last modified date', 'LastModifiedDate', 'date'));

        // Define rows
        List<EmailTemplate> emailTemps = [SELECT Id, Name, FolderId, Folder.Name, Description, DeveloperName, LastModifiedDate FROM EmailTemplate ORDER BY Folder.Name];
        Map<String,EmailTemplate> emailTemplateMap = new Map<String,EmailTemplate>();
        for(EmailTemplate emailTempForMap : emailTemps) {
            emailTemplateMap.put(emailTempForMap.DeveloperName, emailTempForMap);
        }
        Map<String,EmailConfiguration__c> emailConfigMap = new Map<String,EmailConfiguration__c>();
        for(EmailConfiguration__c econfig : [SELECT Id, Name, DeveloperName__c, GoogleDriveTemplateUrl__c, AwaitReply__c, ReviewAtTaxYearEnd__c, HasAttachment__c FROM EmailConfiguration__c]) {
            emailConfigMap.put(econfig.DeveloperName__c, econfig);
        }
        String urlPrefix = URL.getOrgDomainURL().toExternalForm() + '/';
        Map<String,String> picklistApiToLabelMapCloseAfterSend = getPicklistApiLabelMapCloseAfterSend();
        Map<String,String> picklistApiToLabelMapTye = getPicklistApiLabelMapTyeDates();
        Map<String,String> picklistApiToLabelMapAttachments = getPicklistApiLabelMapAttachments();

        for(String emailTempDevNames : emailTemplateMap.keySet()) {
            if(emailConfigMap.containsKey(emailTempDevNames)){
                LwcHelperDynamicRecordList.RowWrapper rowWrapper = new LwcHelperDynamicRecordList.RowWrapper();
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('Folder.Id', urlPrefix+emailTemplateMap.get(emailTempDevNames).FolderId));
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('Folder.Name', emailTemplateMap.get(emailTempDevNames).Folder.Name));
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('TemplateId', urlPrefix+emailTemplateMap.get(emailTempDevNames).Id));
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('Name', emailTemplateMap.get(emailTempDevNames).Name));
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('Description', emailTemplateMap.get(emailTempDevNames).Description));
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('GoogleDriveTemplateUrl__c', emailConfigMap.get(emailTempDevNames).GoogleDriveTemplateUrl__c));
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('ReviewAtTaxYearEnd__c', picklistApiToLabelMapTye.get(emailConfigMap.get(emailTempDevNames).ReviewAtTaxYearEnd__c)));
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('AwaitReply__c', picklistApiToLabelMapCloseAfterSend.get(emailConfigMap.get(emailTempDevNames).AwaitReply__c)));
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('HasAttachment__c', picklistApiToLabelMapAttachments.get(emailConfigMap.get(emailTempDevNames).HasAttachment__c)));
                rowWrapper.fields.add(new LwcHelperDynamicRecordList.FieldWrapper('LastModifiedDate', emailTemplateMap.get(emailTempDevNames).LastModifiedDate.toString()));

                    dataWrapper.rows.add(rowWrapper);
            }
        }
        return dataWrapper;
    }

    // Get a map of picklist values to labels so that we can display the labels in the list
    private static Map<String,String> getPicklistApiLabelMapCloseAfterSend(){
        List<Schema.PicklistEntry> picklistItems = EmailConfiguration__c.AwaitReply__c.getDescribe().getPicklistValues();
        Map<String,String> picklistApiLabelMap = new Map<String,String>();
        For(Schema.PicklistEntry picklistItem : picklistItems){
            String label;
            if(picklistItem.getValue() == 'Await a reply'){
                label = 'No';
            } else if(picklistItem.getValue() == 'No reply expected'){
                label = 'Yes';
            }
            picklistApiLabelMap.put(picklistItem.getValue(), label);
        }
        return picklistApiLabelMap; 
    }
    private static Map<String,String> getPicklistApiLabelMapTyeDates(){
        List<Schema.PicklistEntry> picklistItems = EmailConfiguration__c.ReviewAtTaxYearEnd__c.getDescribe().getPicklistValues();
        Map<String,String> picklistApiLabelMap = new Map<String,String>();
        For(Schema.PicklistEntry picklistItem : picklistItems){
            picklistApiLabelMap.put(picklistItem.getValue(), picklistItem.getLabel());
        }
        return picklistApiLabelMap; 
    }
    private static Map<String,String> getPicklistApiLabelMapAttachments(){
        List<Schema.PicklistEntry> picklistItems = EmailConfiguration__c.HasAttachment__c.getDescribe().getPicklistValues();
        Map<String,String> picklistApiLabelMap = new Map<String,String>();
        For(Schema.PicklistEntry picklistItem : picklistItems){
            picklistApiLabelMap.put(picklistItem.getValue(), picklistItem.getLabel());
        }
        return picklistApiLabelMap; 
    }
}