force-app/main/default/objects/ExpectationConfiguration__mdt/ExpectationConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Configuration data for creating expectation from different recommendation types</description>
    <label>Expectation Configuraiton</label>
    <pluralLabel>Expectation Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/ExpectationConfiguration__mdt/fields/DateOffset__c.field-meta.xml
<CustomField>
    <fullName>DateOffset__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of days offset from today the expectation will be for</description>
    <label>Date Offset</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ExpectationConfiguration__mdt/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <description>Indicates whether the configured expectation represents money coming in (CONTRIBUTION) or going out (WITHDRAWL) of the financial product</description>
    <label>Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CONTRIBUTION</fullName>
                <default>true</default>
                <label>CONTRIBUTION</label>
            </value>
            <value>
                <fullName>WITHDRAWL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExpectationConfiguration__mdt/fields/IsRegular__c.field-meta.xml
<CustomField>
    <fullName>IsRegular__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether this expectation configuration is for a regular recurring transaction or a one-off transaction</description>
    <label>Is Regular</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpectationConfiguration__mdt/fields/RecommendationTypeDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>RecommendationTypeDeveloperName__c</fullName>
    <description>The developer name of the recommendation type that this expectation configuration applies to</description>
    <label>Recommendation Type Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpectationConfiguration__mdt/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Specifies whether the expectation applies to the source product, destination product, or both products in a transfer scenario</description>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Destination</fullName>
                <default>true</default>
                <label>Destination</label>
            </value>
            <value>
                <fullName>Source</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExpectationConfiguration__mdt/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <description>The type of transaction this expectation configuration applies to - regular recurring, lump sum, or tax relief transactions</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REGULAR</fullName>
                <default>true</default>
                <label>Regular</label>
            </value>
            <value>
                <fullName>LUMP_SUM</fullName>
                <label>Lump Sum</label>
            </value>
            <value>
                <fullName>TAX_RELIEF</fullName>
                <label>Tax Relief</label>
            </value>
            <value>
                <fullName>REBATE</fullName>
                <label>Rebate</label>
            </value>
            <value>
                <fullName>TRANSFER</fullName>
                <label>Transfer</label>
            </value>
            <value>
                <fullName>IN_SPECIE</fullName>
                <label>In specie</label>
            </value>
            <value>
                <fullName>REDRESS</fullName>
                <label>Redress</label>
            </value>
            <value>
                <fullName>RESIDUAL</fullName>
                <label>Residual</label>
            </value>
            <value>
                <fullName>FEE</fullName>
                <label>Fee</label>
            </value>
            <value>
                <fullName>DIVIDEND</fullName>
            </value>
            <value>
                <fullName>INTEREST</fullName>
            </value>
            <value>
                <fullName>REFUND</fullName>
            </value>
            <value>
                <fullName>DIVIDEND_VCT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Primary Owner&#39;s household</inlineHelpText>
    <label>Household Lookup</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household.

(Admin message: lookup filter criteria not met on Household on the financial product object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The post-CheerIO product this relates to</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Financial Products</relationshipLabel>
    <relationshipName>Financial_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/RegisteredContact__c.field-meta.xml
<CustomField>
    <fullName>RegisteredContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For junior products, this is the adult registered on the account</description>
    <label>Registered contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Products (Registered contact)</relationshipLabel>
    <relationshipName>Financial_Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/recordTypes/FP_SIPP.recordType-meta.xml
<RecordType>
    <fullName>FP_SIPP</fullName>
    <active>true</active>
    <label>SIPP</label>
</RecordType>

force-app/main/default/objects/FinServ__FinancialAccount__c/recordTypes/Junior_SIPP.recordType-meta.xml
<RecordType>
    <fullName>Junior_SIPP</fullName>
    <active>true</active>
    <label>Junior SIPP</label>
</RecordType>

force-app/main/default/objects/Fulfilment__c/Fulfilment__c.object-meta.xml
<CustomObject>
    <description>An object to store the progress of fulfilling recommendations</description>
    <label>Fulfilment</label>
    <nameField>
        <displayFormat>Flfl-{0000000}</displayFormat>
        <label>Fulfilment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The household that this fulfilment is related to</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment__c/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation which resulted in this fulfilment</description>
    <label>Recommendation</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Will store the kinds of products we can provide in the post-cheerIO world.</description>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>Unique reference for developers</description>
    <externalId>true</externalId>
    <label>Developer name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Recommendation__c/Recommendation__c.object-meta.xml
<CustomObject>
    <description>Contains all the information given by planners when making a recommendation of an action for a change in a clients financial circumstances.</description>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>Rec-{0000000}</displayFormat>
        <label>Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/fields/DestinationLegacy__c.field-meta.xml
<CustomField>
    <fullName>DestinationLegacy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account which is receiving funds or undergoing a change</description>
    <label>Destination</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The household to which this recommendation is being made.</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Recommendation__c/fields/PreRequisiteRecommendation__c.field-meta.xml
<CustomField>
    <fullName>PreRequisiteRecommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the recommendation which must be completed before this one can be done</description>
    <label>Pre-requisite recommendation destination</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>PrimaryOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the main client that this recommendation relates to, the primary owner of the destination product</description>
    <label>Primary owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation (Primary owner)</relationshipLabel>
    <relationshipName>Recommendation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of product this recommendation relates to. Likely only used for open product recommendations</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/RecommendationType__c.field-meta.xml
<CustomField>
    <fullName>RecommendationType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of recommendation, for example rebalance or transfer. The objects held here help determine which fields should be visible on the recommendation.</description>
    <label>Recommendation type</label>
    <referenceTo>RecommendationType__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecommendationType__c/RecommendationType__c.object-meta.xml
<CustomObject>
    <description>Object to control which fields are visible on recommendations, based on the kind of recommendation they are.</description>
    <label>Recommendation Type</label>
    <nameField>
        <label>Recommendation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommendation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecommendationType__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>Unique reference</description>
    <externalId>true</externalId>
    <label>Developer name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FulfilmentTriggerHelper.cls
public class FulfilmentTriggerHelper {
    // Class to collect the fulfilment details from those in the trigger, construct email requests and pass them to the email send class for sending
    public void sendNotices(Map<Id, SObject> fulfilmentsNewMap, Map<Id, SObject> fulfilmentsOldMap) {

    public static final String EXPECTATION_TRIGGER_STATUS = 'Submit fulfilment';

    private static final String TARGET_SOURCE_VALUE = 'Source';
    private static final String TARGET_DESTINATION_VALUE = 'Destination';
    private static final String TARGET_BOTH_VALUE = 'Both';
    
    // Constants for magic numbers and hard-coded values
    private static final String FREQUENCY_MONTHLY = 'Monthly';
    private static final String STATUS_PENDING = 'Pending';
    private static final Integer DAY_OFFSET_ADJUSTMENT = -1; // -1 because addDays is 0-indexed
    private static final Integer MONTHS_TO_ADD_FOR_FUTURE_DATE = 1;

    // Use private backing fields for lazy-loaded properties
    private transient Map<String, ExpectationConfiguration__mdt> recommendationTypeToExpectationConfigMap;
    private transient Map<String, ExpectationConfiguration__mdt> nonRegularRecommendationTypeToExpectationConfigMap;
    private transient Map<String, ExpectationConfiguration__mdt> regularRecommendationTypeToExpectationConfigMap;

    // This single getter now efficiently initializes all three maps at once.
    private void initializeConfigMaps() {
        if (this.recommendationTypeToExpectationConfigMap == null) {
            this.recommendationTypeToExpectationConfigMap = new Map<String, ExpectationConfiguration__mdt>();
            this.nonRegularRecommendationTypeToExpectationConfigMap = new Map<String, ExpectationConfiguration__mdt>();
            this.regularRecommendationTypeToExpectationConfigMap = new Map<String, ExpectationConfiguration__mdt>();

            List<ExpectationConfiguration__mdt> expectationConfigurations = [
                SELECT 
                    RecommendationTypeDeveloperName__c, Direction__c, DateOffset__c, 
                    TransactionType__c, Target__c, isRegular__c
                FROM ExpectationConfiguration__mdt
            ];

            for (ExpectationConfiguration__mdt config : expectationConfigurations) {
                this.recommendationTypeToExpectationConfigMap.put(config.RecommendationTypeDeveloperName__c, config);
                if (config.isRegular__c) {
                    this.regularRecommendationTypeToExpectationConfigMap.put(config.RecommendationTypeDeveloperName__c, config);
                } else {
                    this.nonRegularRecommendationTypeToExpectationConfigMap.put(config.RecommendationTypeDeveloperName__c, config);
                }
            }
        }
    }
    
    // Public methods now call the private initializer first
    public Map<String, ExpectationConfiguration__mdt> getRegularConfigs() {
        initializeConfigMaps();
        return this.regularRecommendationTypeToExpectationConfigMap;
    }

    public Map<String, ExpectationConfiguration__mdt> getNonRegularConfigs() {
        initializeConfigMaps();
        return this.nonRegularRecommendationTypeToExpectationConfigMap;
    }

    public Map<Id, Fulfilment__c> getFulfilmentsChangedToSubmitStatus(Map<Id, Fulfilment__c> oldFulfilmentMap, Map<Id, Fulfilment__c> newFulfilmentMap) {
        Map<Id, Fulfilment__c> fulfilmentsSubmitted = new Map<Id, Fulfilment__c>();
        
        List<Fulfilment__c> fulfilments = [
            SELECT
                Id, 
                Household__c,
                Recommendation__c,
                Recommendation__r.Household__c,
                Recommendation__r.PrimaryOwner__r.PersonContactId, 
                Recommendation__r.Product__r.Name,
                Recommendation__r.RegisteredContact__c,
                Recommendation__r.RegisteredContact__r.PersonContactId,
                Recommendation__r.PrimaryOwner__r.AddressedName__pc,
                Recommendation__r.RegisteredContact__r.AddressedName__pc,
                Recommendation__r.Product__r.DeveloperName__c,
                Recommendation__r.RecommendationType__r.DeveloperName__c,
                Recommendation__r.TransferType__c,
                Recommendation__r.SourceLegacy__r.Public_Provider_Name__r.Name,
                Recommendation__r.DestinationLegacy__r.Public_Provider_Name__r.Name,
                Recommendation__r.DestinationLegacy__r.RecordType.DeveloperName,
                ResidualCash__c,
                Status__c,
                CancellationNoticeSent__c
            FROM
                Fulfilment__c
            WHERE
                ((Recommendation__r.RecommendationType__r.DeveloperName__c = 'OPEN_PRODUCT' AND Recommendation__r.Product__r.DeveloperName__c IN ('SIPP_HUBWISE', 'JSIPP_HUBWISE') AND Status__c = 'Complete' ) OR 
                (Recommendation__r.RecommendationType__r.DeveloperName__c = 'EXTERNAL_TRANSFER_IN' AND Recommendation__r.DestinationLegacy__r.RecordType.DeveloperName IN ('Junior_SIPP', 'FP_SIPP') AND PaymentStatus__c = 'Funds received'))
                AND Id IN :fulfilmentsNewMap.keySet()
            	AND CancellationNoticeSent__c = false
            ];
        if (newFulfilmentMap == null || newFulfilmentMap.isEmpty()) {
            return fulfilmentsSubmitted;
        }
        
        List<Fulfilment__c> fulfilmentsRequiringNotice = new List<Fulfilment__c>();
        for(Id fulfilmentId : newFulfilmentMap.keySet()) {
            Fulfilment__c newFulfilment = newFulfilmentMap.get(fulfilmentId);
            if (newFulfilment == null) continue;
            
            // Check if old map contains the key to prevent null pointer on inserts
            if(oldFulfilmentMap != null && oldFulfilmentMap.containsKey(fulfilmentId)) {
                Fulfilment__c oldFulfilment = oldFulfilmentMap.get(fulfilmentId);
                if (oldFulfilment != null && 
                    newFulfilment.Status__c == EXPECTATION_TRIGGER_STATUS &&
                    oldFulfilment.Status__c != EXPECTATION_TRIGGER_STATUS) {
                    fulfilmentsSubmitted.put(fulfilmentId, newFulfilment);
                }
            }   
        }
        return fulfilmentsSubmitted;
    }
    
    public void processSubmittedFulfilments(Map<Id, Fulfilment__c> oldFulfilmentMap, Map<Id, Fulfilment__c> newFulfilmentMap) {
        try {
            Map<Id, Fulfilment__c> fulfilmentsSubmitted = getFulfilmentsChangedToSubmitStatus(oldFulfilmentMap, newFulfilmentMap);

            if(!fulfilmentsSubmitted.isEmpty()) {
                Map<Id, Recommendation__c> recommendationMap = getRecommendations(fulfilmentsSubmitted);
                generateExpectationRequests(fulfilmentsSubmitted, recommendationMap);
                generateRegularTransactionRequests(fulfilmentsSubmitted, recommendationMap);   
            }
        } catch (Exception e) {
            // Log the error and re-throw to maintain existing behaviour
            System.debug(LoggingLevel.ERROR, 'Error processing submitted fulfilments: ' + e.getMessage());
            throw e;
        }
    }

    public Map<Id, Recommendation__c> getRecommendations(Map<Id, Fulfilment__c> fulfilmentsSubmitted) {
        if (fulfilmentsSubmitted == null || fulfilmentsSubmitted.isEmpty()) {
            return new Map<Id, Recommendation__c>();
        }
        
        for( Fulfilment__c fulfilment : fulfilments ) {
            Fulfilment__c fulfilmentOld = (Fulfilment__c) fulfilmentsOldMap.get(fulfilment.Id);
            if( fulfilmentOld.CancellationNoticeSent__c == false && ((fulfilmentOld.Status__c == 'Chase transfer' && fulfilment.Status__c == 'Investment checks'&& fulfilment.Recommendation__r.RecommendationType__r.DeveloperName__c == 'EXTERNAL_TRANSFER_IN')||(fulfilment.Recommendation__r.RecommendationType__r.DeveloperName__c == 'OPEN_PRODUCT'))) {
                fulfilmentsRequiringNotice.add(fulfilment);
            } 
        Set<Id> recommendationIds = new Set<Id>();
        for(Fulfilment__c fulfilment : fulfilmentsSubmitted.values()) {
            if (fulfilment != null && fulfilment.Recommendation__c != null) {
                recommendationIds.add(fulfilment.Recommendation__c);
            }
        }

        if (recommendationIds.isEmpty()) {
            return new Map<Id, Recommendation__c>();
        }

        return new Map<Id, Recommendation__c>([
            SELECT Id, DestinationLegacy__c, DestinationLegacy__r.OW_own_product__c, DestinationLegacy__r.FinancialProductType__r.RegularDay__c,
                   SourceLegacy__c, SourceLegacy__r.OW_own_product__c, SourceLegacy__r.FinancialProductType__r.RegularDay__c, Amount__c, 
                   RecommendationType__r.DeveloperName__c 
            FROM Recommendation__c
            WHERE Id IN :recommendationIds
        ]);
    }

    public void generateExpectationRequests(Map<Id, Fulfilment__c> fulfilmentsSubmitted, Map<Id, Recommendation__c> recommendationMap) {
        if (fulfilmentsSubmitted == null || fulfilmentsSubmitted.isEmpty() || recommendationMap == null) {
            return;
        }
        
        if( fulfilmentsRequiringNotice.size() > 0 ) {
            // Create a list of email requests for these fulfilments
            List<EmailSend.EmailSendRequestAutomatic> emailRequests = new List<EmailSend.EmailSendRequestAutomatic>();
        List<ExpectationRequest> requests = new List<ExpectationRequest>();
        Map<String, ExpectationConfiguration__mdt> configs = getNonRegularConfigs();

        for(Fulfilment__c fulfilment : fulfilmentsSubmitted.values()) {
            if (fulfilment == null || fulfilment.Recommendation__c == null) continue;
            
            for (Fulfilment__c fulfilment : fulfilmentsRequiringNotice) {
                emailRequests.add(constructEmailRequest(fulfilment));
                fulfilment.CancellationNoticeSent__c = true;
            }  
            Recommendation__c recommendation = recommendationMap.get(fulfilment.Recommendation__c);
            if (recommendation == null) continue; // Skip if no matching recommendation

            String recTypeDevName = recommendation.RecommendationType__r?.DeveloperName__c;
            if(String.isBlank(recTypeDevName) || !configs.containsKey(recTypeDevName)) continue;
            
            // Send the emails
            EmailSend emailSender = new EmailSend();
            emailSender.sendAutomaticTemplatedEmailCustomSubject(emailRequests);
            update fulfilmentsRequiringNotice;
            if(recommendation.DestinationLegacy__r?.OW_own_product__c == true || recommendation.SourceLegacy__r?.OW_own_product__c == true){
                ExpectationConfiguration__mdt expectationConfig = configs.get(recTypeDevName);
                
                ExpectationRequest expectationRequest = new ExpectationRequest();
                expectationRequest.fulfilmentId = fulfilment.Id;
                expectationRequest.direction = expectationConfig.Direction__c;
                
                // Safe casting with null check
                Integer dateOffset = expectationConfig.DateOffset__c != null ? 
                    (Integer)expectationConfig.DateOffset__c : 0;
                expectationRequest.expectationDate = Date.today().addDays(dateOffset);
                
                // Safe handling of amount
                expectationRequest.amount = recommendation.Amount__c != null ? recommendation.Amount__c : 0;
                expectationRequest.transactionType = expectationConfig.TransactionType__c;

                if(expectationConfig.Target__c == TARGET_SOURCE_VALUE) {
                    expectationRequest.productId = recommendation.SourceLegacy__c;
                } else if(expectationConfig.Target__c == TARGET_DESTINATION_VALUE) {
                    expectationRequest.productId = recommendation.DestinationLegacy__c;
                } else if(expectationConfig.Target__c == TARGET_BOTH_VALUE) {
                    expectationRequest.direction = ExpectationHelper.DIRECTION_WITHDRAWAL;
                    expectationRequest.productId = recommendation.SourceLegacy__c;

                    ExpectationRequest expectationRequest2 = expectationRequest.clone();
                    expectationRequest2.productId = recommendation.DestinationLegacy__c;
                    expectationRequest2.direction = ExpectationHelper.DIRECTION_CONTRIBUTION;
                    requests.add(expectationRequest2);
                }
                requests.add(expectationRequest);
            }
        }

        if(!requests.isEmpty()){
            ExpectationHelper.createExpectations(requests);
        }
    }

    public void generateRegularTransactionRequests(Map<Id, Fulfilment__c> fulfilmentsSubmitted, Map<Id, Recommendation__c> recommendationMap){
        if (fulfilmentsSubmitted == null || fulfilmentsSubmitted.isEmpty() || recommendationMap == null) {
            return;
        }
        
    }
    
    // Method to take a piece of fulfilment and create an email request of the correct type with the correct parameters
    public static EmailSend.EmailSendRequestAutomatic constructEmailRequest(Fulfilment__c fulfilment) {
        EmailSend.EmailSendRequestAutomatic emailRequest = new EmailSend.EmailSendRequestAutomatic();
        emailRequest.householdId = fulfilment.Recommendation__r.Household__c;
        emailRequest.whatId = fulfilment.Id;
        emailRequest.saveAsActivity = true;
        if( fulfilment.Recommendation__r.RecommendationType__r.DeveloperName__c == 'EXTERNAL_TRANSFER_IN') {
			emailRequest.emailTemplateDeveloperName = 'CancellationNoticeTransfer';            
            emailRequest.parameters = EmailCancellationNoticeTransfer.getParameters(fulfilment);
        } else {
            emailRequest.emailTemplateDeveloperName = 'CancellationNoticeNewProduct'; 
            emailRequest.parameters = EmailCancellationNoticeNewProduct.getParameters(fulfilment);
            emailRequest.subject = EmailCancellationNoticeNewProduct.getSubject(fulfilment);
        List<RegularTransactionRequest> requests = new List<RegularTransactionRequest>();
        Map<String, ExpectationConfiguration__mdt> configs = getRegularConfigs();

        for(Fulfilment__c fulfilment : fulfilmentsSubmitted.values()){
            if (fulfilment == null || fulfilment.Recommendation__c == null) continue;
            
            Recommendation__c recommendation = recommendationMap.get(fulfilment.Recommendation__c);
            if(recommendation == null) continue;

            String recTypeDevName = recommendation.RecommendationType__r?.DeveloperName__c;
            if(String.isBlank(recTypeDevName) || !configs.containsKey(recTypeDevName)) continue;
            
            ExpectationConfiguration__mdt expectationConfig = configs.get(recTypeDevName);
            
            RegularTransactionRequest request = new RegularTransactionRequest();
            // Safe handling of amount
            request.amount = recommendation.Amount__c != null ? recommendation.Amount__c : 0;
            request.frequency = FREQUENCY_MONTHLY; //only monthly for now
            request.status = STATUS_PENDING;
            request.direction = expectationConfig.Direction__c;
            request.startDate = Date.today();

            if(expectationConfig.Target__c == TARGET_SOURCE_VALUE) {
                request.productId = recommendation.SourceLegacy__c;
                // Safe handling of RegularDay__c with null check
                Integer regularDay = recommendation.SourceLegacy__r?.FinancialProductType__r?.RegularDay__c != null ? 
                    (Integer)recommendation.SourceLegacy__r.FinancialProductType__r.RegularDay__c : 1;
                request.startDate = Date.today().toStartOfMonth().addDays(regularDay + DAY_OFFSET_ADJUSTMENT);
            } else if(expectationConfig.Target__c == TARGET_DESTINATION_VALUE) {
                request.productId = recommendation.DestinationLegacy__c;
                // Safe handling of RegularDay__c with null check
                Integer regularDay = recommendation.DestinationLegacy__r?.FinancialProductType__r?.RegularDay__c != null ? 
                    (Integer)recommendation.DestinationLegacy__r.FinancialProductType__r.RegularDay__c : 1;
                request.startDate = Date.today().toStartOfMonth().addDays(regularDay + DAY_OFFSET_ADJUSTMENT);
            } else if(expectationConfig.Target__c == TARGET_BOTH_VALUE) {
                request.productId = recommendation.SourceLegacy__c;
                request.direction = ExpectationHelper.DIRECTION_WITHDRAWAL;
                // Safe handling of RegularDay__c with null check
                Integer sourceRegularDay = recommendation.SourceLegacy__r?.FinancialProductType__r?.RegularDay__c != null ? 
                    (Integer)recommendation.SourceLegacy__r.FinancialProductType__r.RegularDay__c : 1;
                request.startDate = Date.today().toStartOfMonth().addDays(sourceRegularDay + DAY_OFFSET_ADJUSTMENT); 
                
                RegularTransactionRequest request2 = request.clone();
                request2.productId = recommendation.DestinationLegacy__c;
                request2.direction = ExpectationHelper.DIRECTION_CONTRIBUTION;
                // Safe handling of RegularDay__c with null check
                Integer destRegularDay = recommendation.DestinationLegacy__r?.FinancialProductType__r?.RegularDay__c != null ? 
                    (Integer)recommendation.DestinationLegacy__r.FinancialProductType__r.RegularDay__c : 1;
                request2.startDate = Date.today().toStartOfMonth().addDays(destRegularDay + DAY_OFFSET_ADJUSTMENT);

                if(request2.frequency == FREQUENCY_MONTHLY){
                    if(request2.startDate <= Date.today()){
                        request2.startDate = request.startDate.addMonths(MONTHS_TO_ADD_FOR_FUTURE_DATE);
                    }
                }

                request2.nextTransactionDate = request2.startDate;
                requests.add(request2);
            }
            
            if(request.frequency == FREQUENCY_MONTHLY){
                if(request.startDate <= Date.today()){
                    request.startDate = request.startDate.addMonths(MONTHS_TO_ADD_FOR_FUTURE_DATE);
                }
            }

            request.nextTransactionDate = request.startDate;
            requests.add(request);
        }

        if(!requests.isEmpty()){
            RegularTransactionHelper.generateRegularTransactions(requests);
        }
        emailRequest.targetObjectId = getContactId(fulfilment);
        return emailRequest; 
    }
    
    // Get correct contact for this email
    public static String getContactId(Fulfilment__c fulfilment) {
        if( fulfilment.Recommendation__r.Product__r.DeveloperName__c == 'SIPP_HUBWISE' ) {
            return fulfilment.Recommendation__r.PrimaryOwner__r.PersonContactId;
        } else {
            return fulfilment.Recommendation__r.RegisteredContact__r.PersonContactId;
        }
    }  
}