force-app/main/default/objects/Contact/fields/FinServ__PreferredName__c.field-meta.xml
<CustomField>
    <fullName>FinServ__PreferredName__c</fullName>
    <inlineHelpText>Visible in profile</inlineHelpText>
    <label>Preferred Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/EmailConfiguration__c.object-meta.xml
<CustomObject>
    <description>Holds the details of emails that is used to drive automation and business validation.</description>
    <label>Email Configuration</label>
    <nameField>
        <label>Email Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailConfiguration__c/fields/ClientsAddressed__c.field-meta.xml
<CustomField>
    <fullName>ClientsAddressed__c</fullName>
    <description>Indicates if one or both clients should be included in an email</description>
    <label>Clients addressed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>One only</fullName>
            </value>
            <value>
                <fullName>User defined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/CustomPermission__c.field-meta.xml
<CustomField>
    <fullName>CustomPermission__c</fullName>
    <description>If this field has a value, a user must have this custom permission order to send an email of this type</description>
    <inlineHelpText>If this field has a value, a user must have this custom permission order to send an email of this type</inlineHelpText>
    <label>Custom permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the email template</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name of the email template this email configuration is associated with.</description>
    <externalId>true</externalId>
    <inlineHelpText>Must match the developer name of the email template.</inlineHelpText>
    <label>Developer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <description>The email address this email message must come from.</description>
    <label>From</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Necessity__c.field-meta.xml
<CustomField>
    <fullName>Necessity__c</fullName>
    <label>Necessity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/PartnerCopied__c.field-meta.xml
<CustomField>
    <fullName>PartnerCopied__c</fullName>
    <description>Indicates if partner should be copied into an email of this type</description>
    <label>Partner copied</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always</fullName>
            </value>
            <value>
                <fullName>Never</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of email being sent</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailHiStringTest.cls
@isTest
public class EmailHiStringTest {

    @istest
    static void hiString_generate_successful(){
        // set up user and permissions
        User currentUser = [ SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
        PermissionSet ps = new PermissionSet(
            Name = 'Test', 
            Label = 'Test'
        );
        System.runAs ( currentUser ) {
            insert ps;
        }
        CustomPermission cp = [SELECT Id, DeveloperName FROM CustomPermission WHERE IsLicensed = false AND IsProtected = false AND NamespacePrefix = null LIMIT 1];
        SetupEntityAccess sea = new SetupEntityAccess(
            ParentId = ps.Id, 
            SetupEntityId = cp.Id
        );
        System.runAs ( currentUser ) {
            insert sea;
        }
        
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = currentUser.Id,
            PermissionSetId = ps.Id
        );
        System.runAs ( currentUser ) {
            insert psa;
        }

        // Create email templates and email configuration records
        OrgWideEmailAddress fromEmail = [SELECT Id, Address FROM OrgWideEmailAddress ORDER BY Address ASC LIMIT 1];
        EmailTemplate et = new EmailTemplate(
            isActive = true, 
            Name = 'STARTER_EMAIL', 
            DeveloperName = 'STARTER_EMAIL', 
            TemplateType = 'text', 
            FolderId = UserInfo.getUserId() // fix this line, not right
        ); 
        EmailConfiguration__c ec = new EmailConfiguration__c(
            Name = 'STARTER_EMAIL', 
            DeveloperName__c = 'STARTER_EMAIL',
            ClientsAddressed__c = 'All', 
            CustomPermission__c = cp.DeveloperName,
            Description__c = 'Test',
            From__c = fromEmail.Address,
            PartnerCopied__c = 'Always',
            Type__c = 'Service',
            Necessity__c = 'Required'
        );
        String identifier = 'EmailMessageHelperTestHousehold';
        Account household = DataFactoryAccountHousehold.createHousehold(identifier, 2, 0, 'Active', 'Full');
        System.runAs ( currentUser ) {
            insert et;
            insert ec;
        }
        EmailHiString hi = new EmailHiString();
        hi.emailTemplateDevName = et.DeveloperName;
        hi.objectIdString = household.Id;
        String output = hi.getHiString();
        List<AccountContactRelation> acrs = [SELECT Contact.FirstName, Contact.FinServ__PreferredName__c FROM AccountContactRelation WHERE AccountId = :household.Id];
        System.debug(acrs.size());
        for(AccountContactRelation acr : acrs){
            if(!String.isBlank(acr.Contact.FinServ__PreferredName__c)){
                System.Assert.isTrue(output.contains(acr.Contact.FinServ__PreferredName__c));
            } else {
                System.Assert.isTrue(output.contains(acr.Contact.FirstName));
            }
        }
        System.assertEquals(true, output.contains(',')); 
    }
}