force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment__c/Fulfilment__c.object-meta.xml
<CustomObject>
    <description>An object to store the progress of fulfilling recommendations</description>
    <label>Fulfilment</label>
    <nameField>
        <displayFormat>Flfl-{0000000}</displayFormat>
        <label>Fulfilment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfilment__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The advice that the recommendation this is fulfilling was associated to</description>
    <label>Advice</label>
    <referenceTo>Advice__c</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The household that this fulfilment is related to</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment__c/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation which resulted in this fulfilment</description>
    <label>Recommendation</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Fulfilments</relationshipLabel>
    <relationshipName>Fulfilments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfilment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used to describe at what stage in the process this piece of fulfilment is in</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On hold</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Awaiting pre-requisites</fullName>
            </value>
            <value>
                <fullName>Awaiting ad hoc action</fullName>
            </value>
            <value>
                <fullName>Submit fulfilment</fullName>
            </value>
            <value>
                <fullName>Chase client payment</fullName>
            </value>
            <value>
                <fullName>Chase transfer</fullName>
            </value>
            <value>
                <fullName>Chase provider</fullName>
            </value>
            <value>
                <fullName>Chase client action</fullName>
            </value>
            <value>
                <fullName>Await first regular</fullName>
            </value>
            <value>
                <fullName>Investment checks</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting bank details</fullName>
                <isActive>false</isActive>
                <label>Awaiting bank details</label>
            </value>
            <value>
                <fullName>Awaiting client payment</fullName>
                <isActive>false</isActive>
                <label>Awaiting client payment</label>
            </value>
            <value>
                <fullName>Awaiting client signature</fullName>
                <isActive>false</isActive>
                <label>Awaiting client signature</label>
            </value>
            <value>
                <fullName>Awaiting form processing</fullName>
                <isActive>false</isActive>
                <label>Awaiting form processing</label>
            </value>
            <value>
                <fullName>Awaiting pre-requisite fulfilment</fullName>
                <isActive>false</isActive>
                <label>Awaiting pre-requisite fulfilment</label>
            </value>
            <value>
                <fullName>Awaiting transfer</fullName>
                <isActive>false</isActive>
                <label>Awaiting transfer</label>
            </value>
            <value>
                <fullName>Ready for submission</fullName>
                <isActive>false</isActive>
                <label>Ready for submission</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Will store the kinds of products we can provide in the post-cheerIO world.</description>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/Recommendation__c.object-meta.xml
<CustomObject>
    <description>Contains all the information given by planners when making a recommendation of an action for a change in a clients financial circumstances.</description>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>Rec-{0000000}</displayFormat>
        <label>Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The advice that this recommendation is a part of</description>
    <label>Advice</label>
    <referenceTo>Advice__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount tied to a recommendation such as the lump sum, regular deposit or expected value of a transfer.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/DestinationLegacy__c.field-meta.xml
<CustomField>
    <fullName>DestinationLegacy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account which is receiving funds or undergoing a change</description>
    <label>Destination</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The household to which this recommendation is being made.</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Recommendation__c/fields/PreRequisiteRecommendation__c.field-meta.xml
<CustomField>
    <fullName>PreRequisiteRecommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the recommendation which must be completed before this one can be done</description>
    <label>Pre-requisite recommendation destination</label>
    <referenceTo>Recommendation__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/PrimaryOwner__c.field-meta.xml
<CustomField>
    <fullName>PrimaryOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the main client that this recommendation relates to, the primary owner of the destination product</description>
    <label>Primary owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recommendation (Primary owner)</relationshipLabel>
    <relationshipName>Recommendation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of product this recommendation relates to. Likely only used for open product recommendations</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/RecommendationType__c.field-meta.xml
<CustomField>
    <fullName>RecommendationType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of recommendation, for example rebalance or transfer. The objects held here help determine which fields should be visible on the recommendation.</description>
    <label>Recommendation type</label>
    <referenceTo>RecommendationType__c</referenceTo>
    <relationshipLabel>Recommendation</relationshipLabel>
    <relationshipName>Recommendation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recommendation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The progress of the recommendation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Awaiting decision</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In place</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecommendationType__c/RecommendationType__c.object-meta.xml
<CustomObject>
    <description>Object to control which fields are visible on recommendations, based on the kind of recommendation they are.</description>
    <label>Recommendation Type</label>
    <nameField>
        <label>Recommendation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommendation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecommendationType__c/fields/ReferenceName__c.field-meta.xml
<CustomField>
    <fullName>ReferenceName__c</fullName>
    <description>Specifying the recommendation type, eg &apos;Transfer&apos;</description>
    <externalId>true</externalId>
    <label>Reference name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ringfence__c/Ringfence__c.object-meta.xml
<CustomObject>
    <description>Used to record when ringfences have been applied against a financial product, in the context of fulfilment.</description>
    <label>Ringfence</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Ringfence Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ringfences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ringfence__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of ringfence applied to this financial product specifically in relation to this fulfilment.</description>
    <inlineHelpText>The amount of ringfence applied to this financial product specifically in relation to this fulfilment.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ringfence__c/fields/Fulfilment__c.field-meta.xml
<CustomField>
    <fullName>Fulfilment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The fulfilment that required this ringfence.</description>
    <label>Fulfilment</label>
    <referenceTo>Fulfilment__c</referenceTo>
    <relationshipLabel>Ringfences</relationshipLabel>
    <relationshipName>Ringfences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ringfence__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>The reason this ringfence was applied or updated.</description>
    <inlineHelpText>The reason this ringfence was applied or updated.</inlineHelpText>
    <label>Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Ringfence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of this specific ringfence.</description>
    <inlineHelpText>Indicates the status of this specific ringfence.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LwcHelperFinProdRelatedRingfencesTest.cls
/**
 * This class exists exclusively to provide testing coverage for the Ringfences Related List for financial products LWC.
 * It should not be used in any other contexts.
 */
@isTest
public class LwcHelperFinProdRelatedRingfencesTest {	 
    @istest
    static void test_household_creation(){
        DataFactory df = new DataFactory();
        Id household = df.createHousehold('OW001 Test',2,2,'Onboarding','Full');
        
        Advice__c advice = df.createAdvice(0, household);
        
        List<RecommendationType__c> recTypes = [SELECT 
                                                Id, ReferenceName__c
                                               	FROM
                                                RecommendationType__c 
                                                WHERE
                                                ReferenceName__c 
                                                IN ('OPEN_PRODUCT')
                                               ];
        RecommendationType__c openProdRecType = new RecommendationType__c();
        for( RecommendationType__c recType : recTypes ){
            if( recType.ReferenceName__c == 'OPEN_PRODUCT' ) {
                openProdRecType = recType;
            }
        }
        
        List<Product__c> products = [SELECT 
                                     Id, ReferenceName__c
                                     FROM
                                     Product__c 
                                     WHERE
                                     ReferenceName__c IN
                                     ('SIPP_HUBWISE')
                                    ];
        Product__c productType = new Product__c();
        for( Product__c product : products ){
            if( product.ReferenceName__c == 'SIPP_HUBWISE' ) {
                productType = product;
            } 
        }

        AccountHouseholdMembers ahm = new AccountHouseholdMembers();
        AccountHouseholdMembers.HouseholdMemberRequest request = new AccountHouseholdMembers.HouseholdMemberRequest();
        request.householdId = household;
        Set<String> roles = new Set<String>{'Client','Child'};
        request.roles = roles;
        
        AccountHouseholdMembers.HouseholdMemberResult result = AccountHouseholdMembers.getHouseholdMembers(request);
        
        List<Account> clients = result.memberAccountsByRole.get('Client');
        List<Account> children = result.memberAccountsByRole.get('Child');
        
        
        Recommendation__c openSippRec = new Recommendation__c(
        	Product__c = productType.Id,
            RecommendationType__c = openProdRecType.Id,
            PrimaryOwner__c = clients[0].Id,
            Advice__c = advice.Id,
            Household__c = household
        );
        
        insert openSippRec;
        openSippRec.Status__c = 'Accepted';     
        update openSippRec;
        
        Fulfilment__c testFulfil = [SELECT 
                                    Id, Recommendation__r.DestinationLegacy__c 
                                    FROM 
                                    Fulfilment__c 
                                    WHERE
                                    Recommendation__c =: openSippRec.Id
                                    LIMIT 1
                                   ];
        
        Ringfence__c ringfence = new Ringfence__c(
        	Fulfilment__c = testFulfil.Id,
            Amount__c = 100,
            Reason__c = 'Because',
            Status__c = 'Active'
        );
        
        insert ringfence;

       	LwcHelperDynamicRecordList.DataWrapper data = LwcHelperFinProdRelatedRingfences.getRingfences(testFulfil.Recommendation__r.DestinationLegacy__c );
        System.Assert.areEqual(1, data.rows.size(), 'Expected 1 row');
    }
}