force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Advice_Status__c.field-meta.xml
<CustomField>
    <fullName>Advice_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
                <default>true</default>
                <label>Setup</label>
            </value>
            <value>
                <fullName>Data gathering</fullName>
            </value>
            <value>
                <fullName>Risk Call</fullName>
            </value>
            <value>
                <fullName>Ready for suitability</fullName>
            </value>
            <value>
                <fullName>Suitability in progress</fullName>
            </value>
            <value>
                <fullName>Prepare advice</fullName>
            </value>
            <value>
                <fullName>Present advice</fullName>
            </value>
            <value>
                <fullName>Deck complete</fullName>
            </value>
            <value>
                <fullName>Await decision</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>In fulfilment</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Suitability Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Meeting held</fullName>
                <isActive>false</isActive>
                <label>Meeting held</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/FinServ__FinancialAccount__c.object-meta.xml
<CustomObject>
    <description>A client&#39;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <inlineHelpText>Only used for Direct Equity Holdings</inlineHelpText>
    <label>Company Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/FinServ__FinancialAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FinServ__FinancialAccountNumber__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>AKA Policy Number</inlineHelpText>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Public_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Public_Provider_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Public Provider Name</label>
    <referenceTo>Public_Provider_Names__c</referenceTo>
    <relationshipLabel>Financial Products</relationshipLabel>
    <relationshipName>Financial_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/RegisteredContact__c.field-meta.xml
<CustomField>
    <fullName>RegisteredContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For junior products, this is the adult registered on the account</description>
    <label>Registered contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Products (Registered contact)</relationshipLabel>
    <relationshipName>Financial_Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <inlineHelpText>This is what the client will see under the highlevel  &quot;Type&quot; field in the portal.</inlineHelpText>
    <label>Portal Display Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Financial_Product_Subtypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InformationRequest__c/InformationRequest__c.object-meta.xml
<CustomObject>
    <description>Used to track the process of gathering information for financial products</description>
    <label>Information Request</label>
    <nameField>
        <displayFormat>IR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Information Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformationRequest__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The advice that requires this data request</description>
    <label>Advice</label>
    <referenceTo>Advice__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>InformationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/ComplaintStatus__c.field-meta.xml
<CustomField>
    <fullName>ComplaintStatus__c</fullName>
    <description>Used to track whether a complaint was made during the process of this data request</description>
    <label>Complaint status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lodged</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/DateInformationRequestSent__c.field-meta.xml
<CustomField>
    <fullName>DateInformationRequestSent__c</fullName>
    <description>The date we sent our information request to the third party provider</description>
    <label>Date information request sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/DateLastChased__c.field-meta.xml
<CustomField>
    <fullName>DateLastChased__c</fullName>
    <description>The date information for this policy was last chased</description>
    <label>Date last chased</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/ExpectedReceiptDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedReceiptDate__c</fullName>
    <description>The date we currently expect to receive information by</description>
    <label>Date information expected</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/FinancialProductFinServ__c.field-meta.xml
<CustomField>
    <fullName>FinancialProductFinServ__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The financial product that this information request is for</description>
    <label>Financial product</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>InformationRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/FirstExpectedReceiptDate__c.field-meta.xml
<CustomField>
    <fullName>FirstExpectedReceiptDate__c</fullName>
    <description>This is the first date that a provider gives us for when we should expect to receive information for this policy</description>
    <label>First date information expected</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/InformationRequestType__c.field-meta.xml
<CustomField>
    <fullName>InformationRequestType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The type of information request process needed</description>
    <label>Information Request Type</label>
    <referenceTo>InformationRequestType__c</referenceTo>
    <relationshipLabel>Information Requests</relationshipLabel>
    <relationshipName>InformationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InformationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the overall progression of the data gathering process for this policy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Awaiting policy pre-requisites</fullName>
            </value>
            <value>
                <fullName>Awaiting advice progression</fullName>
            </value>
            <value>
                <fullName>Information request to be sent</fullName>
            </value>
            <value>
                <fullName>Awaiting initial information</fullName>
            </value>
            <value>
                <fullName>Checklist review</fullName>
            </value>
            <value>
                <fullName>Fund analysis</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting ad hoc action</fullName>
            </value>
            <value>
                <fullName>Additional checklist review</fullName>
                <isActive>false</isActive>
                <label>Additional checklist review</label>
            </value>
            <value>
                <fullName>Awaiting additional information</fullName>
                <isActive>false</isActive>
                <label>Awaiting additional information</label>
            </value>
            <value>
                <fullName>Awaiting approval</fullName>
                <isActive>false</isActive>
                <label>Awaiting approval</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>Waiting for provider</fullName>
                <isActive>false</isActive>
                <label>Waiting for provider</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InformationRequestType__c/InformationRequestType__c.object-meta.xml
<CustomObject>
    <description>Used to specify process for different data gathering scenarios</description>
    <label>Information Request Type</label>
    <nameField>
        <label>Information Request Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Information Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InformationRequestType__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>Unique, non changing reference</description>
    <externalId>true</externalId>
    <label>Developer name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InformationRequestType__c/fields/InformationSource__c.field-meta.xml
<CustomField>
    <fullName>InformationSource__c</fullName>
    <description>Where we should go for information on this policy</description>
    <label>Information source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Third party provider</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InformationRequestType__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates if this is a current process</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Public_Provider_Names__c/Public_Provider_Names__c.object-meta.xml
<CustomObject>
    <label>Public Provider List</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Provider List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Financial_Product_Subtypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accident Sickness &amp; Unemployment</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Voluntary Contribution (AVC)</fullName>
    </customValue>
    <customValue>
        <fullName>Annuity</fullName>
    </customValue>
    <customValue>
        <fullName>Cash ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Critical Illness Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Current Account</fullName>
    </customValue>
    <customValue>
        <fullName>Defined Benefit</fullName>
    </customValue>
    <customValue>
        <fullName>Defined Contribution</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Equity Holding</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Gilt/Bond Holding</fullName>
    </customValue>
    <customValue>
        <fullName>Endowment</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Investment Scheme (EIS)</fullName>
    </customValue>
    <customValue>
        <fullName>Family Income Benefit</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Term Deposit</fullName>
    </customValue>
    <customValue>
        <fullName>General Investment Account</fullName>
    </customValue>
    <customValue>
        <fullName>Help To Buy ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Income Protection</fullName>
    </customValue>
    <customValue>
        <fullName>Inheritance Tax Investment Service</fullName>
    </customValue>
    <customValue>
        <fullName>Inheritance Tax Investment Service ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Junior ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Junior ISA / Child Trust Fund</fullName>
    </customValue>
    <customValue>
        <fullName>Life &amp; Critical Illness Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Life Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Life Cover (Whole of Life)</fullName>
    </customValue>
    <customValue>
        <fullName>Lifetime ISA</fullName>
    </customValue>
    <customValue>
        <fullName>Offset Mortgage Cash Account</fullName>
    </customValue>
    <customValue>
        <fullName>Offshore Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Onshore Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Peer-to-Peer/Innovative Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Peer-to-Peer/Innovative Finance ISA</fullName>
    </customValue>
    <masterLabel>Financial Product Subtypes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmailInformationRequestUpdateTable.cls
public class EmailInformationRequestUpdateTable {
    public String objectId{get;set;}
    public List<String> owners;
    public Map<String, List<IrUpdate>> outputs;

    public Map<String, List<IrUpdate>> getOutputs() {
        setOutputs(objectId);
        return outputs;
    }
    
    public List<String> getOwners() {
        setOutputs(objectId);
        return owners;
    }
    
    // Takes a list of data request updates and updates the output map from every owner to a list of their updates    
    public void setOutputs(String objectId) {
        List<IrUpdate> irs = setIrs(objectId);
        List<String> owners = new List<String>();
        Map<String, List<irUpdate>> returnMap = new Map<String, List<irUpdate>>();
        
        for ( irUpdate ir : irs ) {
            if ( !owners.contains(ir.name) ) {
                owners.add(ir.name);
            }
        }
        for (String s : owners) {
            List<irUpdate> tempList = new List<irUpdate>();
            for (irUpdate ir : irs ) {
                if ( ir.name == s ) {
                    tempList.add(ir);
                }
        	}
            returnMap.put(s, tempList); 
        }
        this.outputs = returnMap;
        this.owners = owners;
    }
        
    // Takes an object id for a piece of advice and returns a list of data request updates
    public List<irUpdate> setIrs(String objectId) {
        System.debug('in set irs');
        List<Advice__c> advList = [SELECT Id FROM Advice__c WHERE Advice_Household__c =: objectId AND (Advice_Status__c = 'Data gathering' OR Advice_Status__c = 'Risk call')];
        Set<Id> advIds = new Set<Id>(new Map<Id, Advice__c>(advList).keySet());
        List<InformationRequest__c> irs = [ SELECT Id, 
                                           FinancialProductFinServ__r.Public_Provider_Name__r.DeveloperName__c,
                                           FinancialProductFinServ__r.FinServ__JointOwner__c, 
                                           DateInformationRequestSent__c, 
                                           FinancialProductFinServ__r.FinServ__PrimaryOwner__r.AddressedName__pc,
                                           ComplaintStatus__c,
                                           FinancialProductFinServ__r.Company_Name__c,
                                           FinancialProductFinServ__r.Subtype__c,
                                           FinancialProductFinServ__r.Public_Provider_Name__r.Name,
                                           FinancialProductFinServ__r.FinServ__FinancialAccountNumber__c,
                                           Status__c,
                                           InformationRequestType__r.InformationSource__c,
                                           FirstExpectedReceiptDate__c,
                                           ExpectedReceiptDate__c,
                                           DateLastChased__c 
                                           FROM InformationRequest__c WHERE Advice__c IN :advIds ];
        
        String status;
        String message;
        String title;
        String role;
        String name;
        List<IrUpdate> irList = new List<IrUpdate>();
        
        for (InformationRequest__c r : irs) {  
            System.debug(r.ExpectedReceiptDate__c);
            // Set title
            if ( r.FinancialProductFinServ__r.Subtype__c == 'Direct Equity Holding' ) {
                title = r.FinancialProductFinServ__r.Company_Name__c + ' Shares';
            } else {
                title = r.FinancialProductFinServ__r.Public_Provider_Name__r.Name + ' ' + r.FinancialProductFinServ__r.Subtype__c;
            }
            
            // Set role and name
            if ( r.FinancialProductFinServ__r.FinServ__JointOwner__c == null ) {
                role = 'Client';
                name = r.FinancialProductFinServ__r.FinServ__PrimaryOwner__r.AddressedName__pc;
            } else {
                role = 'Joint';
                name = 'Joint';
            }
            
            // Set status and messages
            
            // Await advice progression
            if (r.Status__c == 'Awaiting advice progression') {
                status = 'On track';
                message = System.Label.EmailInformationRequestUpdateClientRequest;
                
            // Policy pre-reqs required
            } else if (r.Status__c == 'Awaiting policy pre-requisites') {
                String awaitDetails = '';
                if ( r.FinancialProductFinServ__r.FinServ__FinancialAccountNumber__c == '' ){
                    awaitDetails += 'provider, ';
                }
                if ( r.FinancialProductFinServ__r.Public_Provider_Name__r.DeveloperName__c == 'UNKNOWN') {
                    awaitDetails += 'policy number, ';
                }
                if( r.FinancialProductFinServ__r.Subtype__c.contains('Junior')&& r.FinancialProductFinServ__r.RegisteredContact__c == '') {
                    awaitDetails += 'registered contact, ';
                }
                awaitdetails = awaitDetails.substringBeforeLast(', ') + ' & ' + awaitDetails.substringAfterLast(', ');
                
                status = 'Action required';
                message = System.Label.EmailInformationRequestUpdateAwaitPreReqsPt1 + awaitDetails + System.Label.EmailInformationRequestUpdateAwaitPreReqsPt2;
                
                
                
            // Info request to be sent - differs by info source
            } else if (r.Status__c == 'Information request to be sent') {
                if (r.InformationRequestType__r.InformationSource__c == 'Client') {
                    status = 'On track';
                    message = System.Label.EmailInformationRequestUpdateClientRequest;
                    
                } else if (r.InformationRequestType__r.InformationSource__c == 'Third party provider') {
                    status = 'On track';
                    message = System.Label.EmailInformationRequestUpdatePrepRequest;
                    
                }
                
            // Awaiting initial information
            } else if (r.Status__c == 'Awaiting initial information') {
                
                // If info is from client
                if (r.InformationRequestType__r.InformationSource__c == 'Client') {
                    status = 'Action required';
                    message = System.Label.EmailInformationRequestUpdateChaseClient;
                    
                // If info is from third party
                } else if (r.InformationRequestType__r.InformationSource__c == 'Third party provider') {
                    
                    // Check if we have ever chased before
                    if( r.FirstExpectedReceiptDate__c == null ) {
                        status = 'On track';
                        message = System.Label.EmailInformationRequestUpdateChasing + ' ' + formatDate( r.DateInformationRequestSent__c) + '.';
                        
                    // If we have chased before...
                    } else {
                        
                        // Expected receipt date has passed
                        if( date.today() > r.ExpectedReceiptDate__c ) {
                            
                            // Complaint in progress
                            if( r.ComplaintStatus__c == 'Lodged') {
                                status = 'Off track';
                                message = System.Label.EmailInformationRequestUpdateComplaintLodged;
                                
                            // Complaint resolved, still chasing
                            } else if ( r.ComplaintStatus__c == 'Resolved') {
                                status = 'On track';
                                message = System.Label.EmailInformationRequestUpdateChasingPart1 + ' ' + formatDate(r.DateLastChased__c) + '. ' + r.FinancialProductFinServ__r.Public_Provider_Name__r.Name + ' ' + System.Label.EmailInformationRequestUpdateChasingPart2 + ' ' + formatDate(r.ExpectedReceiptDate__c) + '.';
                                
                            // No complaint made
                            } else {
                                status = 'Off track';
                                message = r.FinancialProductFinServ__r.Public_Provider_Name__r.Name + ' ' + System.Label.EmailInformationRequestUpdateOffTrack + ' ' + formatDate(r.ExpectedReceiptDate__c) + ' ' + System.Label.EmailInformationRequestUpdateOffTrackPt2;
                            }
                            
                            
                        // Expected receipt date in future
                        } else {
                            status = 'On track';
							message = System.Label.EmailInformationRequestUpdateChasingPart1 + ' ' + formatDate(r.DateLastChased__c) + '. ' + r.FinancialProductFinServ__r.Public_Provider_Name__r.Name + ' ' + System.Label.EmailInformationRequestUpdateChasingPart2 + ' ' + formatDate(r.ExpectedReceiptDate__c) + '.';                        
                        }  
                    }
                }
                
            // Information received
            } else if (r.Status__c == 'Checklist review') {
                if (r.InformationRequestType__r.InformationSource__c == 'Client') {
                    status = 'On track';
                    message = System.Label.EmailInformationRequestUpdateClientReceived;
                    
                } else if (r.InformationRequestType__r.InformationSource__c == 'Third party provider') {
                    status = 'On track';
                    message = System.Label.EmailInformationRequestUpdateInfoReceived;
                }
                
            // Checklist complete
            } else if (r.Status__c == 'Fund analysis') {
                status = 'Completed';
                message = System.Label.EmailInformationRequestUpdateComplete;
                
            // Completed
            } else if (r.Status__c == 'Complete' || r.Status__c == 'Ready for advice') {
                status = 'Completed';
                message = System.Label.EmailInformationRequestUpdateComplete;
                
            // Other
            } else {
                status = 'Off track';
                message = System.Label.EmailInformationRequestGeneric;
            }
            
            // Add data request update to collection of outputs
            if( status != null ) {
                irList.add(new irUpdate(title, message, status, role, name));
            }

        }
        
        irList.sort();
        return irList;
    }

    // Data request update class with custom sorting function
    public class irUpdate implements Comparable {
        public String title {get;set;}
        public String message {get;set;}
        public String status {get;set;}
        public String role {get;set;}
        public String name{get;set;}
        
        public irUpdate(String t, String m, String s, String r, String n) {
            title = t;
            message = m;
            status = s;
            role = r;
            name = n;
        }
        
        public Integer compareTo(Object compareTo){
            irUpdate compareToOwn = (irUpdate)compareTo;
            if(role == compareToOwn.role){
                if(role == compareToOwn.role){
                    if(name == compareToOwn.name){
                        return 0;
                    } else if(name < compareToOwn.name){
                        return -1;
                    } else {
                        return 1;
                    }
                } else if( role == 'Joint' && compareToOwn.role != 'Joint' ){
                    return -1;
                } else {
                    return 1;
                }
            } else if(role == 'Client' && compareToOwn.role != 'Client'){
                return -1;
            } else {
                return 1;
            }
        }
    }
    
    public String formatDate(Date d) {
        DateTime dt = DateTime.newInstance(d.year(), d.month(), d.day());
        return dt.format('d MMMMM yyyy');
    }
}