force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Advice_Status__c.field-meta.xml
<CustomField>
    <fullName>Advice_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
                <default>true</default>
                <label>Setup</label>
            </value>
            <value>
                <fullName>Data gathering</fullName>
            </value>
            <value>
                <fullName>Risk Call</fullName>
            </value>
            <value>
                <fullName>Ready for suitability</fullName>
            </value>
            <value>
                <fullName>Suitability in progress</fullName>
            </value>
            <value>
                <fullName>Prepare advice</fullName>
            </value>
            <value>
                <fullName>Present advice</fullName>
            </value>
            <value>
                <fullName>Deck complete</fullName>
            </value>
            <value>
                <fullName>Await decision</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>In fulfilment</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Suitability Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Meeting held</fullName>
                <isActive>false</isActive>
                <label>Meeting held</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/AdviceType__c.field-meta.xml
<CustomField>
    <fullName>AdviceType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A reference to advice type where variables are held that control business logic of the advice record.</description>
    <label>Advice type</label>
    <referenceTo>AdviceType__c</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Fact_find_requirements__c.field-meta.xml
<CustomField>
    <fullName>Fact_find_requirements__c</fullName>
    <label>Fact find requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Update required</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/FulfilmentUpdateStatus__c.field-meta.xml
<CustomField>
    <fullName>FulfilmentUpdateStatus__c</fullName>
    <description>Indicates whether this advice is receiving fulfilment updates</description>
    <label>Fulfilment update status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Receiving updates</fullName>
            </value>
            <value>
                <fullName>Temporary pause on updates</fullName>
            </value>
            <value>
                <fullName>Never receiving updates</fullName>
            </value>
            <value>
                <fullName>Not receiving updates</fullName>
            </value>
            <value>
                <fullName>Final update sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/G_Drive_Advice_Folder__c.field-meta.xml
<CustomField>
    <fullName>G_Drive_Advice_Folder__c</fullName>
    <label>Google Drive advice folder</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/New_LOAs_required__c.field-meta.xml
<CustomField>
    <fullName>New_LOAs_required__c</fullName>
    <inlineHelpText>This will start a workflow to create and send out new LOAs</inlineHelpText>
    <label>Additional LOAs required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/New_or_existing_client__c.field-meta.xml
<CustomField>
    <fullName>New_or_existing_client__c</fullName>
    <label>New or existing client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Update_valuations__c.field-meta.xml
<CustomField>
    <fullName>Update_valuations__c</fullName>
    <inlineHelpText>Yes - will create a task for a specialist to update valuations for related financial products</inlineHelpText>
    <label>Update valuations</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/recordTypes/Advice_RT_General_Advice.recordType-meta.xml
<RecordType>
    <fullName>Advice_RT_General_Advice</fullName>
    <active>true</active>
    <description>RT for general advice, this will be broken into many</description>
    <label>General Advice</label>
</RecordType>

force-app/main/default/objects/Advice__c/recordTypes/TopUp.recordType-meta.xml
<RecordType>
    <fullName>TopUp</fullName>
    <active>true</active>
    <description>For lump sum or regular deposits to GIA, ISA, SIPP, JISA, JSIPP.</description>
    <label>Top up</label>
</RecordType>

force-app/main/default/objects/AdviceType__c/AdviceType__c.object-meta.xml
<CustomObject>
    <description>Models the types of advice that we provide to customers and how things vary between them. Used to drive business logic on actual advice.</description>
    <label>Advice Type</label>
    <nameField>
        <label>Advice Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AdviceType__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name for an advice type. Used to provide consistency in business logic across environments.</description>
    <label>Developer Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataFactoryAdvice.cls
/**
 * This class can be used for test purposes only in test classes or in seeing configuration data. 
 * It can create advice records against a specified household.
 */
public without sharing class DataFactoryAdvice {

    private final static String ADVICE_GENERIC_RECORD_TYPE_DEVELOPER_NAME = 'Advice_RT_General_Advice';
    private final static String ADVICE_TOP_UP_RECORD_TYPE_DEVELOPER_NAME = 'TopUp';
    private final static Id ADVICE_GENERIC_RECORD_TYPE_ID = Schema.SObjectType.Advice__c.getRecordTypeInfosByDeveloperName().get(ADVICE_GENERIC_RECORD_TYPE_DEVELOPER_NAME).getRecordTypeId();
    private final static Id ADVICE_TOP_UP_RECORD_TYPE_ID = Schema.SObjectType.Advice__c.getRecordTypeInfosByDeveloperName().get(ADVICE_TOP_UP_RECORD_TYPE_DEVELOPER_NAME).getRecordTypeId();

    // Creates ad-hoc advice
    public static Advice__c createAdHocAdvice(Id householdId){
        Advice__c advice = new Advice__c(
            Advice_Household__c = householdId,
            RecordTypeId = ADVICE_GENERIC_RECORD_TYPE_ID,
            New_or_existing_client__c = 'Existing',
            Partner__c = [ SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ].Id,
            Fact_find_requirements__c = 'Not required',
            G_Drive_Advice_Folder__c = 'google.com',
            Update_valuations__c = 'No',
            New_LOAs_required__c = 'No', 
            Advice_Status__c = 'Data Gathering',
            Subject__c = 'Test advice',
            Name = 'Test advice',
            FulfilmentUpdateStatus__c = 'Receiving updates',
            AdviceType__c = [SELECT Id FROM AdviceType__c WHERE DeveloperName__c = 'AD_HOC' ].Id
        );
        insert advice;
        System.debug(advice);
        return advice;
    }   
}