force-app/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FulfilmentType__c/FulfilmentType__c.object-meta.xml
<CustomObject>
    <description>Used to store process specific information for each type of fulfilment</description>
    <label>Fulfilment Type</label>
    <nameField>
        <label>Fulfilment Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfilment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FulfilmentType__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The product that  this fulfilment type is associated with</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Fulfilment Types</relationshipLabel>
    <relationshipName>Fulfilment_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FulfilmentType__c/fields/RecommendationType__c.field-meta.xml
<CustomField>
    <fullName>RecommendationType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The recommendation type that this fulfilment type relates to</description>
    <label>Recommendation Type</label>
    <referenceTo>RecommendationType__c</referenceTo>
    <relationshipName>Fulfilment_types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Will store the kinds of products we can provide in the post-cheerIO world.</description>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product category this falls under</description>
    <label>Product type</label>
    <referenceTo>ProductType__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductType__c/ProductType__c.object-meta.xml
<CustomObject>
    <description>Used to indicate which fields are relevant for the Product object</description>
    <label>Product type</label>
    <nameField>
        <label>Product type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Provider_Names__c/Public_Provider_Names__c.object-meta.xml
<CustomObject>
    <label>Public Provider List</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Provider List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecommendationType__c/RecommendationType__c.object-meta.xml
<CustomObject>
    <description>Object to control which fields are visible on recommendations, based on the kind of recommendation they are.</description>
    <label>Recommendation Type</label>
    <nameField>
        <label>Recommendation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommendation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AdvicePlanningPioritisationHelperTest.cls
@isTest
public with sharing class AdvicePlanningPioritisationHelperTest {

    @isTest
    static void getAdvice_success() {
        List<sObject> ls = Test.loadData(Public_Provider_Names__c.sObjectType, 'ProviderRef');
        List<sObject> ls3 = Test.loadData(RecommendationType__c.sObjectType, 'RecRef');
        List<sObject> ls4 = Test.loadData(ProductType__c.sObjectType, 'ProductTypeRef');
        List<sObject> ls2 = Test.loadData(Product__c.sObjectType, 'ProductRef');
        List<sObject> ls5 = Test.loadData(FulfilmentType__c.sObjectType, 'FTRef');
        Integer numClients = 2;
        Integer numChildren = 2;
        String householdStatus = 'Active';
        String profileType = 'Full'; 
        DataFactory df = new DataFactory();
        Id householdId = df.createHousehold('Test', numClients, numChildren, householdStatus, profileType);
        Advice__c advice = df.createAdvice(2, householdId);
        List<Advice__c> records = AdvicePlanningPioritisationHelper.getAdvice();
        System.Assert.areEqual(records.size(), 1, 'Expected 1 advice record');
    }    
}