unpackaged/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Advice_Status__c.field-meta.xml
<CustomField>
    <fullName>Advice_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Setup</fullName>
                <default>true</default>
                <label>Setup</label>
            </value>
            <value>
                <fullName>Data gathering</fullName>
            </value>
            <value>
                <fullName>Risk Call</fullName>
            </value>
            <value>
                <fullName>Ready for suitability</fullName>
            </value>
            <value>
                <fullName>Suitability in progress</fullName>
            </value>
            <value>
                <fullName>Prepare advice</fullName>
            </value>
            <value>
                <fullName>Present advice</fullName>
            </value>
            <value>
                <fullName>Deck complete</fullName>
            </value>
            <value>
                <fullName>Await decision</fullName>
            </value>
            <value>
                <fullName>Awaiting acceptance</fullName>
            </value>
            <value>
                <fullName>In fulfilment</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Suitability Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Meeting held</fullName>
                <isActive>false</isActive>
                <label>Meeting held</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/AdviceType__c.field-meta.xml
<CustomField>
    <fullName>AdviceType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A reference to advice type where variables are held that control business logic of the advice record.</description>
    <label>Advice type</label>
    <referenceTo>AdviceType__c</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/Assigned_planner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_planner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Suitability Planner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_planner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/DataAnalysisStatus__c.field-meta.xml
<CustomField>
    <fullName>DataAnalysisStatus__c</fullName>
    <description>Indicates the progress of data analysis</description>
    <label>Data analysis status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not required</fullName>
            </value>
            <value>
                <fullName>Not started</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Advice__c/fields/DataGatheringStatus__c.field-meta.xml
<CustomField>
    <fullName>DataGatheringStatus__c</fullName>
    <description>Indicates the progress of the information gathering on products</description>
    <label>Data gathering status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not required</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not started</fullName>
                <isActive>false</isActive>
                <label>Not started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/DeckStatus__c.field-meta.xml
<CustomField>
    <fullName>DeckStatus__c</fullName>
    <label>Deck status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planner review</fullName>
            </value>
            <value>
                <fullName>Resolve planner comments</fullName>
            </value>
            <value>
                <fullName>Partner review</fullName>
            </value>
            <value>
                <fullName>Resolve partner comments</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/IsPriority__c.field-meta.xml
<CustomField>
    <fullName>IsPriority__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by planning to capture advice cases that have been prioritised in agreement with the partner.</description>
    <label>Priority</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/NarrativeStatus__c.field-meta.xml
<CustomField>
    <fullName>NarrativeStatus__c</fullName>
    <label>Narrative status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planner review</fullName>
            </value>
            <value>
                <fullName>Resolve planner comments</fullName>
            </value>
            <value>
                <fullName>Partner review</fullName>
            </value>
            <value>
                <fullName>Resolve partner comments</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/New_or_existing_client__c.field-meta.xml
<CustomField>
    <fullName>New_or_existing_client__c</fullName>
    <label>New or Existing client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/OW_review__c.field-meta.xml
<CustomField>
    <fullName>OW_review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Concurrent Annual Review to Advice</description>
    <inlineHelpText>If populated, this means the advice is being given as part of an ongoing review. 

This field is read only on the advice. To set it, please link to this advice from a review record.</inlineHelpText>
    <label>Review</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The advice and annual review must be linked to the same household.

(Admin message: filter criteria on OW_review__c field on the Advice__c object)</errorMessage>
        <filterItems>
            <field>$Source.Advice_Household__c</field>
            <operation>equals</operation>
            <valueField>OW_review__c.OW_household__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OW_review__c</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Advice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/PlanningNotes__c.field-meta.xml
<CustomField>
    <fullName>PlanningNotes__c</fullName>
    <description>For the planning team to capture notes as part of managing their work.</description>
    <label>Planning notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/RetirementCallStatus__c.field-meta.xml
<CustomField>
    <fullName>RetirementCallStatus__c</fullName>
    <description>This field captures whether the status around retirement call for a given bit of advice - is one required or not and whether it&#39;s complete, if it was required.</description>
    <label>Retirement call status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT_REQUIRED</fullName>
                <label>Not required</label>
            </value>
            <value>
                <fullName>REQUIRED</fullName>
                <label>Required</label>
            </value>
            <value>
                <fullName>PRESENT</fullName>
                <label>Present content</label>
            </value>
            <value>
                <fullName>COMPLETE</fullName>
                <label>Complete</label>
            </value>
            <value>
                <fullName>NEVER_REQUIRED</fullName>
                <label>Never required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Advice__c/fields/RiskCallDate__c.field-meta.xml
<CustomField>
    <fullName>RiskCallDate__c</fullName>
    <description>The date of the risk call</description>
    <label>Risk call date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Advice__c/fields/RiskCallStatus__c.field-meta.xml
<CustomField>
    <fullName>RiskCallStatus__c</fullName>
    <defaultValue>&quot;Not ready&quot;</defaultValue>
    <description>Indicates the progress towards the risk call</description>
    <label>Risk call status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not required</fullName>
                <default>true</default>
                <label>Not required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdviceType__c/AdviceType__c.object-meta.xml
<CustomObject>
    <description>Models the types of advice that we provide to customers and how things vary between them. Used to drive business logic on actual advice.</description>
    <label>Advice Type</label>
    <nameField>
        <label>Advice Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OW_review__c/OW_review__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage the review process with existing clients. It&#39;s a fairly lightweight place to manage the upcoming reviews and track the initial conversations. The resulting workflows - preparation of decks, advice etc - are all managed in the advice object.</description>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OW_review__c/fields/Advice__c.field-meta.xml
<CustomField>
    <fullName>Advice__c</fullName>
    <inlineHelpText>Does the advice make sense and seem to be both suitable, but also the right thing for the client? If not, please flat to planner/head planner</inlineHelpText>
    <label>Advice</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OW_review__c/fields/Assigned_Planner__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Planner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the user who is the assigned planner for the review.</description>
    <label>Assigned planner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Annual_Reviews1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OW_review__c/fields/OW_due_date__c.field-meta.xml
<CustomField>
    <fullName>OW_due_date__c</fullName>
    <description>The final day of the customer&#39;s annual review month. This value is set at the time of creation so that if the annual review month changes for the future, this due date does not.</description>
    <label>Due date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/AdvicePlanningPioritisationHelper.cls
/*********************************************************
Apex Class Name    : AdvicePlanningPioritisationHelper
Created Date       : 2024-09-10
@description       : This class is a helper for a planning advice management/prioritisation LWC. Runs without sharing so summary level view always visible. 
@author            : Cian Morrissey
Modification Log:
Date         Author                               Modification
2024-09-10   Cian Morrissey                       Initial Version
*********************************************************/
public without sharing class AdvicePlanningPioritisationHelper {

    /**********************************************************
    @Method Name    : getAdvice
    @author         : Cian Morrissey
    @description    : This method runs a query to get the advice data then returns it
    @param          : N/A
    @return         : advice - the list of advice returned
    *********************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Advice__c> getAdvice(){
        List<String> adviceStatuses = new List<String>{'Data gathering','Risk Call','Suitability in progress'};
        List<Advice__c> advice = [SELECT Id, Name, New_or_existing_client__c, PlanningNotes__c, IsPriority__c, AdviceType__r.Name, Advice_Household__r.Name,  Assigned_planner__c, Assigned_planner__r.Name, Advice_status__c, Partner__r.Name, RetirementCallStatus__c, RiskCallStatus__c, RiskCallDate__c, NarrativeStatus__c, DeckStatus__c, OW_review__c, OW_review__r.OW_due_date__c FROM Advice__c WHERE Advice_status__c IN ('risk call','data gathering','suitability in progress') WITH SECURITY_ENFORCED ORDER BY Advice_status__c DESC, DeckStatus__c DESC, NarrativeStatus__c DESC, RiskCallStatus__c DESC, RiskCallDate__c ASC NULLS LAST, DataAnalysisStatus__c DESC, DataGatheringStatus__c DESC, CreatedDate ASC];
        return advice;
    }
}