unpackaged/main/default/objects/Advice__c/Advice__c.object-meta.xml
<CustomObject>
    <label>Advice</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advice__c/fields/Advice_Household__c.field-meta.xml
<CustomField>
    <fullName>Advice_Household__c</fullName>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the household field must be a household. 

(Admin message: lookup filter criteria not met on Advice_Household on the Advice__c object)</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>IndustriesHousehold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advice</relationshipLabel>
    <relationshipName>Advice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/EmailConfiguration__c.object-meta.xml
<CustomObject>
    <description>Holds the details of emails that is used to drive automation and business validation.</description>
    <label>Email Configuration</label>
    <nameField>
        <label>Email Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailConfiguration__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <description>The developer name of the email template this email configuration is associated with.</description>
    <externalId>true</externalId>
    <inlineHelpText>Must match the developer name of the email template.</inlineHelpText>
    <label>Developer Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EmailConfiguration__c/fields/Necessity__c.field-meta.xml
<CustomField>
    <fullName>Necessity__c</fullName>
    <label>Necessity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/EmailHiString.cls
public class EmailHiString {
	public String objectIdString{get;set;}
	public String emailTemplateDevName{get;set;}
    public String hiString;

    public String getHiString() {
        Id householdId;
        if(String.isBlank(objectIdString)){
            objectIdString = ApexPages.currentPage().getParameters().get('objectIdString');
        }
        Id objectId = Id.valueOf(objectIdString);
        String objectApiName = objectId.getSObjectType().getDescribe().getName();
        if(objectApiName == 'Account'){
            householdId = objectId;
        } else if (objectApiName == 'Advice__c'){
            householdId = [SELECT Advice_household__c FROM Advice__c where Id = :objectId].Advice_household__c;
        }
        if(String.isBlank(emailTemplateDevName)){
            emailTemplateDevName = ApexPages.currentPage().getParameters().get('emailTemplateDevName');
        }
        List<EmailConfiguration__c> ecs = [SELECT Id, Necessity__c FROM EmailConfiguration__c WHERE DeveloperName__c =: emailTemplateDevName];
        String necessity = [SELECT Id, Necessity__c FROM EmailConfiguration__c WHERE DeveloperName__c =: emailTemplateDevName][0].Necessity__c;
        
        // Generate a list of the people in the household using their first or preferred name appropriately and sort
        List<AccountContactRelation> household_members = [SELECT Contact.Account.ServiceContactPreferences__pc, Contact.Account.FirstName, Contact.Account.FinServ__PreferredName__pc FROM AccountContactRelation WHERE AccountId =: householdId AND Roles = 'Client' AND Contact.Email != null];
        List<String> recipients = new List<String>();
        String name;
        for( AccountContactRelation household_member : household_members ){
            if (necessity == 'Required' || household_member.Contact.Account.ServiceContactPreferences__pc == 'All emails') {
                if( String.isBlank(household_member.Contact.Account.FinServ__PreferredName__pc) ){
                    name = household_member.Contact.Account.FirstName;
                } else {
                    name = household_member.Contact.Account.FinServ__PreferredName__pc;
                }
            	recipients.add(name);
           }
        }
        recipients.sort();
        
        // Loop through the recipients to produce the recipient details to be displayed in the email
        Integer n = recipients.size();
        Integer i = 0;
        hiString = 'Hi ';
        
        if ( n == 1 ) {
            hiString = hiString + recipients[0] + ',';
        } else {
            i = 0;
            for(String recipient : recipients){
                if ( i < n - 2 ) {
                    hiString = hiString + recipients[i] + ', ';
                } else if ( i == n - 2 ) {
                    hiString = hiString + recipients[i] + ' & ';
                } else {
                    hiString = hiString + recipients[i] + ',';
                }
                i = i + 1;
            }
        }
        return hiString;
    }
}